### ISSUE TITLE
Where to import icons

### ISSUE THREAD

**Issue by P4sca1** [FortAwesome/vue-fontawesome#100]
Currently I'm importing icons directly in my Vue Components (`.vue` files), which seems quite convenient to me, because I'm using the icons in the `<template> block` and I am importing them in the same file in the `<script> block`.
However if multiple components are used, it is importing the library and maybe duplicate icons every time, which leads to a higher file size due to the same code being at multiple places.
So, is there any way to solve this issue and only import every icon once?

**Comment by meteorlxy** [comment]
@P4sca1 

If you import `lodash` or so in different places, would you worry about that?

Or in Vue cases, sometimes we need to import `mapState` from 'vuex' in different components.

**Comment by P4sca1** [comment]
Hmm, you are right, guess I should not worry about this too much.
Importing the same icon twice is still better than importing all available icons like I did before :)
