### ISSUE TITLE
Icons are very large are startup with Nuxt

### ISSUE THREAD

**Issue by ThomasKientz** [FortAwesome/vue-fontawesome#103]
Similar to https://github.com/FortAwesome/vue-fontawesome/issues/14 :

All my icons are very big at startup, then (probably when css is applied) are scale to the desired size. 

![animation_preview](https://user-images.githubusercontent.com/10157845/41697797-bf33de94-7544-11e8-92dc-f7af97ddc40a.gif)

I am simply doing :

```
<template>
  <font-awesome-icon :icon="icon" />
</template>

<script>
import FontAwesomeIcon from "@fortawesome/vue-fontawesome"
import { faArrowRight } from "@fortawesome/fontawesome-pro-regular"

export default {
  components: {
      FontAwesomeIcon
   }
  computed: {
    icon() {
      return faCheckCircle
    }
  },
}
</script>
```

I have tried to configure fontawesome with : 

```
fontawesome.config = {
  autoAddCss: false
}
```

But the icons stay big with this.

Very annoying, using pro icons everywhere ! Any ideas ?

Thanks :)

**Comment by wheato** [comment]
#14 has resolved this. you need write the configure to nuxt.config.js as plugin.

**Comment by ThomasKientz** [comment]
@wheato thanks

I was missing :

```
//nuxt.config.js
css: [
  '@fortawesome/fontawesome/styles.css',
],
```

**Comment by leccyril** [comment]
i make it work just with this 

`//nuxt.config.js
css: [
  '@fortawesome/fontawesome/styles.css',
],

then in vue file 

   `    import {library, config} from "@fortawesome/fontawesome-svg-core";
     import {faCheck, faChevronRight, faChevronDown} from "@fortawesome/free-solid-svg-icons";
     import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

     config.autoAddCss = false

library.add(
	faCheck,
	faChevronRight,
	faChevronDown
);

export default {
	components: {
		FontAwesomeIcon
	},
}
</script>`

and it was working
