### ISSUE TITLE
Typo in Upgrading Guide

### ISSUE THREAD

**Issue by aquariuz** [FortAwesome/vue-fontawesome#107]
There's a typo in the [Upgrading Guide](https://github.com/FortAwesome/vue-fontawesome/blob/development/UPGRADING.md).

Under 'New way':
`import { library } from '@fontawesome/fontawesome-svg-core'`

Should be:
`import { library } from '@fortawesome/fontawesome-svg-core'`
(...fo**R**tawesome...)

**Comment by robmadole** [comment]
Got this fixed. Thanks!
