### ISSUE TITLE
Tree shaking not working correctly

### ISSUE THREAD

**Issue by mserajnik** [FortAwesome/vue-fontawesome#109]
I'm not sure if it's not just a webpack configuration issue on my end, but the tree shaking doesn't seem to work correctly when importing in a specific way.

E.g., if I import icons as described in the readme

```javascript
# main.js

import { library } from '@fontawesome/fontawesome-svg-core'
import {
  faCog,
  faInfo,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSort,
  faSpinner,
  faUser
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faCog, faInfo, faSearch, faSignInAlt, faSignOutAlt, faSort, faSpinner, faUser
)
```

my bundle size is around 900kb.

However, if I import them like this

```javascript
# main.js

import { library } from '@fontawesome/fontawesome-svg-core'
import { faCog } from '@fortawesome/free-solid-svg-icons/faCog'
import { faInfo } from '@fortawesome/free-solid-svg-icons/faInfo'
import { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch'
import { faSignInAlt } from '@fortawesome/free-solid-svg-icons/faSignInAlt'
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons/faSignOutAlt'
import { faSort } from '@fortawesome/free-solid-svg-icons/faSort'
import { faSpinner } from '@fortawesome/free-solid-svg-icons/faSpinner'
import { faUser } from '@fortawesome/free-solid-svg-icons/faUser'

library.add(
  faCog, faInfo, faSearch, faSignInAlt, faSignOutAlt, faSort, faSpinner, faUser
)
```

My bundle size is just about 400kb.

I use the component as described in the readme (in separate components though):

```vue
# Example Vue component

<template>
  <div>
    <font-awesome-icon icon="search" />
  </div>
</template>

<script>
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

export default {
  // […]
  components: {
    FontAwesomeIcon
  }
}
</script>
```

I have installed the following Font Awesome related packages:

```json
{
  "@fortawesome/fontawesome-svg-core": "^1.2.0",
  "@fortawesome/free-solid-svg-icons": "^5.1.0",
  "@fortawesome/vue-fontawesome": "^0.1.0"
}
```

I'm using the latest version of webpack (`4.12.1`). Here is my config:

```javascript
# webpack.common.js

const path = require('path')

const CleanWebpackPlugin = require('clean-webpack-plugin')
const { VueLoaderPlugin } = require('vue-loader')
const DotenvPlugin = require('dotenv-webpack')

module.exports = {
  entry: path.resolve(__dirname, 'src/main.js'),
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, 'dist')
  },
  resolve: {
    extensions: ['*', '.js', '.json', '.vue', '.scss'],
    alias: {
      '@@': path.resolve(__dirname, 'src')
    }
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            js: 'babel-loader'
          }
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.s?[ac]ss$/,
        use: [
          'style-loader',
          'postcss-loader',
          {
            loader: 'sass-loader',
            options: {
              includePaths: [
                path.resolve(__dirname, 'src/assets/scss')
              ]
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(path.resolve(__dirname, 'dist'), {
      verbose: false,
      watch: false
    }),
    new VueLoaderPlugin(),
    new DotenvPlugin()
  ],
  stats: {
    entrypoints: false,
    modules: false
  }
}
```

```javascript
# webpack.prod.js

require('dotenv').config()

const merge = require('webpack-merge')
const minifyHtml = require('htmlclean')

const CopyWebpackPlugin = require('copy-webpack-plugin')

const common = require('./webpack.common.js')

module.exports = merge(common, {
  plugins: [
    new CopyWebpackPlugin([
      {
        context: 'src',
        from: '**/*.html',
        transform: content => {
          content = content.toString()

          content = content.replace(
            '<title></title>', `<title>${process.env.TITLE}</title>`
          )

          return minifyHtml(content)
        }
      },
      {
        context: 'src',
        from: '**/*',
        ignore: '**/*.{html,scss,js,vue,DS_Store}'
      },
      {
        context: 'src',
        from: '.**/*',
        ignore: '.**/*.{html,scss,js,vue,DS_Store}'
      }
    ])
  ]
})
```

My build task is simply `webpack -p --config webpack.prod.js`.

**Comment by robmadole** [comment]
@mserajnik if you can post a repo link or a reproducible example we can take a look

**Comment by mserajnik** [comment]
@robmadole Thank you, I have created a simple example for you to try yourself: https://github.com/mserajnik/fontawesome-tree-shaking-issue-example

__Usage:__ Install dependencies (`yarn install`) and run the webpack build (`yarn run build`).

If you take a look at https://github.com/mserajnik/fontawesome-tree-shaking-issue-example/blob/master/src/main.js#L6-L26 you can see I have both variants in there (with the one from your readme commented out).

If you run `yarn run build` just as it is, it should produce a bundle that's `111 KiB` in size. However, if you comment out "my" variant and instead try the one from your readme, the bundle should come out with a size of `585 KiB`.

If you compare the two bundles directly (`dist/app.js`, save it somewhere after the first build and before running the second one or you will just overwrite it), it seems like the `585 KiB` one contains many more SVG data for the icons (probably for all the solid icons?) than the `111 KiB` one.

**Comment by robmadole** [comment]
@mserajnik I've created this using vue-cli 3.

https://github.com/robmadole/vue-fontawesome-issue-109

Tree shaking works with this. I don't see any issues with your reproduction but you might compare your config to the vue-cli config by using `vue inspect`. There are a lot of moving parts.

**Comment by mserajnik** [comment]
@robmadole Thank you, it seems like the issue was with my Babel configuration.

I've been using the following:

```json5
// .babelrc

{
  "presets": ["env"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

While `@vue/cli` uses [@vue/babel-preset-app](https://www.npmjs.com/package/@vue/babel-preset-app):

```json5
// .babelrc

{
  "presets": ["@vue/app"]
}
```

Using the same preset now gives me the desired result: it doesn't seem to make a difference anymore which of the two `import` styles I use.

I've had to adjust some other stuff, such as upgrading to `"@babel/core": "7.0.0-beta.47"` from `"babel-core": "^6.26.3"` and fixing it to that version because using the latest beta (`51`) `@vue/babel-preset-app` would spam the console with wrong peer dependency version errors.

But all in all, it seems to work fine now. Still, I'll think about switching my project over to `@vue/cli` instead of running my own webpack configuration just so I won't have to spend more time in the future trying to figure out why certain stuff doesn't work. It also seems to feature some useful stuff like caching and code splitting which I haven't even bothered to configure in my own config yet. :D

**Comment by robmadole** [comment]
Nice. Good to know @mserajnik. Yeah Vue Cli is pretty great. We've got our own mess of a Webpack config for fontawesome.com that we'll likely switch to `cli` in the near future. It's a great setup they give you.

**Comment by mserajnik** [comment]
@robmadole

Already done with the switch, that was pretty painless. :)

My only (small) gripe so far are the peer dependency warnings of Yarn when using `cli`, just because it "feels wrong" to ignore warnings, even though it's perfectly safe and working as intended in this case:

```console
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.4" has unmet peer dependency "webpack@>=2".
warning "@vue/cli-plugin-eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.1.0" has unmet peer dependency "eslint@>=3.19.0".
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0-alpha.0" has unmet peer dependency "eslint@>=5.0.0-alpha.2".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.13.0" has unmet peer dependency "eslint@2.x - 5.x".
warning " > sass-loader@7.0.3" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
```

But it [looks like](https://github.com/vuejs/vue-cli/issues/1243) there's not much they can do about it on their end.

**Comment by carestad** [comment]
Is there a way to get this working with Babel v6 though? This caught my eye as well when peeking through the un-minified vendor.js file we have, all the icons are included, although we only use a handful of them
