### ISSUE TITLE
How to import the same icon from different packages?

### ISSUE THREAD

**Issue by dekst** [FortAwesome/vue-fontawesome#113]
import { faAddressBook } from '@fortawesome/free-solid-svg-icons'
import { faAddressBook } from '@fortawesome/free-regular-svg-icons'
library.add(faAddressBook)

gets error
Module build failed: Duplicate declaration "faAddressBook"

Expect to be able to use
font-awesome-icon :icon="['fas', 'address-book']"
font-awesome-icon :icon="['far', 'address-book']"

**Comment by robmadole** [comment]
Hey there @dekst. We have a [doc here that mentions this](https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons).

```
import { faAddressBook as fasAddressBook } from '@fortawesome/free-solid-svg-icons'
import { faAddressBook as farAddressbook } from '@fortawesome/free-regular-svg-icons'
```
