### ISSUE TITLE
Clarify Icon Prop API in README?

### ISSUE THREAD

**Issue by jbenner-radham** [FortAwesome/vue-fontawesome#114]
Earlier I was getting browser errors like so:

> Could not find one or more icon(s) Object { prefix: "fas", iconName: "signOutAlt" } Object {  }

Which perplexed me for a moment because I had other icons displaying just fine. After tinkering around for a couple minutes I discovered that when you're adding icons via `library.add()` that have multiple words in their name you don't pass them as a camel case string to the component e.g.

```vue
<font-awesome-icon icon="signOutAlt"/>
```

Instead you need to pass them in hyphenated form to the component e.g.

```vue
<font-awesome-icon icon="sign-out-alt"/>
```

In the README the usage examples all use single word icon names, so I suggest that a note regarding multi-word icon names be added to the usage section. If it's cool I'd like to submit a PR with the aforementioned changes made to the README.

P.S. Thank you for all the hard work that's put into a great open source library for the community.

**Comment by robmadole** [comment]
@jbenner-radham absolutely a PR would be welcome :) That will be an easy click on the "Merge" button!

**Comment by jbenner-radham** [comment]
@robmadole Awesome thank you! I've created a merge request.
