### ISSUE TITLE
How to define "Regular" or "Solid" bookmark icon

### ISSUE THREAD

**Issue by tophat1986** [FortAwesome/vue-fontawesome#117]
With the "**bookmark**" icon there is 2 variants.  They have the same name, so I need to define the weight I believe to use the **regular** version as solid is appearing by default.  My intention is to hover over it and then switch to the solid bookmark.  

I'm not sure how to achieve this with a vue component based icon.  Can't see anything in the docs about setting this option.  I can see how to rotate, change size which I can achieve.  This code I tried however will set the size, but not the weight which I thought should've worked?

`<font-awesome-icon icon="bookmark" style="font-size: 28px; font-weight: 400;"/>`

**Comment by robmadole** [comment]
We talk about that [here](https://github.com/FortAwesome/vue-fontawesome#shorthand-that-assumes-a-prefix-of-fas) @tophat1986. If you still need assistance I'd be happy to re-open this.
