### ISSUE TITLE
How can i get social icons?

### ISSUE THREAD

**Issue by sir-kain** [FortAwesome/vue-fontawesome#120]
Social icons (facebook, github, git, linkedIn, ...) are not present in the package `@fortawesome/free-solid-svg-icons`

Is there another way to get them?

Otherwise I can use the other icons following the doc
```js
import Vue from 'vue'
import App from './App'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faCoffee)
```

**Comment by robmadole** [comment]
Try `@fortawesome/free-brands-svg-icons`. https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons#packages
