### ISSUE TITLE
Feature Request: List of used icons for production

### ISSUE THREAD

**Issue by Blackcatz1911** [FortAwesome/vue-fontawesome#121]
When developing a Website/Webapp
`import { fas } from '@fortawesome/free-solid-svg-icons'`
is my choice to go because i dont have to import every single icon to test and use. But when deploying/going into production the import of fas seems like an overkill. So a small module/component to detect and create a list of used icon would be awesome.

Example output: 
```
import {
  faChevronUp, faEnvelope, faCogs, faSearch, faArchive, faArrowsAltH, faExclamationTriangle
} from '@fortawesome/free-solid-svg-icons'

library.add(faChevronUp, faEnvelope, faCogs, faSearch, faArchive, faArrowsAltH, faExclamationTriangle)
```

**Comment by Herteby** [comment]
Since your icon props can be dynamic and depend on your app state, the only way to know which icons are needed is to record it during automated testing. And if you don't have complete test coverage, it could miss icons.

**Comment by robmadole** [comment]
@Blackcatz1911 yeah this is a nice idea but the implementation would be unreliable (for the reasons that @Herteby is stating).

Going to close this is not a direction we want to explore.
