### ISSUE TITLE
[Vue warn]: Invalid prop: custom validator check failed for prop "size".

### ISSUE THREAD

**Issue by passion044** [FortAwesome/vue-fontawesome#122]
[Vue warn]: Invalid prop: custom validator check failed for prop "size".

I get this error in vue, I do not know the cause. When I insert size, I get this error. What should I do?

**Comment by robmadole** [comment]
What are you passing it?

**Comment by robmadole** [comment]
Here's the validator https://github.com/FortAwesome/vue-fontawesome/blob/master/src/components/FontAwesomeIcon.js#L72

**Comment by Boevsson** [comment]
Hey I'm having the same issue. Im either passing lg or md. My import in main.js is the following:
`import {library} from '@fortawesome/fontawesome-svg-core'
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'
import { fas } from '@fortawesome/free-solid-svg-icons'

library.add(fas);
Vue.component('font-awesome-icon', FontAwesomeIcon);
`

**Comment by Boevsson** [comment]
Ahhh. Yea. Thought the friend who entered those already checked. Thanks :D

**Comment by BigMichelle** [comment]
Try to write ' size="1x" '  1x, 2x, 3x...

**Comment by leonardobrito** [comment]
Accepted values:
`"xs", "lg", "sm", "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x", "9x", "10x"`

**Comment by seyfer** [comment]
@robmadole , @leonardobrito is it correct, that `px` also supported?
if I set `size: 25px` then I get SVG with custom style `font-size: 25px` as expected, but also I get Vue invalid property error, because of custom validator.
```
    size: {
      type: String,
      default: null,
      validator: (value) => ['lg', 'xs', 'sm', '1x', '2x', '3x', '4x', '5x', '6x', '7x', '8x', '9x', '10x'].indexOf(value) > -1
    },
```

UPD:
sorry, `size` in PX was a custom solution. ignore me.
