### ISSUE TITLE
Can't add brand icons...

### ISSUE THREAD

**Issue by nicroto** [FortAwesome/vue-fontawesome#123]
Following the docs, this is how I add a couple of icons within my NUXT project.

Package.json:
```json
{
  ...
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.0",
    "@fortawesome/free-brands-svg-icons": "^5.1.0",
    "@fortawesome/free-regular-svg-icons": "^5.1.0",
    "@fortawesome/free-solid-svg-icons": "^5.1.0",
    "@fortawesome/vue-fontawesome": "^0.1.0",
    ...
  }
  ...
}
```

```javascript
// nuxt.config.js

export default {
    ...
    plugins: [
        ...
        "~/plugins/font-awesome",
        ...
    ],
    ...
};
```

```javascript
// ~/plugins/font-awesome.js

import Vue from "vue";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";


// icon imports

// works!
import { faThumbsUp as thumbsUp_SolidIcon } from "@fortawesome/free-solid-svg-icons";
library.add (thumbsUp_SolidIcon);

// THE PROBLEMATIC ICON
import { faFacebookF } from "@fortawesome/free-brands-svg-icons";
library.add (faFacebookF);


// register component
Vue.component("font-awesome-icon", FontAwesomeIcon);

Vue.config.productionTip = false;
```

And this is how I use the icons:

```javascript
<font-awesome-icon icon="thumbs-up" />
<font-awesome-icon icon="facebook-f" />
```

I get this error in the console:

```
Could not find one or more icon(s) {prefix: "fas", iconName: "facebook-f"} {}
```

And I can clearly see the facebook icon on the correct path and the prefix inside (whatever this prefix actually means as context) is "fab" not "fas".

Is it possible that nuxt picks up on the .ts file and compiles (transpiles) that incorrectly instead of getting the js file? Edit: just tried referring to the js files directly... don't know what's going on with this.

I can't believe something that was so simple to use previously, would now involve such issues and frustration...

**Comment by nicroto** [comment]
This method in FontAwesomeIcon.js always would return an icon description with prefix "fas":

```javascript
function normalizeIconArgs (icon) {
  if (icon === null) {
    return null
  }

  if (typeof icon === 'object' && icon.prefix && icon.iconName) {
    return icon
  }

  if (Array.isArray(icon) && icon.length === 2) {
    return { prefix: icon[0], iconName: icon[1] }
  }

  if (typeof icon === 'string') {
    return { prefix: 'fas', iconName: icon }
  }
}
```

**Comment by nicroto** [comment]
Finally figured out what's going on.

```javascript
<font-awesome-icon :icon="['fab', 'facebook-f']" />
```

The boilerplate I need to add 2 icons is larger than starting up an http server...

**Comment by genu** [comment]
This might be a bug, because this should work as well:
```html
<font-awesome-icon icon="facebook-f" prefix="fab"/>
```

**Comment by danieldanielecki** [comment]
Same in Angular, it worked out: `<fa-icon style="font-size: 2rem;" [icon]="['fab', 'facebook-f']"></fa-icon>`.

**Comment by regalstreak** [comment]
Why wont the documentation say this

**Comment by claide** [comment]
Additionally, you can use integrated sizing from [here](https://github.com/FortAwesome/vue-fontawesome#basic).

`<font-awesome-icon :icon="['fab', 'github-alt']" size="lg" />`

**Comment by Akashaj09** [comment]
I only want to add fa icon not fas or fab. how? Seems like it's not working.

**Comment by claide** [comment]
@Akashaj09 what have you done so far? Make sure you installed the required packages and call them. Pls read the docs you can find it there.
