### ISSUE TITLE
Document how to use the same icon from different sets

### ISSUE THREAD

**Issue by dantheother** [FortAwesome/vue-fontawesome#125]
I think @jeitneir's excellent comment on #77 about how to import an icon with an alias should be incorporated into the documentation. Perhaps I'm just stupid, but it took me a while to work out how to use check circle from both the solid and the regular set.

*to be clear, this is a copy of @jeitneir's example from #77*
```
import {
  faEdit
} from '@fortawesome/fontawesome-free-solid'

import {
  faEdit as faEditRegular
} from '@fortawesome/fontawesome-free-regular'

fontawesome.library.add(
  faEdit,
  faEditRegular
)
```

**Comment by robmadole** [comment]
Agreed. I'll get it on the list and get to it as I can. If someone wants to put up a PR I'd be happy to merge it.

**Comment by tophat1986** [comment]
This is a update must please :)

Given there is 151 "Regular" "Free" icons, I don't understand why the doc states "Regular" as _more_ styles - when I think it should be under the standard **Installation** in my opinion?

Also, the package for "Core" at first I thought was maybe including the regular hence the name similar meanings.  
`$ npm i --save @fortawesome/fontawesome-svg-core`

**Comment by NJM8** [comment]
I'd like to add to this for those who find it, and as a suggestion in the documentation, when you use the same icons from different libraries and you alias the import, you do not use the alias in your icon usage, you still use the regular name. 

```js
import { faStar } from "@fortawesome/pro-regular-svg-icons/faStar";
import { faStar as faStarSolid } from "@fortawesome/pro-solid-svg-icons/faStar";

library.add(
  faStar,
  faStarSolid
);
```
```html
          <font-awesome-icon 
            :icon="['fas', 'star']"/>
          <font-awesome-icon 
            :icon="['far', 'star']"/>
```

**Comment by Adavo** [comment]
This is gold. Please add this to the doc ASAP. I cannot recover the time stupidly spent on finding how to do so but it can save next one's time :-)

**Comment by vhoyer** [comment]
It's already in the docs, can't this issue be closed?

**Comment by dantheother** [comment]
Good point @vhoyer - closing now

**Comment by dlishtvan** [comment]
> It's already in the docs, can't this issue be closed?

Can you give link?

**Comment by vhoyer** [comment]
I think [this section](https://github.com/FortAwesome/vue-fontawesome#import-the-same-icon-from-different-styles) is what you search for, friend :D

**Comment by NJM8** [comment]
Could we add to that section to make it explicitly clear how to use those icons?

`
import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee as fasCoffee } from '@fortawesome/pro-solid-svg-icons'
import { faCoffee as farCoffee } from '@fortawesome/pro-regular-svg-icons'
import { faCoffee as falCoffee } from '@fortawesome/pro-light-svg-icons'
import { faCoffee as fadCoffee } from '@fortawesome/pro-duotone-svg-icons'

library.add(fasCoffee, farCoffee, falCoffee, fadCoffee)

          <font-awesome-icon 
            :icon="['fas', 'coffee']"/>
          <font-awesome-icon 
            :icon="['far', 'coffee']"/>
          <font-awesome-icon 
            :icon="['fal', 'coffee']"/>
          <font-awesome-icon 
            :icon="['fad', 'coffee']"/>
`

The usage is what is confusion because it does not necessarily match the import.

**Comment by robmadole** [comment]
Sure @NJM8! PR's are welcome.
