### ISSUE TITLE
Wrong documentation for style attribute on the component

### ISSUE THREAD

**Issue by Terrijoo** [FortAwesome/vue-fontawesome#126]
Hello everyone,

I had the same issue giving a color (or style in general) to an icon, like in this issue: #112 
Figured that the documentation on the readme was misleading: [Look at the Layers part](https://github.com/FortAwesome/vue-fontawesome#advanced)
There it's a simple String, so I guess this is a documentation error?

Or am I overseeing something?

**Comment by robmadole** [comment]
Ah yes, got it fixed in `master`. Thanks @Terrijoo
