### ISSUE TITLE
What is if i have some icons hardcoded in css / scss files??

### ISSUE THREAD

**Issue by altraWeb** [FortAwesome/vue-fontawesome#129]
I have a bit older css / scss files in are defined some hardcoded icons in css code.
If there a solution to bring this defined font awesome 4 icons as font awesome 5 icons back to state?

Thans a lot

**Comment by robmadole** [comment]
@altraWeb I'm not 100% sure what you are asking. But you might have a look at [upgrading docs](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)
