### ISSUE TITLE
Typo error: "fortawesome" instead of "fontawesome"

### ISSUE THREAD

**Issue by cosmin2583** [FortAwesome/vue-fontawesome#130]
$ npm i --save @fortawesome/fontawesome-svg-core
$ npm i --save @fortawesome/free-solid-svg-icons
$ npm i --save @fortawesome/vue-fontawesome

This typo is everywhere: on fontawesome.com, github and npmjs

...and because of this you can't install the correct package

**Comment by robmadole** [comment]
Hey @cosmin2583.  `@fortawesome` (with an "r") is the organization. That is the correct scope.
