### ISSUE TITLE
Checkbox with checkmark mask

### ISSUE THREAD

**Issue by molerat619** [FortAwesome/vue-fontawesome#132]
I would like to allow the user to tick the checkbox (which is just a square-icon) and then show a checkmark in it. 

Unchecked:
![image](https://user-images.githubusercontent.com/3458576/44785678-0313bc00-ab92-11e8-9eea-5696cc15be1a.png)

The way it looks now is this:
![image](https://user-images.githubusercontent.com/3458576/44785750-40784980-ab92-11e8-85ab-a22a9274881c.png)

Here's my code (I will add the mask only if certain conditions are fulfilled, so this is just a simple example):
```
<fa icon="['far', 'square']" mask="check" fixed-width size="2x"></fa>
```

Also: Is it possible to give the checkmark a different color than the square?

**Comment by robmadole** [comment]
@molerat619 take a look at the ["Layers" feature](https://fontawesome.com/how-to-use/on-the-web/styling/layering) instead. I think that will work better for you.

```
<span class="fa-layers fa-fw">
  <i class="far fa-square"></i>
  <i class="fas fa-check" data-fa-transform="shrink-7"></i>
</span>
```

**Comment by molerat619** [comment]
Cool, that worked, thanks!

![image](https://user-images.githubusercontent.com/3458576/44793666-13826180-aba7-11e8-9713-665a084844b5.png)
