### ISSUE TITLE
Wrapper component not working

### ISSUE THREAD

**Issue by gmask** [FortAwesome/vue-fontawesome#133]
Hi, I'm trying to create a wrapper component as mentioned in #18 in order to get around the limitation of not being able to define a default `prefix` value, but it is not working. Here it is:

```
<template functional>
    <font-awesome-icon
            :icon="['far', icon]"
    ></font-awesome-icon>
</template>

<script>
    import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

    export default {
        components: {
            FontAwesomeIcon
        },

        props: {
            icon: {
                type: String,
                default: ''
            }
        },
    }
</script>
```
It builds fine, but I am getting this error in console:
```
[Vue warn]: Unknown custom element: <font-awesome-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Anonymous>)
```

I am registering my wrapper in my main `app.js` file like this:
```
// Font Awesome
import {library} from '@fortawesome/fontawesome-svg-core'
import {far} from '@fortawesome/pro-regular-svg-icons';

library.add(far);

Vue.component('fa-icon', require('./components/FontAwesome'));
```

What am I doing wrong?

**Comment by robmadole** [comment]
Try `import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'`

**Comment by gmask** [comment]
Still doesn't work trying this:
```
<template functional>
    <font-awesome-icon
            :icon="['far', props.icon]"
    ></font-awesome-icon>
</template>

<script>
    import {library} from '@fortawesome/fontawesome-svg-core';
    import {far} from '@fortawesome/pro-regular-svg-icons';

    library.add(far);

    import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'

    export default {
        components: {
            FontAwesomeIcon
        },
    }
</script>
```

Seems to be an issue with the `functional` tag but if I remove it then I have to manually assign all the props.

**Comment by robmadole** [comment]
Oh yep! Missed that the first time. If you are making a functional `<template>` it's not going to have an instance. So you can't use `components` with it. You can register the component using `Vue.component` instead elsewhere in your app.

**Comment by gmask** [comment]
Ah I see... so this works now:

*app.js*
```
import {library} from '@fortawesome/fontawesome-svg-core';
import {far} from '@fortawesome/pro-regular-svg-icons';

library.add(far);

import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';

Vue.component('font-awesome-icon', FontAwesomeIcon);
Vue.component('fa-icon', require('./components/FontAwesome'));
```

*./components/FontAwesome.vue*
```
<template functional>
    <font-awesome-icon
            :icon="['far', props.icon]"
    ></font-awesome-icon>
</template>
```

I don't like having to register the component twice, but if that's what I gotta do to override the default prefix then I guess it'll have to stay.

Thanks.

**Comment by gmask** [comment]
Actually it looks like I still have to manually specify all the props anyway? `<fa-icon icon="users-cog" fixed-width></fa-icon>`, the `fixed-width` tag does nothing.
