### ISSUE TITLE
[Proposal] UMD version

### ISSUE THREAD

**Issue by olegvakulenko** [FortAwesome/vue-fontawesome#134]
Hi!

Is it possible to make UMD version and use this lib without NPM?

Thanks!

**Comment by olegvakulenko** [comment]
Sorry, but I can't find generated 0.1.1 version on `unpkg.com` like other libs.

https://unpkg.com/vue-fontawesome/

Vue:
https://unpkg.com/vue@2.5.17/

Quasar:
https://unpkg.com/quasar-framework@0.17.12/dist/umd/

Is it possible to make UMD version in this way?

**Comment by olegvakulenko** [comment]
@robmadole 

I'm not sure that I exactly understand your answer.
Service like `unpkg.com` offer possibility to use JS libs without having NPM.
I agree with you, that I can generate for myself UMD version, but I usually (and I think not only myself) don't use NPM, so I have trouble with such tool.
Unfortunately I don't know how `unpkg.com` work, but I think they import data from `npmjs.com`.

1. Is it possible to have possibility to simply download UMD version?
2. Is it possible to add example of usage UMD version in documentation?

Thanks!

**Comment by robmadole** [comment]
@olegvakulenko so we have a UMD version in our NPM package. What I was saying is that I don't know how to make `unpkg.com` recognize that and make our lib available.

**Comment by olegvakulenko** [comment]
I'm embarrassed to bother you, but maybe this link help:

https://medium.com/@kelin2025/so-you-wanna-use-es6-modules-714f48b3a953

**Comment by olegvakulenko** [comment]
https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600

> For example the unpkg field. If you publish your lib on npm it will be available over unpkg. It's a CDN so people can pull your scripts into their scripts without installing them over npm.
> 
> https://unpkg.com/package@version/file
> In the unpkg field you can define the default file, which get served if someone includes https://unpkg.com/package.
> 
> Most of the time, it is a good practice to define the minified version of your lib there.
> 
> "unpkg": "dist/my-awesome-lib.min.js",
>

**Comment by robmadole** [comment]
You are missing the scope identifier. https://unpkg.com/@fortawesome/vue-fontawesome
