### ISSUE TITLE
icons aren't shown in vue cli 3 web component

### ISSUE THREAD

**Issue by hardjob** [FortAwesome/vue-fontawesome#139]
i want to use font awesome icons in my web component.
using this  https://github.com/vuejs/vue-web-component-wrapper  with vue-cli-3
it works in dev mode with "vue-cli-service serve"
but when building with "vue-cli-service build --target wc --name app 'src/app.vue'" the icons aren't shown

**Comment by jgribonvald** [comment]
I'm getting the same problem, icons aren't shown and into the shadow dom the svg tag is replaced by `<!---->`
here is a jsfiddle : https://jsfiddle.net/jgribonvald/wL8h0fjt/

**Comment by jgribonvald** [comment]
@hardjob : do you have an example on how you solved that ?

**Comment by robmadole** [comment]
@hardjob is this resolved then?

**Comment by jgribonvald** [comment]
at least when using svg icons there isn't problems

**Comment by hardjob** [comment]
@jgribonvald check that http://robdodson.me/at-font-face-doesnt-work-in-shadow-dom/

**Comment by jgribonvald** [comment]
Watch on these components: https://github.com/uPortal-contrib/uPortal-web-components/tree/master/%40uportal/esco-content-menu/src/components

Like the actionButton, the header button, etc.
