### ISSUE TITLE
dom.watch doesn't play well with inner comments

### ISSUE THREAD

**Issue by MarienMonnier** [FortAwesome/vue-fontawesome#140]
Hi,

I'm having an issue with the dom.watch() method that adds a comment around the `<i class="far fa-calendar-alt"></i>`, but if the `<i>` has already a comment inside (generated by a subcomponent of Vue), it displays "-->".
I made a repo here: https://codesandbox.io/s/4wvx7742n7

For your information, I'm using [vuejs-datepicker](https://github.com/charliekassel/vuejs-datepicker) that behaves like this (a `<i>` with a custom class and possibly an icon content).

Thank you,

**Comment by MarienMonnier** [comment]
@robmadole Thank you but I can't replace the `<i>` with a `<font-awesome-icon />` component. I'm using the vuejs-datepicker component that just allows me to specify classes. Here are the sources: https://github.com/charliekassel/vuejs-datepicker/blob/master/src/components/DateInput.vue#L6
And I assume this component doesn't want a dependency to FontAwesome.

> You were using `dom.watch()` with Vue which is never a good idea.

I'm wondering why this isn't a good idea? When I have components that only allows me to specify classes, I don't see how else to do this?

**Comment by robmadole** [comment]
> I'm wondering why this isn't a good idea? When I have components that only allows me to specify classes, I don't see how else to do this?

The way that `dom.watch()` works is to establish a MutationObserver that does the replacement of `<i>` tags with `<svg>`. This breaks Vue's ability to use a virtual DOM. For this reason we created the `vue-fontawesome` project (so it works nicely with Vue.) In fact, we use it on fontawesome.com (which is a Vue app).

> Thank you but I can't replace the <i> with a <font-awesome-icon /> component

Ah, this wasn't clear with your first example. You'll probably be better off using Web fonts with CSS (the classic version of Font Awesome) and forego this `vue-fontawesome` component.

**Comment by jasonlundien** [comment]
I am going to go ahead and close this issue.  If you feel that it needs to be reopened just let us know.
