### ISSUE TITLE
Multi-Part Icon Name Example

### ISSUE THREAD

**Issue by vermiceli** [FortAwesome/vue-fontawesome#142]
I wanted to use `align-left` as an icon, but it took me a long time to figure out that I needed to use `align-left` instead of `alignLeft`.  Could the docs be updated to have an example with a multi-part name?

```
import { faAlignLeft } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add(faHome, faAlignLeft);`
...
<font-awesome-icon icon="align-left"/> <!-- NOT alignLeft -->
```

**Comment by robmadole** [comment]
Added this to the README
