### ISSUE TITLE
Easier way to use classic icons sets

### ISSUE THREAD

**Issue by jacqueslelezard** [FortAwesome/vue-fontawesome#151]
I'm really lost with all the configuration of the doc, is their an easy way to implement font-awesome with Vue? I'm ok if the solution isn't optimized since it's only for prototyping. For now it seems that you have to manually import each icon you want to use, is it right or is there another way? Thanks

**Comment by RMFogarty** [comment]
You don't have to manually import each icon. If you read through the description of this package you will see the code to create a vue plugin to load each library similar to this:

```
import Vue from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/pro-regular-svg-icons'
import { fas } from '@fortawesome/pro-solid-svg-icons'

library.add(far);
library.add(fas);

Vue.component('fa-icon', FontAwesomeIcon)
```

**Comment by RMFogarty** [comment]
You should be indicating the icon type like this:  <fa-icon :icon="['fab', 'twitter']" />

**Comment by jacqueslelezard** [comment]
Err I think you sent the message before finishing ;)

**Comment by jacqueslelezard** [comment]
I guess you wanted to write this: `<fa-icon :icon="['fab', 'twitter']" />` seems to work for me !
