### ISSUE TITLE
How to Achieve Fixed Width Icons

### ISSUE THREAD

**Issue by kaisanjay** [FortAwesome/vue-fontawesome#152]
![fixedwidth](https://user-images.githubusercontent.com/16288226/48715697-97466a00-ec3b-11e8-8ee7-c5e4c72cb016.PNG)
 I want this kind of behavior in component-based items.

```
<div style="font-size: 2rem;">
  <div><i class="fas fa-home fa-fw" style="background:MistyRose"></i> Home</div>
  <div><i class="fas fa-info fa-fw" style="background:MistyRose"></i> Info</div>
  <div><i class="fas fa-book fa-fw" style="background:MistyRose"></i> Library</div>
  <div><i class="fas fa-pencil-alt fa-fw" style="background:MistyRose"></i> Applications</div>
  <div><i class="fas fa-cog fa-fw" style="background:MistyRose"></i> Settings</div>
</div>
```

**Comment by ergonomicus** [comment]
@kaisanjay Take a look at [https://github.com/FortAwesome/vue-fontawesome#basic](url) , you have to add fixed-width 'attribute'.

**Comment by kaisanjay** [comment]
> @kaisanjay Take a look at [https://github.com/FortAwesome/vue-fontawesome#basic](url) , you have to add fixed-width 'attribute'.

**Comment by kaisanjay** [comment]
> @kaisanjay Take a look at [https://github.com/FortAwesome/vue-fontawesome#basic](url) , you have to add fixed-width 'attribute'.

I found it
<font-awesome-icon icon="spinner" fixed-width />
