### ISSUE TITLE
Feature: aliased icon names

### ISSUE THREAD

**Issue by robjbrain** [FortAwesome/vue-fontawesome#153]
It would be good to be able to alias icon names.

For instance if you always use "fas fa-comments" for a forum topic, you could just use:

    <font-awesome-icon icon="forum-topic" />

And have it automatically translate into "comments"

**Comment by robmadole** [comment]
@robjbrain this should be pretty trivial to implement yourself. To reduce confusion we are not going to introduce the concept of aliases in the core library or this official component. That brings along some extra complexity that we are really trying to push back against.
