### ISSUE TITLE
Icon volume-mute not found

### ISSUE THREAD

**Issue by nginex** [FortAwesome/vue-fontawesome#156]
I get error when I use volume-mute

`<font-awesome-icon icon="volume-mute" />`

**Could not find one or more icon(s) {prefix: "fas", iconName: "volume-mute"}** 

Others icons work good. It seems volume-mute is not defined.

<img width="417" alt="screenshot 2018-11-28 15 04 23" src="https://user-images.githubusercontent.com/5188136/49153663-077d7b80-f31f-11e8-9dc6-2a976adf2778.png">

**Comment by robmadole** [comment]
@nginex please check the version you are using. The `volume-mute` was added in 5.3.0.

**Comment by nginex** [comment]
Thanks for answering.

I use 5.3.1 version and there is no faVolumeMute icon.

My package-lock.json looks this

```
"@fortawesome/free-solid-svg-icons": {
  "version": "5.3.1",
  "resolved": "https://registry.npmjs.org/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.3.1.tgz",
  "integrity": "sha512-NkiLBFoiHtJ89cPJdM+W6cLvTVKkLh3j9t3MxkXyip0ncdD3lhCunSuzvFcrTHWeETEyoClGd8ZIWrr3HFZ3BA==",
  "requires": {
    "@fortawesome/fontawesome-common-types": "^0.2.4"
  }
}
```

You can check source files [here](https://registry.npmjs.org/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.3.1.tgz)

**Comment by robmadole** [comment]
Try 5.4.0 or newer. It wasn't added to the free version of Font Awesome until then.
