### ISSUE TITLE
Use of "symbol" prop.

### ISSUE THREAD

**Issue by Tcheikovski** [FortAwesome/vue-fontawesome#160]
Hello and thanks for your contributions.
I just discovered the "symbol" feature in FontAwesome a few days ago, but I cannot find any documentation about how to use it in vue-fontawesome... When applying the symbol prop to my fa component, it just becomes a display-none svg tag. I don't understand: does the prop has to be applied on every instance of the symbol, or just on the reference? How do I use the reference ?
It would be very nice if you could explain this a little bit more precisely in the documentation.
Thank you !

**Comment by kawazoe** [comment]
I also think the doc could be clearer about how to use symbols, especially for unnamed symbols.

For now, I use named symbols that I reference with svg myself:

```html
<!-- declaration -->
<font-awesome-icon :icon="['far', 'smile']" symbol="far-smile" />

<!-- usage -->
<svg><use xlink:href="#far-smile"></use></svg>
```

Though, I cannot get class-based properties to work correctly.... For instance, `fa-5x` won't do anything, no matter if I use the `size="5x"` property on the component or the class directly on the svg tag.

**Comment by securit** [comment]
I've been playing with this a bit, you can get the size by adding it to the <svg>.
As a complete example...
```vuejs
<v-app>
        <!-- Define the symbols, these are invisible on the page -->
        <font-awesome-icon :icon="['far','brain']" fixed-width symbol="brain" />
```

```vuejs
<v-tooltip bottom>
    <template v-slot:activator="{ on }">
        <span v-on="on" @click="hitTheBrain(props.item)" class="mr-2 mb-1" color="grey" small>
            <svg class="icon text-blue-500 fa-fw fa-lg">
                <use xlink:href="#brain" />
            </svg>
        </span>
    </template>
    <span>Hit the brain</span>
</v-tooltip>
``` 

```vuejs
<script>
    import Vue from 'vue';
    import Vuetify from 'vuetify';
    import 'vuetify/dist/vuetify.min.css';
    import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome';
    import {library} from '@fortawesome/fontawesome-svg-core';
    import {faBrain} from '@fortawesome/pro-regular-svg-icons/faBrain';
    library.add(faBrain);
    Vue.component('font-awesome-icon', FontAwesomeIcon);
    Vue.use(Vuetify);
```

**Comment by Tcheikovski** [comment]
Thank you both ! Very helpful :)
