### ISSUE TITLE
Removed pro-*-svg-icons packages: how to use new fontawesome-pro?

### ISSUE THREAD

**Issue by EPinci** [FortAwesome/vue-fontawesome#162]
Hello,

the pro-*-svg-icons packages mentioned in the main instructions are no longer existing.
Looks like they have been replaced with the new fontawesome-pro.

I used this code to load all icons (I know, not smart, it's just starting things up before trimming):
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/pro-solid-svg-icons'
import { far } from '@fortawesome/pro-regular-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(fas, far, fal, fab)

export {
  FontAwesomeIcon
}
```

How do I do the same with the new package?

Thank you!

**Comment by robmadole** [comment]
@EPinci these packages still exist. Are you having trouble installing them? Are you a Pro subscriber?

**Comment by EPinci** [comment]
Bummer, indeed they do! Must have been some issue with my npm.
I can pull them now and all works.
I'm closing this - thank you for getting back to me - if you can, just delete this issue to avoid confusing other users.

Thank you!

**Comment by robmadole** [comment]
No worries!
