### ISSUE TITLE
SVG issues with Vue

### ISSUE THREAD

**Issue by Extarys** [FortAwesome/vue-fontawesome#166]
There is many bugs with FontAwesome on Vue using SVG.

https://github.com/vuetifyjs/vuetify/issues/3505
There is handful of issues linked in this issue.

I encountered:
- Icons in a v-if are not removed when the condition is change to false.
- Vuetify icon callback are impossible

Using CSS add a huge amount of bytes to the package and therefor the team should put more effort in making SVG works properly with Vue to encourage tree shaking and reducing the size and memory footprint of a webpage.

I do understand why this may be hard to do, I want to make sure the team knows this and are working on it.

HEre's something to help you.. :duck: :smile:

**Comment by robmadole** [comment]
Using this project (`@fortawesome/vue-fontawesome`) is the best way use Font Awesome with Vue. If you have a specific bug you can file it here using the proper format and providing a reproducible example.

Tree-shaking, correct SVG support, and reduced file size is exactly what this project does.

Please file another issue if you have a bug.
