### ISSUE TITLE
Icon lock not found

### ISSUE THREAD

**Issue by willvin313** [FortAwesome/vue-fontawesome#167]
i get error when i do this 

> Could not find one or more icon(s) {prefix: "fas", iconName: "lock"}

when i do this `<font-awesome-icon icon="lock" />`.
But `<font-awesome-icon icon="coffee" />` and some other icons works.

**Comment by Alvai** [comment]
Hi,

Yeah some icons don't work

I'm trying to get this one : https://fontawesome.com/icons/heart?style=regular
but `far fa-heart` doesn't work

``` <FontAwesomeIcon :icon="['far', 'heart']"></FontAwesomeIcon>```

![image](https://user-images.githubusercontent.com/32277602/51914236-a6365f00-23d8-11e9-852f-a613e048be31.png)

but this is working : 


``` <FontAwesomeIcon :icon="['fas', 'heart']"></FontAwesomeIcon>```

![image](https://user-images.githubusercontent.com/32277602/51914293-d0881c80-23d8-11e9-98ac-7459e99cc70b.png)


How can we fix this ?

**Comment by dudedigital** [comment]
Did you install the regular icons via NPM and import them?

`$ npm i --save @fortawesome/free-regular-svg-icons`

In your JavaScript:

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faHeart } from '@fortawesome/free-regular-svg-icons';
library.add(faHeart);
```

**Comment by XingGuan** [comment]
> 您是否通过NPM安装常规图标并导入它们？
> 
> `$ npm i --save @fortawesome/free-regular-svg-icons`
> 
> 在您的JavaScript中：
> 
> ```
> import { library } from '@fortawesome/fontawesome-svg-core';
> import { faHeart } from '@fortawesome/free-regular-svg-icons';
> library.add(faHeart);
> ```


Hello,
Yes, I quoted the above files, but my lock still can't display

**Comment by XingGuan** [comment]
> Hi,
> 
> Yeah some icons don't work
> 
> I'm trying to get this one : https://fontawesome.com/icons/heart?style=regular
> but `far fa-heart` doesn't work
> 
> ` <FontAwesomeIcon :icon="['far', 'heart']"></FontAwesomeIcon>`
> 
> ![image](https://user-images.githubusercontent.com/32277602/51914236-a6365f00-23d8-11e9-852f-a613e048be31.png)
> 
> but this is working :
> 
> ` <FontAwesomeIcon :icon="['fas', 'heart']"></FontAwesomeIcon>`
> 
> ![image](https://user-images.githubusercontent.com/32277602/51914293-d0881c80-23d8-11e9-98ac-7459e99cc70b.png)
> 
> How can we fix this ?

Hello:
I also encountered the same problem, how do you solve it?

**Comment by robmadole** [comment]
Please provide a reproducible example for us to take a look at using codesandbox.io or something similar. I'll reopen this if you do.

**Comment by connecteev** [comment]
Ditto, same issue here @robmadole - "Regular" fontawesome icons dont work...though the solid and brand icons seem to work fine

```
    [
      "nuxt-fontawesome",
      {
        imports: [
          {
            set: "@fortawesome/free-solid-svg-icons",
            icons: ["fas"]
          },
          {
            set: "@fortawesome/free-brands-svg-icons",
            icons: ["fab"]
          },
          {
            set: "@fortawesome/fontawesome-svg-core",
            icons: ["far"]
          }
        ]
      }
    ]


```

This is the error i get in my console:
```
 WARN  in ./.nuxt/templates.plugin.7921e11b.js                                                                                                                                    friendly-errors 00:10:05

"export 'far' (imported as 'fortawesomefontawesomesvgcore_far') was not found in '@fortawesome/fontawesome-svg-core'                                                              friendly-errors 00:10:05
                                          
```

And this does not work
```
          <font-awesome-icon :icon="['far', 'heart']" />
```

**Comment by robmadole** [comment]
@connecteev provide a reproducible example with something like codesandbox.io and we'll be happy to take a look (we need more than just a few code snippets to reproduce this)

**Comment by connecteev** [comment]
Here's the fix
```
b/nuxt.config.js
index 22576b6..a17ced3 100644
--- a/nuxt.config.js
+++ b/nuxt.config.js
@@ -80,6 +80,10 @@ export default {
       "nuxt-fontawesome",
       {
         imports: [
+          {
+            set: "@fortawesome/free-regular-svg-icons",
+            icons: ["far"]
+          },
           {
             set: "@fortawesome/free-solid-svg-icons",
             icons: ["fas"]
@@ -87,7 +91,12 @@ export default {
           {
             set: "@fortawesome/free-brands-svg-icons",
             icons: ["fab"]
-          }
+          },
         ]
       }
     ]
```

```
diff --git a/package.json b/package.json
index b6aac24..ce8c3f4 100644
--- a/package.json
+++ b/package.json
@@ -13,6 +13,7 @@
   "dependencies": {
     "@fortawesome/fontawesome-svg-core": "^1.2.25",
     "@fortawesome/free-brands-svg-icons": "^5.11.2",
+    "@fortawesome/free-regular-svg-icons": "^5.11.2",
     "@fortawesome/free-solid-svg-icons": "^5.11.2",
     "@fortawesome/vue-fontawesome": "^0.1.7",
     "@nuxtjs/axios": "^5.6.0",
@@ -29,6 +30,7 @@
     "vue-plyr": "^5.1.3"
   },
   "devDependencies": {
+    "@fortawesome/fontawesome-free": "^5.11.2",
     "eslint-plugin-nuxt": "^0.4.3",
     "eslint-plugin-prettier": "^3.1.1",
     "node-sass": "^4.12.0",
```

**Comment by AlexSimpler** [comment]
@willvin313 What I did is include the font awesome stylesheet in my app.vue file and then used it on my components like this `
<template>
   <html>
   <head>
   	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
   </head>
	  <div id="app">
	    <router-view></router-view>
	  </div>
  </html>
</template>`
