### ISSUE TITLE
How to swap icons on hover?

### ISSUE THREAD

**Issue by jongio** [FortAwesome/vue-fontawesome#168]
I could not figure out how to swap the icon on hover.  I am using SASS

This does not switch the icon, but padding is updated.

```
.fa-circle:hover {
  @extend .fa-check-circle !optional;
  padding: 5px;
}
```

Thoughts?
Jon

**Comment by dudedigital** [comment]
Once approach is to use the `myIcon` icon prop to switch them on hover (within a Vue component).

```
<template>
    <div>
        <font-awesome-icon :icon="myIcon" @mouseover="myIcon = ['far', 'check-square']" />
    </div>
</template>

<script>
    export default {
        data() {
            return {
                myIcon: ['far', 'square'],
            };
        }
    }
</script>
```

**Comment by jongio** [comment]
Thanks, I'll give that a shot. Do you know if there's a way to do with just SASS?

**Comment by UltraCakeBakery** [comment]
> Thanks, I'll give that a shot. Do you know if there's a way to do with just SASS?

Maybe through the use of pseudo elements. Make a empty div and set the :before to check-square and :after to square and display: hide, block them when you need to.

**Comment by robmadole** [comment]
@jongio this project is focused on using SVG where the Sass version of Font Awesome uses web fonts. You can post on Stackoverflow.com or https://github.com/FortAwesome/Font-Awesome.
