### ISSUE TITLE
Icon Not Found

### ISSUE THREAD

**Issue by launchriot** [FortAwesome/vue-fontawesome#17]
Hi,
I'm using this component like so:
`<font-awesome-icon :icon="tab.icon" pulse />`
but I'm hitting this error:
`Check not find one or more icon(s) {prefix: "fas", iconName: "spinner"} {}`

I assume "spinner" is a valid name, so I'm a bit confused.

In my main.js I have the following:
```
import fontawesome from '@fortawesome/fontawesome'
Vue.use(fontawesome)
```
and in an index.js, where I register all my components I have

```
// Library
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

  install (Vue) {
    Vue.component(FontAwesomeIcon.name, FontAwesomeIcon)
  }
```
I guess I'm missing something. I'm using webpack, btw.

**Comment by launchriot** [comment]
Never mind, I understand that you must import libraries and you must install those libraries in the first place.

For example: `npm install --save @fortawesome/fontawesome-free-solid`

How can I install the Pro version that I own? The npm link on the pro demo is a  github 404.

**Comment by robmadole** [comment]
@launchriot we'll be releasing documentation for installing Pro packages next week, just hang tight!

**Comment by robmadole** [comment]
@launchriot we've got docs up now for this. just let me know if this is still a problem for you.

**Comment by launchriot** [comment]
Where can I find the docs for this? Thanks.
