### ISSUE TITLE
No known component for element svg

### ISSUE THREAD

**Issue by realtebo** [FortAwesome/vue-fontawesome#176]
I just installed your package and added to my nativescript-vue app

app.js (the main file that creates app)

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add(faUserSecret);

Vue.component('font-awesome-icon', FontAwesomeIcon);
```

In a component vue file (a page)

```
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

export default {
    components: {
        FontAwesomeIcon
    },
```

And the using ...

```
<font-awesome-icon icon="user-secret" ></font-awesome-icon>
```

I got this error:

`JS ERROR TypeError: No known component for element svg.`

If I remove just the tag <FontAwesomeIcon> from my page file, the error disappear. 

This happens to me running on a Mac

`tns run ios --bundle
`
I have still not tried if the same happens on windows, and/or against android

I tried also a different syntax (without success)

`<font-awesome-icon :icon="['fas','user-secret']" ></font-awesome-icon>
`
What can I do to fix?

**Comment by blairacuda** [comment]
possible there's a conflict with adding the component in main and also in your vue file?  

if you've got this in your main
`Vue.component('font-awesome-icon', FontAwesomeIcon);`
 you shouldn't also need to import it into your vue file. 

have you tried removing the import from your vue file?

**Comment by robmadole** [comment]
@realtebo it sounds like you are trying to build an iOS app? Is that correct?

If so then this component hasn't been tested or designed for that.

**Comment by realtebo** [comment]
> @realtebo it sounds like you are trying to build an iOS app? Is that correct?
> 
> If so then this component hasn't been tested or designed for that.

:( Thanks
