### ISSUE TITLE
WebStorm IDE : "Cannot resolve symbol 'FontAwesomeIcon'"

### ISSUE THREAD

**Issue by ByScripts** [FortAwesome/vue-fontawesome#177]
**Describe the bug**

When importing `FontAwesomeIcon` component, WebStorm underlines the import saying `Cannot resolve symbol 'FontAwesomeIcon'`. This causes problem for props completion.

```
import Vue from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
         ^^^^^^^^^^^^^^^
```

The app works correctly, but WebStorm is unable to show any completion for props defined by this component (`icon`, `size`, `fixedWidth`, ...).

I'm willing to accept that this is a WebStorm issue, but it's the only component that causes me such a problem, so...

**Reproducible test case**

Just import and register the component in WebStorm/PhpStorm then use it in a template.

```
<!-- App.vue -->

<template>
  <FontAwesomeIcon [ctrl+space here]
</tempalte>

<script>
  import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

  export default {
    name: "App",
    components: { FontAwesomeIcon }
  }
</script>
```

**Expected behavior**

Typing `<FontAwesomeIcon ` should trigger props autocompletion for FontAwesomeIcon component, but only show completion for standard Vue props (`v-if`, `v-for`...) and HTML attributes.

**Desktop (please complete the following information):**
 - macOS 10.14.5
 - PhpStorm 2019.1.2

**Comment by btaens** [comment]
This is due to index.d.ts declaring the node namespace as a module.
https://github.com/FortAwesome/vue-fontawesome/blob/346ea76fa528a051d28badb3918791e4f7c51eeb/index.d.ts#L1-L10

If you remove the `declare` line (and brackets) it works perfectly.
Is there any reason it's declared like this here, but not in any of the other repos (eg. @fortawesome/free-solid-svg-icons)?

**Comment by yarcowang** [comment]
I do have this error, also.
![simple-modeling-toolkit____Documents_js_simple-modeling-toolkit__-_____src_main_js](https://user-images.githubusercontent.com/1576504/66971705-d340b400-f0c4-11e9-8bff-c3549bfce63f.png)

And when `<font-awesome-icon icon="arrow-left" />` , I got error...
![simple-modeling-toolkit](https://user-images.githubusercontent.com/1576504/66971788-0c792400-f0c5-11e9-8259-abb710d8d434.png)

(Latest `vue create` project, not quite sure what's wrong going on.)

**Comment by robmadole** [comment]
Should be fixed now. Please let us know if it's not.
