### ISSUE TITLE
Explicit prefix is too explicit

### ISSUE THREAD

**Issue by sleewoo** [FortAwesome/vue-fontawesome#18]
Impressed with the work done!

Started migrating and the only issue is tediousness of defining explicit prefixes.
What if passing prefix as prop?

```
<font-awesome-icon far icon="spinner" />
``` 
seems to be a way better than 
```
<font-awesome-icon :icon="['far', 'spinner']" />
```

**Comment by elamperti** [comment]
I agree. It would be even better if we could define a default prefix and/or if it could check the other possible prefixes if it's not found in the default one (e.g. first `fas`, then `far`, then `fal`) and throw a warning.

**Comment by robmadole** [comment]
Thanks, folks, for the feedback!

We've gone back and forth a lot on this. There are a lot of factors involved but the problem with this:

`<font-awesome-icon far icon="spinner" />`

Is that it does not provide a consistent way to specify a `mask`. We wanted these to be specified the same way.

For example:

`<font-awesome-icon :icon="['far', 'spinner']" :mask="['fas', 'circle']" />`

It also makes it difficult to provide an icon definition by binding. In the following case which style should be used (light from the icon definition or regular from the `far` boolean):

```
import faSpinner from `@fortawesome/fontawesome-pro-light`

<font-awesome-icon far :icon="faSpinner" />
```

You also have to bind more than one property if the icon is dynamic:

```
<font-awesome-icon :far="style === 'regular'" :fal="style === 'light'" :icon="icon" />
```

@elamperti a default prefix might be a great idea. I could see that being something set on the `fontawesome.library` object. I'll add that to our list.

**Comment by rdubbeldam86** [comment]
For now I have just created a custom wrapper component that uses the vue-fontawesome component. 

fa.vue:
`<template>
    <font-awesome-icon
    class="fa-icon"
    :border="border"
    :fixedWidth="fixedWidth"
    :flip="flip"
    :icon="['far', icon]"
    :listItem="listItem"
    :mask="mask"
    :pull="pull"
    :pulse="pulse"
    :rotation="rotate"
    :size="size"
    :spin="spin"
    :symbol="symbol"
    :transform="transform"/>
</template>

<script>
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

export default {
  name: 'fa',
  props: {
    border: { type: Boolean, default: false },
    fixedWidth: { type: Boolean, default: false },
    flip: { type: String, default: null, validator: value => ['horizontal', 'vertical', 'both'].indexOf(value) > -1 },
    icon: { type: String, default: null },
    listItem: { type: Boolean, default: false },
    mask: { type: [Object, Array, String], default: null },
    pull: { type: String, default: null, validator: value => ['right', 'left'].indexOf(value) > -1 },
    pulse: { type: Boolean, default: false },
    rotate: { type: Number, default: null, validator: value => [90, 180, 270].indexOf(value) > -1 },
    size: { type: String, default: null, validator: value => ['lg', 'xs', 'sm', '1x', '2x', '3x', '4x', '5x', '6x', '7x', '8x', '9x', '10x'].indexOf(value) > -1 },
    spin: { type: Boolean, default: false },
    symbol: { type: [Boolean, String], default: false },
    transform: { type: [String, Object], default: null }
  },
  components: { 
    FontAwesomeIcon 
  }
}
</script>`

**Comment by robmadole** [comment]
Nice! @rdubbeldam86 as an optimization you could make this a functional template.

Check it out:

```
<template functional>
      <font-awesome-icon
       :icon="['far', props.icon]"
       ...
```

**Comment by dflock** [comment]
@rdubbeldam86 Your wrapper component looks great - but I can't figure out how to use it as a global component?
