### ISSUE TITLE
<font-awesome-icon> title property breaks snapshots

### ISSUE THREAD

**Issue by scottdickerson** [FortAwesome/vue-fontawesome#181]
If I add the title property to font-awesome, it dynamically adds an aria-labelledby to the rendered svg.  The problem is this title is dynamically generating an id, so the aria-labelledby always changes, which invalidates my Jest snapshots.

 <font-awesome-icon v-if="showWarning" icon="exclamation-triangle" size="lg" title="my title" :style="{ color: 'red' }" />

Can we please add an id prop to font-awesome-icon that if set, will guarantee that the title element always gets generated with consistent ids.

**Comment by di1606** [comment]
Did you solve it ?

**Comment by johachi** [comment]
This seems to be solvable by mocking `Math.random`: https://github.com/FortAwesome/react-fontawesome/issues/194

**Comment by jasonlundien** [comment]
Closing issue, fixed with PR [Vue 3x - Update for titleId and maskId prop](https://github.com/FortAwesome/vue-fontawesome/pull/455#top) #455
