### ISSUE TITLE
Ability to specify classes to the icon element

### ISSUE THREAD

**Issue by brianhogg** [FortAwesome/vue-fontawesome#182]
**Is your feature request related to a problem? Please describe.**
When using tailwind, there's no way to add `text-grey` (for example) on the `font-awesome-icon` and have it apply. Instead we need to replicate the colors in a scss file, and apply them using CSS instead.

**Describe the solution you'd like**
Ability to specify a class or classes that would be applied to the icon element

**Describe alternatives you've considered**
While `:style="{ color: 'red' }"` works to apply color styling manually, there's no way I can see to have it use the styling from a CSS class. I tried adding it to the `icon` array (which are basically mapped to classes on the `svg` element) but that breaks.

**Comment by mattixittam** [comment]
Just do `<font-awesome-icon :class="'your-class'" />`?

**Comment by brianhogg** [comment]
@mattixittam that does actually work now! For some reason when I was testing previously the class wasn't being applied on the `svg` element. If it's not a dynamically evaluated class this works:

`<font-awesome-icon class="text-grey" />`

vs. `:class="'text-grey'"`

One little snag separate from color comes with classes, ie. `w-8` in tailwind which would normally apply a width of `2rem`. The CSS rule of `.svg-inline--fa.fa-w-16` is more specific so the single class rule is overridden. Fortunately for that case you can [use the size option](https://github.com/FortAwesome/vue-fontawesome#basic), ie.

`<font-awesome-icon class="text-grey" size="2x" />`
