### ISSUE TITLE
Icon rendered as comment

### ISSUE THREAD

**Issue by dhruvkb** [FortAwesome/vue-fontawesome#183]
**Describe the bug**
When rendering a component (from a UMD build of a component library) that internally renders a Font Awesome icon
![image](https://user-images.githubusercontent.com/16580576/59726229-70dac280-924e-11e9-9bd1-97d8af2a0b5a.png)
the DOM output is just a comment `<!-- -->`
![image](https://user-images.githubusercontent.com/16580576/59726197-50ab0380-924e-11e9-90ad-c3b36ea4d935.png)

For context the code for the Header component can be found [here](https://github.com/creativecommons/cc-vocabulary/blob/master/src/patterns/Header/Header.vue). Vue CLI 3 build target lib was used to generate the UMD and to be extra sure the `build.umd.js` file contains the `FontAwesomeIcon` component in there with all the props. 

**Expected behavior**
The icon referenced should appear.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Firefox
 - Version 67.0.2
_I think this will reproduce in any browser._

**Additional context**
I think it might be because `library` from the `fontawesome-svg-core` is not populated with the icons being used but how does one do that when writing in a browser inside the `<script>` tag?

**Comment by dhruvkb** [comment]
Yes the error was that the icon had not been added to the library but the solution was to add it to the library inside the component's `.vue` file and not delegate the job to the parent app utilising the component.

**Comment by Bubka** [comment]
Hi @dhruvkb 

I have the exact same problem but i'm new to vue and i cannot figure out how to fix it.

Could you explain what exactly you add to your .vue file and which part of the vue-fontawesome declaration remains in the app.js file.

Thanks

**Comment by robmadole** [comment]
This could be a [self-closing tag issue](https://github.com/FortAwesome/vue-fontawesome#quick-warning-about-self-closing-tags)
