### ISSUE TITLE
I cant attach the free-brands-svg-icons and the free-regular-svg-icons Libarsy

### ISSUE THREAD

**Issue by murilolivorato** [FortAwesome/vue-fontawesome#190]
Hello Guys I am trying to use icons from those libraries -
```
free-brands-svg-icons
free-regular-svg-icons
```
But it is not working =/ ,
this one it is working -

```
free-solid-svg-icons
```

my code is like this -
```


import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { faFacebook } from '@fortawesome/free-brands-svg-icons'
import { faClock   } from "@fortawesome/free-regular-svg-icons"


library.add(faCoffee);
library.add(faFacebook);
library.add(faClock);
```
in my blade

````
this dont work
 <font-awesome-icon icon="clock" /></font-awesome-icon>
this dont work
 <font-awesome-icon icon="facebook" /></font-awesome-icon>
this works
<font-awesome-icon icon="coffe" /></font-awesome-icon>
````

**Comment by deevannaveed** [comment]
> Hello Guys I am trying to use icons from those libraries -
> 
> ```
> free-brands-svg-icons
> free-regular-svg-icons
> ```
> 
> But it is not working =/ ,
> this one it is working -
> 
> ```
> free-solid-svg-icons
> ```
> 
> my code is like this -
> 
> ```
> 
> 
> import { library } from '@fortawesome/fontawesome-svg-core'
> import { faCoffee } from '@fortawesome/free-solid-svg-icons'
> import { faFacebook } from '@fortawesome/free-brands-svg-icons'
> import { faClock   } from "@fortawesome/free-regular-svg-icons"
> 
> 
> library.add(faCoffee);
> library.add(faFacebook);
> library.add(faClock);
> ```
> 
> in my blade
> 
> ```
> this dont work
>  <font-awesome-icon icon="clock" /></font-awesome-icon>
> this dont work
>  <font-awesome-icon icon="facebook" /></font-awesome-icon>
> this works
> <font-awesome-icon icon="coffe" /></font-awesome-icon>
> ```

You also need to add the following to make it work.
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'
Vue.component('font-awesome-icon' FontAwesomeIcon)

**Comment by murilolivorato** [comment]
thanks @deevannaveed 
👍

**Comment by sammysmart95** [comment]
npm install @fortawesome/react-fontawesome --save
npm install @fortawesome/free-brands-svg-icons --save

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFacebook } from '@fortawesome/free-brands-svg-icons'

application:
<FontAwesomeIcon  icon={faFacebook} size="sm"></FontAwesomeIcon>
