### ISSUE TITLE
Embed icon in svg

### ISSUE THREAD

**Issue by berzley** [FortAwesome/vue-fontawesome#192]
I'm looking to use icons inside of other SVG elements in my vue templates. Ex.

Rough example:
```
<template>
   <svg>
        ...other svg stuff...

        <font-awesome-icon icon="coffee" />

        ...other svg stuff...
    </svg>
</template>
```

The only approach I've found workable right now is to included the FontAwesome font cdn and do something like:
```
<svg>
    <g><text x="0" y="0" class="fa">&#xf0f4;</text></g>
<svg>
...
<style>
svg text.fa {
   font-family: FontAwesome;
}
</style>
```

Other ideas I've come up with are using a `foreignObject` to drop the content in place.

An possible solution may be something like `<font-awesome-icon icon="coffee" svg />` that only generates `<path d="..." />` and leaves it up to the user to transform and scale as needed.

**Comment by robmadole** [comment]
Hey @berzley you might want to use the lower-level API for this. https://fontawesome.com/how-to-use/with-the-api/methods/icon

Or just use the raw data that comes back from the icon when you import them

```javascript
import { faPlus } from '@fortawesome/free-solid-svg-icons'

faPlus.icon[4] // will be the path data suitable for use in d="..."
```

**Comment by berzley** [comment]
@robmadole Thank you for the quick response! This is a great solution and should work wonderfully!
