### ISSUE TITLE
CSS pseudo elements with Webpack and Vue

### ISSUE THREAD

**Issue by guillaumebriday** [FortAwesome/vue-fontawesome#205]
**Is your feature request related to a problem? Please describe.**
The only documentation I found is [here](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#with-svg-js).

I think it's not clear how we should use it with Vue (or React) and a module bundler like Webpack.

**Describe the solution you'd like**
Please consider add a section in the readme to explain how to configure this option with this package.

**Describe alternatives you've considered**
The only workaround I found is to import both SVGs and fonts which is far from ok for load performance.

Thank you in advance!

**Comment by robmadole** [comment]
Hey @guillaumebriday. Pseudo elements are not recommended and we intentionally do not want to support them in any of the SVG component libraries (Vue, React, Ember, Angular, etc). I'm curious why you need them when you are using Vue?

**Comment by guillaumebriday** [comment]
Hey! Thank you for you quick answer.

Most of the time is to override libraries to be honest. But it happens often with the number of Vuejs components librairies.

**Comment by robmadole** [comment]
Gotcha. Yeah if you are using other components and they use pseudo elements or they use web fonts you normally are just better off using web fonts yourself and putting `<i>` tags in your app. We just don't have a good solution for pseudo elements in Vue with Font Awesome.
