### ISSUE TITLE
Prefix defaults to "fas" even when iconName is set to "['fab', 'google']"

### ISSUE THREAD

**Issue by tylermmorton** [FortAwesome/vue-fontawesome#208]
**Describe the bug**
Prefix defaults to `"fas"` even when `iconName` is set to `"['fab', 'google']"`

Error:
```
Could not find one or more icon(s) Object
iconName: "['fab', 'google']"
prefix: "fas"
__proto__: Object Object
```

**Reproducible test case**
```
<font-awesome-icon :icon="`['fab', '${ico}']`" v-for="(ico, index) in getIcons(slotScope.value)" v-bind:key="index"/>
```
where `getIcons()` returns:
```
['google']
```

**Expected behavior**
The icon would be set to `"['fab', 'google']"` with the prefix `fab`

**Desktop (please complete the following information):**
 - Browser chrome
 - Version  
@fortawesome/fontawesome-svg-core@1.2.25
@fortawesome/fontawesome-common-types@0.2.25
@fortawesome/free-brands-svg-icons@^5.11.2

**Additional context**
I have a feeling that using the tilde to specify `['fab', '${ico}']` is the issue, however I have tried with escaped single quotes and run into the same problem. If there is something I'm not seeing here please let me know. Thanks in advance :)

**Comment by robmadole** [comment]
Try `:icon="['fab', ico]"`@tylermmorton

**Comment by tylermmorton** [comment]
That worked! I was definitely overcomplicating it. Thanks :)
