### ISSUE TITLE
Can provide global introduction?

### ISSUE THREAD

**Issue by weihongyu12** [FortAwesome/vue-fontawesome#21]
There is no provision for the introduction of the overall function of the world, similar examples of the code in the component may not be eslint inspection, I suggest the use of ```Vue.use (FontAwesomeIcon)``` this way, to the overall introduction of the icon library

**Comment by robmadole** [comment]
@weihongyu12 the `FontAwesomeIcon` is just a normal component and not a plugin. You really just need to register the component like normal:

```
import Vue from 'vue'
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

Vue.component('font-awesome-icon', FontAwesomeIcon)
```

Or through the `components` property of another component:

```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

export default {
  name: 'MyComponent',

  components: {
    FontAwesomeIcon
  }
}
```

**Comment by weihongyu12** [comment]
@robmadole Yes, I've already done this, but there was an error on the console.

![image](https://user-images.githubusercontent.com/19792747/34022490-8a57d8be-e17a-11e7-9eac-980657a22c66.png)

This question should be the same as #22

**Comment by mathieutu** [comment]
The same for me, and still no answer... :/

**Comment by robmadole** [comment]
You're going to get this error if you haven't added an icon to your library.

```
import faSpinner from '@fortawesome/fontawesome-free-regular/faSpinner'

fontawesome.library.add(faSpinner)
```

**Comment by mathieutu** [comment]
Yeah I've realized that afterwards.  So  we agree that the doc must be updated, and you can't do just like in your previous comment: https://github.com/FortAwesome/vue-fontawesome/issues/21#issuecomment-351754519?
