### ISSUE TITLE
How import Light Style ?

### ISSUE THREAD

**Issue by murilolivorato** [FortAwesome/vue-fontawesome#213]
I can see that this ICON -
https://fontawesome.com/icons/envelope?style=solid
and this one -
https://fontawesome.com/icons/envelope?style=light

Are the same , you can attach this icon like this -
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faEnvelope  } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon, } from '@fortawesome/vue-fontawesome';
library.add(faEnvelope  );
Vue.component('font-awesome-icon', FontAwesomeIcon);

``` 
AND USE LIKE THAT -

```
<font-awesome-icon icon="faEnvelope  "  />
```

THIS WILL DISPLAY LIKE THIS ONE -
https://fontawesome.com/icons/envelope?style=solid

HOW CAN I USE LIGHT OPTION LIKE THIS ONE -
https://fontawesome.com/icons/envelope?style=light

??

**Comment by alphatrust-dev** [comment]
import { faEnvelope  } from '@fortawesome/free-solid-svg-icons';
import { faEnvelope as falEnvelope  } from '@fortawesome/free-light-svg-icons';

library.add(faEnvelope);
library.add(falEnvelope);

**Comment by jasonlundien** [comment]
@murilolivorato ---

Looks like @richcoleman-alphatrust may have helped you out.  I am going to go ahead and close this issue.  If you feel it needs to remain open just let us know.
