### ISSUE TITLE
Could not find one or more icon(s) in VueJS with TypeScript

### ISSUE THREAD

**Issue by SnowNooDLe** [FortAwesome/vue-fontawesome#215]
Hi all,

I am quite new to Vuejs so my explanation may not be accurate or dumb but please understand me :)

So I have followed the instruction and can see it's going but only with one icon from the example but anything else keep saying 'Could not find....'

inside main.ts 
```JavaScript
import { library } from '@fortawesome/fontawesome-svg-core';
import { faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add(faUserSecret)
Vue.component('font-awesome-icon', FontAwesomeIcon);
```

inside my component,
```JavaScript
<font-awesome-icon :icon="['fas', 'envelope-open-text']" />
<font-awesome-icon :icon="['fas', 'user-secret']" />
```
envelope is where I am getting an error.
Based on those link
[Envelope](https://fontawesome.com/icons/envelope-open-text?style=solid)
[User-Secret](https://fontawesome.com/icons/user-secret?style=solid)

For Envelope is
```HTML
<i class="fas fa-envelope-open-text"></i>
```
and User-Secret is
```HTML
<i class="fas fa-user-secret"></i>
```

So I thought I could put 'fas' as a prefix, then put 'envelope-open-text' without fa, just like what 'user-secret' is like.
I am getting an 'user-secret' icon without an issue but everything else is not coming up.

Am I missing something?

**Comment by SnowNooDLe** [comment]
NVM, I just sorted out, just in case if someone else is getting the same issue, here is the solution
in ReadME.md, saying put this inside main.js or main.ts 
```JavaScript
import { library } from '@fortawesome/fontawesome-svg-core';
import { faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
library.add(faUserSecret)
Vue.component('font-awesome-icon', FontAwesomeIcon);
```
You don't really have to this unless you need those for globally,
if you think you will need to use FontAwesome in multiple components, then just keep
```JavaScript
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
Vue.component('font-awesome-icon', FontAwesomeIcon);
``` 
then inside the componenet where you want to use,

```JavaScript
<script lang="ts">
// this is must have
import { library } from '@fortawesome/fontawesome-svg-core';
// import { name of your icon in camelCase } from "@fortawesome/free-solid-svg-icons";
// For example, I want to use fa-enveloper-open-text, then it's faEnvelopeOpenText
import { faEnvelopeOpenText } from "@fortawesome/free-solid-svg-icons";
// Then add it to library
library.add(faEnvelopeOpenText)
</script>

// Finally I can use envelope-open-text like this inside template
<font-awesome-icon :icon="['fas', 'envelope-open-text']" />

```

**Comment by dohyung97022** [comment]
I had the exact same problem with vue 3.2.13

Solved it a different way.

main.ts
```ts
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {library} from "@fortawesome/fontawesome-svg-core";
import {fas} from "@fortawesome/free-solid-svg-icons";

library.add(fas)

createApp(App)
    .use(router)
    .component('font-awesome-icon', FontAwesomeIcon)
    .mount('#app')
```

and added this in the component with no imports.

```html
<font-awesome-icon icon="trash" />
```



The problem was that the font-awesome website keeps giving  
`<font-awesome-icon icon="fa-solid fa-trash" />` this instead.

**Comment by CharithaDhananjaya** [comment]
> I had the exact same problem with vue 3.2.13
> 
> Solved it a different way.
> 
> main.ts
> 
> ```ts
> import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
> import {library} from "@fortawesome/fontawesome-svg-core";
> import {fas} from "@fortawesome/free-solid-svg-icons";
> 
> library.add(fas)
> 
> createApp(App)
>     .use(router)
>     .component('font-awesome-icon', FontAwesomeIcon)
>     .mount('#app')
> ```
> 
> and added this in the component with no imports.
> 
> ```
> <font-awesome-icon icon="trash" />
> ```
> 
> The problem was that the font-awesome website keeps giving `<font-awesome-icon icon="fa-solid fa-trash" />` this instead.

This Works for me. Thanks.

**Comment by rodolfo-santos** [comment]
I'm having the same problem with nuxt 3

**Comment by makiika** [comment]
> I'm having the same problem with nuxt 3

this is how i solved it 
i added the following in my nuxt.config.ts

  build: {
    transpile: [
      "@fortawesome/vue-fontawesome",
      "@fortawesome/fontawesome-svg-core",
      "@fortawesome/pro-solid-svg-icons",
      "@fortawesome/pro-regular-svg-icons",
      "@fortawesome/free-brands-svg-icons",
    ],
  },

**Comment by redwarff** [comment]
> > I'm having the same problem with nuxt 3
> 
> this is how i solved it i added the following in my nuxt.config.ts
> 
> build: { transpile: [ "@fortawesome/vue-fontawesome", "@fortawesome/fontawesome-svg-core", "@fortawesome/pro-solid-svg-icons", "@fortawesome/pro-regular-svg-icons", "@fortawesome/free-brands-svg-icons", ], },

Actually just adding `build: {
    transpile: ['@fortawesome/vue-fontawesome'],
  },`
  solved the issue for me

**Comment by bayasdev** [comment]
> > > I'm having the same problem with nuxt 3
> > 
> > 
> > this is how i solved it i added the following in my nuxt.config.ts
> > build: { transpile: [ "@fortawesome/vue-fontawesome", "@fortawesome/fontawesome-svg-core", "@fortawesome/pro-solid-svg-icons", "@fortawesome/pro-regular-svg-icons", "@fortawesome/free-brands-svg-icons", ], },
> 
> Actually just adding `build: { transpile: ['@fortawesome/vue-fontawesome'], },` solved the issue for me

Thanks, it worked for me 👍

**Comment by alex-eliot** [comment]
> > I'm having the same problem with nuxt 3
> 
> this is how i solved it i added the following in my nuxt.config.ts
> 
> build: { transpile: [ "@fortawesome/vue-fontawesome", "@fortawesome/fontawesome-svg-core", "@fortawesome/pro-solid-svg-icons", "@fortawesome/pro-regular-svg-icons", "@fortawesome/free-brands-svg-icons", ], },

You are blessed. Thank you.

**Comment by wavedeck** [comment]
> > > I'm having the same problem with nuxt 3
> > 
> > 
> > this is how i solved it i added the following in my nuxt.config.ts
> > build: { transpile: [ "@fortawesome/vue-fontawesome", "@fortawesome/fontawesome-svg-core", "@fortawesome/pro-solid-svg-icons", "@fortawesome/pro-regular-svg-icons", "@fortawesome/free-brands-svg-icons", ], },
> 
> Actually just adding `build: { transpile: ['@fortawesome/vue-fontawesome'], },` solved the issue for me

This really should be mentioned in the official  [FontAwesome Docs for Nuxt](https://fontawesome.com/docs/web/use-with/vue/use-with#nuxt)

It's still an issue in 2023 (Nuxt 3.2.3 | vue-fontawesome: 3.0.3)

By adding this line it's also able to SSR the icons which avoids flashing

**Comment by BroFromSpace** [comment]
> > I'm having the same problem with nuxt 3
> 
> this is how i solved it i added the following in my nuxt.config.ts
> 
> build: { transpile: [ "@fortawesome/vue-fontawesome", "@fortawesome/fontawesome-svg-core", "@fortawesome/pro-solid-svg-icons", "@fortawesome/pro-regular-svg-icons", "@fortawesome/free-brands-svg-icons", ], },

Thanks, you saved my day.

And yeah, it's still an issue in September 2023.

**Comment by mskry** [comment]
For those who have long list of icons and are Ok with not rendering some of them: use a placeholder icon "fw" (fa-fw) to avoid exceptions.

**Comment by jeannen** [comment]
Still an issue in November

Would be nice to have a real Nuxt module we can install without having to manually add the plugin and everything

**Comment by luiguild** [comment]
Anyone with this problem on Astro? I cannot import any icon, it keep giving me the same error message:
```
Could not find one or more icon(s) { prefix: 'fas', iconName: 'envelope-open-text' } {}
```

**Comment by renderf0x** [comment]
> Actually just adding `build: { transpile: ['@fortawesome/vue-fontawesome'], },` solved the issue for me

Thank you. This is a straightforward solution that works in Nuxt 3 in 2024 =)

**Comment by diadras** [comment]
Still an issue today.
I have a brand new project and use the icons in a slot in a component. It loads the first time but breaks on refresh.

Adding the line @redwarff mentioned fixes the issue.
