### ISSUE TITLE
Error Using Duotone icons

### ISSUE THREAD

**Issue by Yodablues** [FortAwesome/vue-fontawesome#216]
**Describe the bug**
We are trying to use the duotone icons 'sortUp' and 'sortDown', but our console is throwing errors when it appears to try to render the icon. We are running this in Storybook to build our components.

```
vue.esm.js:6790 Error: <path> attribute d: Expected path command, "…05-4.4-41 17-41z,M24.05 183.05l1…".
```

![image](https://user-images.githubusercontent.com/2636870/73671908-f003f600-4679-11ea-8c4a-35251aecd1ac.png)

It does appear to render the darkened element, but not the lightened svg.
![image](https://user-images.githubusercontent.com/2636870/73672043-2c375680-467a-11ea-8293-8817fc96b0b5.png)

**Reproducible test case**
Include a URL (codepen.io, jsfiddle.net, Git repository, codesandbox.io, stackblitz.com, etc.) that demonstrates the problem.
Component:
```
    <font-awesome-icon
      :icon="['fad', 'sort-down' ]"
    />
```

config.js
```
import { library, dom } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { faShieldCheck } from '@fortawesome/pro-solid-svg-icons';
import { faSortUp, faSortDown } from '@fortawesome/pro-duotone-svg-icons';

library.add(fas,
  faShieldCheck,
  faSortUp,
  faSortDown,
  );
dom.watch();
Vue.component('font-awesome-icon', FontAwesomeIcon);

```

**Comment by robmadole** [comment]
@Yodablues let's start with checking the version of the `@fortawesome/fontawesome-svg-core` library. We introduced duotone in 5.10.0. If you have an older version it won't know how to handle those duotones.

**Comment by Yodablues** [comment]
```
"dependencies": {
    "@fortawesome/fontawesome-pro": "5.11.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.3",
    "@fortawesome/free-brands-svg-icons": "^5.10.2",
    "@fortawesome/free-regular-svg-icons": "^5.3.0",
    "@fortawesome/free-solid-svg-icons": "^5.3.0",
    "@fortawesome/pro-duotone-svg-icons": "^5.12.0",
    "@fortawesome/pro-solid-svg-icons": "5.11.2",
    "@fortawesome/vue-fontawesome": "^0.1.1",
    "bootstrap": "^4.1.1",
    "bootstrap-vue": "^2.0.0-rc.24",
    "core-js": "^2.6.5",
    "lodash": "^4.17.11",
    "vue": "^2.6.10",
    "vue-slider-component": "^3.1.0",
    "vue-the-mask": "^0.11.1"
  },
```


Let me know if I can provide any more info.

**Comment by robmadole** [comment]
@Yodablues try upgrading those dependencies first, they are a tad old.

**Comment by Yodablues** [comment]
Yuuup, updating resolved it. 🤦‍♂ Thanks for the help!

**Comment by robmadole** [comment]
Fantastic. Glad it was an easy fix.
