### ISSUE TITLE
Use library directly on css

### ISSUE THREAD

**Issue by lelibreauquotidien** [FortAwesome/vue-fontawesome#218]
Hello.
I would like to use the library icons in my css with the content property. 
Is it possible ?
Thank you.

**Comment by robmadole** [comment]
No with this component library @lelibreauquotidien. You should look at using the web fonts version with pseudo-elements. You can install `@fortawesome/fontawesome-pro` or `@fortawesome/fontawesome-free`.

**Comment by lelibreauquotidien** [comment]
Thanks, what font-family do i have to use ?

**Comment by robmadole** [comment]
Try the [documentation here](https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements)

**Comment by lelibreauquotidien** [comment]
Thanks !

**Comment by chadwtaylor** [comment]
Followed the documentation as recommended to use the pseudo-element and used `font-family: "Font Awesome 5 Pro"` as outlined (we are a Pro member). I'm getting a square icon.

Previously, I installed the `nuxt-fontawesome` plugin which allows me to use `font-family: "FontAwesome"` without issues. In my new project, I don't have this installed except for this fantastic plugin and need a bit of guidance.

I understand this is outside this plugin's expertise but I am interested in getting insight on how others archived this as this will tremendously help me (and others who stumble across this issue). 

Thanks so much.
