### ISSUE TITLE
Missing the 'pagelines' icon

### ISSUE THREAD

**Issue by become-iron** [FortAwesome/vue-fontawesome#219]
It seems that the  'pagelines' icon (https://fontawesome.com/icons/pagelines?style=brands) is missing in the module, so I can't use it

**Comment by robmadole** [comment]
@become-iron have you installed the `@fortawesome/free-brands-svg-icons` package?

**Comment by become-iron** [comment]
Oops, my bad. I just thought it's weird name for an icon with branch. Thank you!
