### ISSUE TITLE
Icon not working with vue

### ISSUE THREAD

**Issue by Mactaivsh** [FortAwesome/vue-fontawesome#22]
Based on the user guide,  same code, but not working.

``` js
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
export default {
  components: {
    FontAwesomeIcon
  }
}
```

``` html
<button class="btn btn-primary btn-lg btn-block">
    edit
  <font-awesome-icon icon="edit" />
<button>
```

Threw error in chrome console:
` Check not find one or more icon(s) {prefix: "fas", iconName: "edit"} {}`

neither this would work: 

``` html
<button class="btn btn-primary btn-lg btn-block">
    edit
  <font-awesome-icon :icon="['fas', 'edit']" />
<button>
```

Any explanation ? Thanks.

**Comment by Mactaivsh** [comment]
Maybe should I include the `fontawesome-all.js` inside the `<head></head>` ? That seems work. I thought this module would include the core script. If this is true, please notice me and feel free to close this issue. Much obliged.

**Comment by OriginalEXE** [comment]
Check my post here: https://github.com/FortAwesome/vue-fontawesome/issues/14#issuecomment-351474573

Basically, you also need this:

```
import '@fortawesome/fontawesome/styles.css';
import { faEdit } from '@fortawesome/fontawesome-free-solid';

fontawesome.config = {
  autoAddCss: false,
};

fontawesome.library.add(faEdit);
```

and then

**Comment by shaunie2fly** [comment]
Not sure if this is ideal but it works for me :)
```

import fontawesome from '@fortawesome/fontawesome';
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
import falight from '@fortawesome/fontawesome-pro-light';
import fasolid from '@fortawesome/fontawesome-pro-solid';

fontawesome.library.add(falight, fasolid);

 Vue.component(FontAwesomeIcon.name, FontAwesomeIcon);
```

**Comment by robmadole** [comment]
@shaunie2fly what's not ideal?

**Comment by rlam3** [comment]
I'm having a similar issue. But with nuxt js.

Are there specifics that I need to import for nuxt.config.js?

**Comment by robmadole** [comment]
Check this out @rlam3 https://github.com/FortAwesome/vue-fontawesome/issues/14#issuecomment-351474573

**Comment by mikelmi** [comment]
The same issue. Still not working.
https://codesandbox.io/s/62vyyk7qpr

see the console

**Comment by robmadole** [comment]
@mikelmi looks like you referenced `fas` which is the solid style. Can you add that as a dependency and try again?

**Comment by mikelmi** [comment]
@robmadole How can I use regular style? I've imported regular style
import regular from "@fortawesome/fontawesome-free-regular";
fontawesome.library.add(regular);

**Comment by robmadole** [comment]
@mikelmi docs are on the [README.md](https://github.com/FortAwesome/vue-fontawesome/blob/master/README.md)

**Comment by minedun6** [comment]
regular icons are not the same as solid icons.
for example an icon like "users" is available in solid version but not in regular version

**Comment by cielblog** [comment]
First of all, my English is not good so I hope you get the point 🤦‍♂️

To use Snotify inside Vuex's module you can use prototype property:
`Vue.prototype.$snotify.success('Test Test Test')`
It worked with me.

![image](https://user-images.githubusercontent.com/16566503/47967240-6592a800-e06c-11e8-8ef9-97f74375b398.png)

![image](https://user-images.githubusercontent.com/16566503/47967321-10a36180-e06d-11e8-8c0f-9ea0f6b65956.png)

❤✨
