### ISSUE TITLE
FontAwesome free usage pageview limit

### ISSUE THREAD

**Issue by jelazos7** [FortAwesome/vue-fontawesome#220]
I'm reading through the limitations of the font awesome free plan at https://fontawesome.com/plans

When using vue-fontawesome, are our websites still subject to the pageview limit?

**Comment by robmadole** [comment]
Hi @jelazos7. Those limits only apply if you are using one of the services that Font Awesome is paying the bandwidth for. If you are serving it from your own servers there are no page view limits.

**Comment by neeraj395** [comment]
Hi @robmadole what If I'm using FontAwesome kit that means am I using fontawesome bandwidth or not ?

**Comment by vincentwansink** [comment]
> Hi @robmadole what If I'm using FontAwesome kit that means am I using fontawesome bandwidth or not ?

On the home page of font awesome, once you're logged into your account, there is a download button.  Use that to serve the icons from your own server.
