### ISSUE TITLE
FontAwesome Icons are tiny and can't be seen after NuxtJS Build

### ISSUE THREAD

**Issue by rsalunga29** [FortAwesome/vue-fontawesome#221]
**Describe the bug**
Icons are very tiny after a NuxtJS build, but there were of normal size during development.
Dev:
<img width="145" alt="Screen Shot 2020-03-29 at 10 43 00 PM" src="https://user-images.githubusercontent.com/20834464/77851978-b4ffe800-720e-11ea-9dc7-dd8eaa0a07d4.png">

Build:
<img width="248" alt="Screen Shot 2020-03-29 at 10 18 08 PM" src="https://user-images.githubusercontent.com/20834464/77851882-1a9fa480-720e-11ea-8bc8-8bb71cac1b57.png">

**Reproducible test case**
I followed the tutorial as stated [here](https://github.com/FortAwesome/vue-fontawesome#integrating-with-other-tools-and-frameworks). After that, I ran `npm run build` and `npm run start`. This is how I used it on my Vue components
```vue
<div class="navbar flex justify-between items-center z-50">
  <div class="cursor-pointer">
    <img src="~/assets/img/logo_nav.svg">
  </div>

  <div class="text-2xl">
    <a href="https://www.instagram.com/" class="mr-1">
      <font-awesome-icon :icon="['fab', 'instagram']" />
    </a>
    
    <a href="https://www.facebook.com/">
      <font-awesome-icon :icon="['fab', 'facebook']" />
    </a>
  </div>
</div>
``` 

**Expected behavior**
Icons be of same normal size like develop after NuxtJS Build.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

**Comment by robmadole** [comment]
Hi @rsalunga29. You'll have to provide a fully reproducible test case in the form of a GitHub repo, Gist, or something like codesandbox.io. We'll be happy to take a look at it after that.

**Comment by rsalunga29** [comment]
Hi @robmadole, this was actually solved, I'm not really sure what the problem was but when I used the CDN it went fine.
