### ISSUE TITLE
Duotone sortup and sortdown doesnt match fontawesome.com icons

### ISSUE THREAD

**Issue by VenkataJanapareddy** [FortAwesome/vue-fontawesome#222]
I installed duotone icons in our vue app yesterday. 

```$ npm i --save @fortawesome/pro-duotone-svg-icons```

which installed the following version

```"@fortawesome/pro-duotone-svg-icons": "^5.13.0"```

When I import the sort-up and sort-down icons as follows

```
import {
	faSortDown,
	faSortUp,
} from '@fortawesome/pro-duotone-svg-icons'
```

the above icons are not matching what's on the fontawesome website

https://fontawesome.com/icons/sort-up?style=duotone
https://fontawesome.com/icons/sort-down?style=duotone

instead, the solid style icons are returned, which looks like:

https://fontawesome.com/icons/sort-up?style=solid
https://fontawesome.com/icons/sort-down?style=solid

We have font awesome pro subscription.

**Comment by robmadole** [comment]
Hi @VenkataJanapareddy .  Please provide a reproducible test case we can run locally using a GitHub repo, Gist, or something like codesandbox.io. We'll take a look then.
