### ISSUE TITLE
Font Awesome Version Needs Upgrade

### ISSUE THREAD

**Issue by lilnayners** [FortAwesome/vue-fontawesome#228]
I just tried to use the fa-bell-on icon from Font Awesome version 5.12.0, and it appears to be unavailable. Are there plans to upgrade the version being used anytime soon?

**Comment by robmadole** [comment]
Hi @lilnayners. The packages that provide the icons are separate from the Vue component package.

Try upgrading the `@fortawesome/*-svg-icons` packages. (Like `@fortawesome/free-solid-svg-icons`)

**Comment by lilnayners** [comment]
ah ok, cool, thanks!
