### ISSUE TITLE
Could you provide an example of using a brand icon?

### ISSUE THREAD

**Issue by KyleTryon** [FortAwesome/vue-fontawesome#23]
Can someone clarify these two lines a little for me?

```
import brands from '@fortawesome/fontawesome-free-brands'
import { faSpinner } from '@fortawesome/fontawesome-free-solid'
fontawesome.library.add(brands, faSpinner )
```

It looks here I can use the spinner icon but if I try to use facebook instead I get nothing.

`<font-awesome-icon icon="facebook" />`

I'd also like to know the proper way to refer to icons with dashes in their name, such as "calendar-alt" when importing them.

**Comment by robmadole** [comment]
:+1:
