### ISSUE TITLE
Added to clean vue project - error breaks the project

### ISSUE THREAD

**Issue by nalex-macaroni** [FortAwesome/vue-fontawesome#234]
ERROR TypeError: Cannot read property 'fontawesome' of undefined
at module.exports (C:.........\@cheap-glitch\vue-cli-plugin-fontawesome\index.js:30:61)
etc.

**Reproducible test case**
every time
**Expected behavior**
that it won't kill my project

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by robmadole** [comment]
@nalex-macaroni have you filed this with the correct project? I'm seeing `vue-cli-plugin-fontawesome` there in the error.

**Comment by nalex-macaroni** [comment]
I’ve shelved that particular problem for the time-being due to time constraints. I may - or may not - address this again in the future. I’m not a particular fan of the implementation, and may just use the actually-working CSS-only stuff, which works beautifully.



Neil Alexander
Chief Macaroni Geek, Macaroni Kid
| e:neil@macaronikid.com <https://bits.zynbit.com/link?guid=1ee2842f-6513-123b-cff7-411221d1ba91&url=mailto:Joyce@Macaronikid.com> 
| a:PO Box 60871, Potomac, MD 20854

**Comment by jasonlundien** [comment]
Hey @nalex-macaroni ---

I am going to go ahead and close this issue.  If you feel this needs to remain open, just let us know and we can adjust.
