### ISSUE TITLE
Regular and Solid Fonts with the same name , how import  and use both ?

### ISSUE THREAD

**Issue by murilolivorato** [FortAwesome/vue-fontawesome#237]
Hello , I have 2 Font awsome to import  , both have the same name - STAR .

this is the link of regular -
https://fontawesome.com/icons/star?style=regular
and this is the link of the solid -
https://fontawesome.com/icons/star?style=solid

so I import like that 
```
import { library } from '@fortawesome/fontawesome-svg-core';
// IMPORT SOLID
import { faStar } from '@fortawesome/free-solid-svg-icons';

// IMPORT REGULAR
import { faStar } from '@fortawesome/free-regular-svg-icons'

// ADD TO LIBRARY
library.add(faStar);

Vue.component('font-awesome-icon', FontAwesomeIcon);

```

the proble is that I can not use the regular , becose the solid is with the same name . how can I change this ? thanks

**Comment by drafu** [comment]
For proper usage of `library.add`, you need to rename imported icon as such:
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faStar } from '@fortawesome/free-solid-svg-icons';
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons'
```
and then add both to library
```
library.add(faStar, farStar);
```
and use them as documentation states:
```
<fa :icon="['fas', 'star']"/>
<fa :icon="['far', 'star']"/>
```
