### ISSUE TITLE
Classes are not happened to the component

### ISSUE THREAD

**Issue by LeCoupa** [FortAwesome/vue-fontawesome#238]
```html
    <base-icon
      :class="[
        {
          'w-2 h-2': size === 'xs',
          'w-3 h-3': size === 'sm',
          'w-4 h-4': size === 'base',
          'w-5 h-5': size === 'lg',
          'w-6 h-6': size === 'xl'
        }
      ]"
      class="flex-initial mr-3"
      :icon="icon"
    />
```

the width and height classes are not appended to the icon component according to the size. It looks like classes with v-bind do not work. Is there a way to overcome this issue?

**Comment by christhofer** [comment]
I think you don't need array brace there. This is how I usually do.

Try
```
<base-icon
      :class="{
          'w-2 h-2': size === 'xs',
          'w-3 h-3': size === 'sm',
          'w-4 h-4': size === 'base',
          'w-5 h-5': size === 'lg',
          'w-6 h-6': size === 'xl'
      }"
      class="flex-initial mr-3"
      :icon="icon"
/>
```

**Comment by robmadole** [comment]
@LeCoupa can you provide a bit more context? Looks like you have a `size` property you are reading from. And is `base-icon` the `FontAwesomeIcon` component from this project?

If you can provide a reproducible test case that would help a lot.

**Comment by LeCoupa** [comment]
@christhofer's way of doing things solved the issue 👍
