### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@fortawesome%2fvue-fontawesome - Not found

### ISSUE THREAD

**Issue by loic001** [FortAwesome/vue-fontawesome#241]
Hi,

I get this error while doing npm install:

`Not Found - GET https://registry.npmjs.org/@fortawesome%2fvue-fontawesome - Not found`

Thanks for your help!

**Comment by JuanmaCano** [comment]
+1 

same issue here

**Comment by mimimircea** [comment]
+1
same with yarn

`An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/vue-fontawesome: Not found`

**Comment by cbl** [comment]
+ 1

**Comment by mircea-cm** [comment]
a few moments ago started working with yarn, probably works with npm also.

**Comment by loic001** [comment]
Indeed, it works again with npm, thank you ;)

**Comment by loic001** [comment]
FYI, I think something went wrong with npm registry server. I have the same mistake with other packages...
