### ISSUE TITLE
font-awesome-icon tag does not support pug syntax

### ISSUE THREAD

**Issue by benwalsh** [FortAwesome/vue-fontawesome#248]
**Describe the bug**
When using `pug` as a templating language, no "prefix" other than the default `fas` can be used.

**Reproducible test case**
https://github.com/benwalsh/font-awesome-pug

**Expected behavior**
When providing an array to the `:icon` in an HTML template, everything works as expected.

In a pug template, the two elements the array are concatenated into the `iconName`, and the `prefix` remains the default `fas`. Example: `icon="['far', 'star']` should yield a `prefix` of `far` and an `iconName` of `star`, but instead it throws the error `Could not find one or more icon(s) {prefix: "fas", iconName: "far-star"}`

**Desktop (please complete the following information):**
 - This happens at the compilation stage regardless of the browser

**Comment by robmadole** [comment]
Hey @benwalsh.

Looks like you just need to bind the property since it's an array:

```pug
font-awesome-icon(:icon="['far', 'star']")
```

**Comment by benwalsh** [comment]
D'oh. I think it even says "don't make this exact mistake" in the docs.
