### ISSUE TITLE
Vue 3 props aren't reactive

### ISSUE THREAD

**Issue by Gobd** [FortAwesome/vue-fontawesome#250]
Using version 3.0.0-1 of this library.

```
<font-awesome-icon :icon="computedFunc"/>
```

When computedFunc return value changes the icon doesn't change. This code worked with Vue 2.6.11 & the 0.1.9 release of this library.

**Comment by Gobd** [comment]
Here's a repo with vue2 & vue3 folders as examples. Both were created with `@vue/cli 4.5.4`.

https://github.com/Gobd/fa3-bug

This can be fixed for now by adding a `:key=""` right next to the `:icon` prop with the same value as the icon prop.

**Comment by richardtallent** [comment]
Confirmed, just ran into this bug with 3.0.0-2 with some code that changes the `:icon` dynamically. The `:key=""` workaround seems to work fine for now.

**Comment by ArcherGu** [comment]
I'm having the same problem, although I can add `:key=""` now to solve it，will there be a more elegant way in the future?

**Comment by arodrigueze0215** [comment]
Just I did what @ArcherGu said. I have added the `:key=""` and that worked for me.

**Comment by Livijn** [comment]
Adding `key` shouldn't be necessary. The `key` attribute is used as a hint for Vue's virtual DOM algorithm to keep track of a node's identity.

**Comment by jasonlundien** [comment]
@Gobd ---

Hey there, are you still having issues with this one?

I created a (simple) test cases to verify where I used a `computedFunc` and toggled (with a method) between two different icons.  You should not need the `key` attribute.

Let me know if you are still having issues.

```
// template
<font-awesome-icon :icon="userIcon" size="10x" />
<button @click="toggleUser">toggle icon</button>

// scripts
data() {
    return {
      user: false,
    };
  },

  computed: {
    userIcon() {
      if (this.user) {
        return ["fas", "user"];
      } else {
        return ["fas", "dog"];
      }
    },
  },

  methods: {
    toggleUser() {
      this.user = !this.user;
    },
  },
```

**Comment by jasonlundien** [comment]
Closing, if this is still an issue just let us know.

**Comment by devnull73** [comment]
Hi @jasonlundien, still an issue for me with 3.0.5. I am using Vue 3.4.13, typescript and composition API.

The key workaround works though.

thanks
