### ISSUE TITLE
Use icon in CSS only, not as a component

### ISSUE THREAD

**Issue by nickyoung87** [FortAwesome/vue-fontawesome#253]
I couldn't find anything on this, so sorry if there is a resource out there that I didn't find.

I have been integrating Font Awesome into a Vue project and so far it has gone very smoothly, thank you! The issue I am running into right now is that I need to be able to add a few icons just on the CSS side because I am overwriting the default CSS of another component. So I was hoping I could just do the normal:

```
element:before {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400;
  content: '\f061';
}
```

It does not work though. I even tried adding the icon through the library and still no luck. Is there a proper way to handle this type of occurrence? 

Thanks!

**Comment by robmadole** [comment]
Hey @nickyoung87 . If you want to use CSS just grab the download package from https://fontawesome.com/download or use Kits. This `vue-fontawesome` component is specifically for using SVGs with JavaScript.

**Comment by nickyoung87** [comment]
I am using the component based for the majority of the application, it's just a few instances where I need to use the pure CSS way. So I take it that's not possible without just loading the css package. 

Will there be a conflict if I run the downloaded CSS package along with the component?

**Comment by robmadole** [comment]
Using both SVG and web fonts with CSS is not supported officially. There can be conflicts and we don't have a nice way to prevent them. You also end up double-loading icons which is bad for performance. Sometimes that cost is OK and sometimes it's not.

So, I'll say that it is possible to use them both together. But depending on your tooling and app it may be a maddening chore to get it to work. If you decide to go down this route, I would recommend at least using the Desktop Subsetter (in beta right now) to lighten the payload of web fonts and CSS you have to bundle.

**Comment by nickyoung87** [comment]
Thank you @robmadole I appreciate your time!

I will mark this as closed, have a great day :)
