### ISSUE TITLE
Free 'far' icons cannot be used?

### ISSUE THREAD

**Issue by 6ichem** [FortAwesome/vue-fontawesome#255]
Hey,

I'm trying to add a 'far' icon that is free such as this (https://fontawesome.com/icons/envelope?style=regular) but I can't seem to find how to do so without having to register ''@fortawesome/pro-regular-svg-icons'' which requires additional configuration such as AUTH key for paid users even though this icon is free.

I tried doing it using the regular import like the other free icons from '@fortawesome/free-solid-svg-icons' but that does not seem to work, I also wasn't able to find anything about doing this on the docs. 

I'd appreciate some help on this, thanks in advance.

**Comment by robmadole** [comment]
We have a `@fortawesome/free-regular-svg-icons` packages as well. Give that a shot.

**Comment by 6ichem** [comment]
> We have a `@fortawesome/free-regular-svg-icons` packages as well. Give that a shot.

Thank you!
