### ISSUE TITLE
API proposal, an easier way to select icon set. `set="fas"`

### ISSUE THREAD

**Issue by ngokevin** [FortAwesome/vue-fontawesome#256]
**Is your feature request related to a problem? Please describe.**
I never remember the syntax to change the icon set (far, fab, fas, fal, fad, etc). It's an inline array, which is strange to put into one prop.

**Describe the solution you'd like**

Instead of:

`<font-awesome-icon :icon="['fas', 'user-secret']" />`

Also support:

`<font-awesome-icon set="fas" icon="user-secret" />`

**Describe alternatives you've considered**

Just a syntax / API request. I also sometimes don't remember whether to prefix `fa-` or not, so maybe support both if it doesn't already.

**Comment by ngokevin** [comment]
Even the README reads `<!-- Don't forget to bind the property with ":" (we forget all the time!) -->` haha. We just got PRO, and love it, thank you!

**Comment by christhofer** [comment]
If you are only using solid (fas), you can just use `<font-awesome-icon icon="bell" />`
It will be defaulted to fas, you only needs to use array for other icon set (far, fab, fal, fad)

**Comment by ngokevin** [comment]
yeah i understand, my suggestion is to make the icon set a separate property versus passing it in an array which has lots of special characters to type

**Comment by christhofer** [comment]
https://github.com/FortAwesome/vue-fontawesome#how-about-a-separate-property-for-the-prefix

**Comment by ngokevin** [comment]
Alright. Well, that's sorta sad to contort the API for less common cases. Guess I can wrap the component then.
