### ISSUE TITLE
Icon inside a button or inside a search field ?

### ISSUE THREAD

**Issue by inickca** [FortAwesome/vue-fontawesome#26]
Hi

I am trying to place fa-search inside a search field and every thing I tried put the icon ouside.

Any on how to proceed ?

Tanxs

**Comment by robmadole** [comment]
@inickca this is outside the scope of this repo but I'll give you a hint.

```
<div class="search">
  <input type="text" />
  <i class="fa fa-search"></i>
</div>
```

Now `position: absolute` the `.svg-inline--fa` `<svg>` tag that ends up in there.
