### ISSUE TITLE
Thumbtack icon is not working

### ISSUE THREAD

**Issue by stripathix** [FortAwesome/vue-fontawesome#262]
All other icons are working only thumbtack icon is not working.

Versions of packages used:
```
        "@fortawesome/fontawesome-free": "5.14.0",
        "@fortawesome/fontawesome-svg-core": "1.2.30",
        "@fortawesome/free-solid-svg-icons": "5.14.0",
        "@fortawesome/vue-fontawesome": "3.0.0-1",
        "vue": "3.0.1",
```

**Comment by robmadole** [comment]
@stripathix please provide a reproducible test case and we'll take a look

**Comment by stripathix** [comment]
@robmadole sorry after isolating the issue it was my application CSS issue. It works :).
