### ISSUE TITLE
Icon not working as 'twitch', but working as ['fab', 'twitch']

### ISSUE THREAD

**Issue by gvlasov** [FortAwesome/vue-fontawesome#266]
**Describe the bug**
I have to provide `['fab', 'iconname']` instead of just `'iconname'` in `:icon` property to use icons from `@fortawesome/free-brands-svg-icons`. This is not the case with the rest of icons from `@fortawesome/free-solid-svg-icons`.

**Reproducible test case**
Sorry, not providing a live example, here is the best I have time for:
```ts
import {FontAwesomeIcon} from '@fortawesome/vue-fontawesome'
import {library} from '@fortawesome/fontawesome-svg-core'
import {
    faPatreon,
    faTwitch,
} from '@fortawesome/free-brands-svg-icons'
import {
    faUser,
} from '@fortawesome/free-solid-svg-icons'
library.add(faUser);
library.add(faPatreon);
library.add(faTwitch);
Vue.component('font-awesome-icon', FontAwesomeIcon);
```
```vue
        <div class="method">
            Patreon
            <font-awesome-icon :icon="['fab', 'patreon']"/>
            <font-awesome-icon icon="twitch"/>
            <font-awesome-icon icon="user"/>
        </div>
```
![image](https://user-images.githubusercontent.com/4467948/97542329-60149200-19e8-11eb-8d97-6b15ab3edd21.png)

![image](https://user-images.githubusercontent.com/4467948/97542472-96eaa800-19e8-11eb-8fed-898c52769029.png)

**Expected behavior**
`<font-awesome-icon icon='twitch'/>` should display the icon on page, instead it leaves Vue's `<!-- -->` placeholder

**Desktop:**
```
Chromium | 86.0.4240.75 (Official Build) Arch Linux (64-bit)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | Linux
JavaScript | V8 8.6.395.10
```
```
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/vue-fontawesome": "^2.0.0",
```

**Additional context**
None I guess

**Comment by robmadole** [comment]
This is intentional @gvlasov. Since that icon is part of the brands package you need to use `['fab', 'twitch']`. Am I missing something?

**Comment by gvlasov** [comment]
@robmadole Yeah, sorry, I didn't know that's in the doc, read it now. Having to use a prefix for an icon that otherwise has a unique name just looks unintuitive, but I guess there are reasons for such organization of the default icon namespace other than intuitivity.
