### ISSUE TITLE
Please update index.es.js

### ISSUE THREAD

**Issue by ondaa** [FortAwesome/vue-fontawesome#267]
vue 2.6.11
@fortawesome/vue-fontawesome ^3.0.0-1

-------------

 WARNING  Compiled with 5 warnings                                                                                                                                             10:52:43
 warning  in ./node_modules/@fortawesome/vue-fontawesome/index.es.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@fortawesome/vue-fontawesome/index.es.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@fortawesome/vue-fontawesome/index.es.js

"export 'defineComponent' was not found in 'vue'

 warning  in ./node_modules/@fortawesome/vue-fontawesome/index.es.js

"export 'h' was not found in 'vue'

 warning  in ./node_modules/@fortawesome/vue-fontawesome/index.es.js

"export 'h' was not found in 'vue'

-------------

how to fix this bug ?

[references]
https://github.com/vuejs/rfcs/blob/render-fn-api-change/active-rfcs/0008-render-function-api-change.md

**Comment by ricardovanlaarhoven** [comment]
You are using the vue-fontawesome for vue 3. You should downgrade to `@fortawesome/vue-fontawesome ^2.0.0`

**Comment by ondaa** [comment]
> You are using the vue-fontawesome for vue 3. You should downgrade to `@fortawesome/vue-fontawesome ^2.0.0`

I made a stupid mistake. Thanks for any help in solving it.

**Comment by ricardovanlaarhoven** [comment]
I've made it too..
