### ISSUE TITLE
CDN Self installing version

### ISSUE THREAD

**Issue by DelfsEngineering** [FortAwesome/vue-fontawesome#270]
Often when adding or updating to FA5+ we are just adding a CDN tag but to take advantage of SVG mode we need this module since without it most Vue apps break do to the way the module replaces the original icon tags so we can't use SVG mode.

If this module can be added via a CDN to the front end WITHOUT a build step, that would open up who can use it to a bigger audience.

Ideally it would self install also.

**Comment by cmoine** [comment]
https://medium.com/front-end-weekly/how-to-use-fon-awesome-5-on-vuejs-project-ff0f28310821

Arf sorry... it is using fontawesome without the Vus plugin :(

**Comment by jasonlundien** [comment]
If you are using Vue, you would have to use our [Vue2 or Vue3 component](https://fontawesome.com/v6/docs/web/use-with/vue/#_3-add-the-vue-component).

You can then [add all the icons](https://fontawesome.com/v6/docs/web/use-with/vue/add-icons) (solid, regular, light, thin, duotone, brands, solid-sharp) you would like.

I am going to go ahead and close this issues.  If you have any other issues just let us know.

**Comment by DelfsEngineering** [comment]
The OP was a comment on existing apps that use the CDN tags as the source is not available  ( CMS apps etc ). 
If one has access to this it would be a no-brainer. That is not the request though. 

A self installing add on via CDN tag would solve this.
