### ISSUE TITLE
tsx error

### ISSUE THREAD

**Issue by mivui** [FortAwesome/vue-fontawesome#276]
**Describe the bug**
JSX element type 'FontAwesomeIcon' does not have any construct or call signatures.

**Reproducible test case**
Include a URL (codepen.io, jsfiddle.net, Git repository, codesandbox.io, stackblitz.com, etc.) that demonstrates the problem.

**Expected behavior**
![image](https://user-images.githubusercontent.com/49021590/103476882-6104de00-4df4-11eb-85ef-23929d6d199e.png)

**Desktop (please complete the following information):**
 - Version
 "vue": "^3.0.5",
@fortawesome/vue-fontawesome": "^3.0.0-3"

**Additional context**

**Comment by robmadole** [comment]
@uinio if you can provide a reproducible test case we'll be happy to take a look. Until then I'll close this. (and I'll re-open as soon as you provide the test case)

**Comment by uinio** [comment]
```ts
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(fas);

import { defineComponent, InputHTMLAttributes } from 'vue';

export interface IconProps extends Omit<InputHTMLAttributes, 'innerHTML'> {
  icon: string;
  innerHTML?: JSX.Element | string;
}

export default defineComponent({
  name: 'fontIcon',
  setup(props: IconProps) {
    return () => <FontAwesomeIcon icon={props.icon} />;
  },
});
```
dependencies
 "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@fortawesome/vue-fontawesome": "^3.0.0-3",
    "@vue/babel-plugin-jsx": "^1.0.1",
    "vue": "^3.0.5",
    "vue-router": "^4.0.2"

error: TS2604: JSX element type 'FontAwesomeIcon' does not have any construct or call signatures.

**Comment by mivui** [comment]
fix
https://github.com/FortAwesome/vue-fontawesome/blob/3.x/index.d.ts
EndOfLine

```ts
declare const FontAwesomeIcon: DefineComponent<FontAwesomeIconProps>
declare const FontAwesomeLayers: DefineComponent<FontAwesomeLayersProps>
declare const FontAwesomeLayersText: DefineComponent<FontAwesomeLayersTextProps>
```

**Comment by XiNiHa** [comment]
Just faced the same issue. Use `FontAwesomeIcon` inside TSX and a type error will pop in.

**Comment by Maxim-Mazurok** [comment]
Same issue, using with boilerplate vue 3 TSX repo. Fix by uinio works, will use https://www.npmjs.com/package/patch-package for now

**Comment by Maxim-Mazurok** [comment]
@robmadole here's a reproduction repo: https://github.com/Maxim-Mazurok/vue3-fa-repro, please see README.md for instructions, and please reopen this issue, thanks!

**Comment by robmadole** [comment]
perfect @Maxim-Mazurok we'll take a look.

**Comment by mivui** [comment]
@fortawesome/vue-fontawesome 3.0.2 fixed https://github.com/FortAwesome/vue-fontawesome/issues/276#issuecomment-761770180
