### ISSUE TITLE
 CodeSandbox Starter Sample missing

### ISSUE THREAD

**Issue by ghostrydr** [FortAwesome/vue-fontawesome#278]
**Describe the bug**
Clicking _CodeSandbox Starter Sample_ in the [README.md](https://github.com/FortAwesome/vue-fontawesome TOC doesn't jump to section, plus clicking the link-out to CodeSandbox lower down in the content results in a _No commit found for SHA: master/examples/vue-cli-webpack_ error

**Reproducible test case**
See project [README.md](https://github.com/FortAwesome/vue-fontawesome#codesandbox-starter-sample-)

**Expected behavior**
Expect Starter example to exist, or refer to the example in the repo

**Comment by jasonlundien** [comment]
Hey @ghostrydr ---

We have updated our REAADME.md and our [Vue 2 and Vue 3 docs](https://fontawesome.com/v6/docs/web/use-with/vue/add-icons) on the proper usage of our icons.

I am going to go ahead and close this issue.  If you feel it should remain open just let us know.
