### ISSUE TITLE
Readme Installation steps not complete

### ISSUE THREAD

**Issue by joshtom** [FortAwesome/vue-fontawesome#279]
After following the installation steps in the readme, this part ``` import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"; ``` returns an error.

- The following lines should be added to the Readme to complete the installation steps
```
yarn add @fortawesome/vue-fontawesome
```

```
npm i --save @fortawesome/vue-fontawesome
```

**Comment by christhofer** [comment]
It's already been there

![image](https://user-images.githubusercontent.com/13524958/103969964-bbf25880-5199-11eb-9a05-26f93e6ae830.png)

**Comment by joshtom** [comment]
Ohhhhhhh, I didn't notice. Thanks!
