### ISSUE TITLE
import { faCoffee } from '@fortawesome/fontawesome-free-solid' load all icons from solid

### ISSUE THREAD

**Issue by s3rg3** [FortAwesome/vue-fontawesome#28]
Hello,

With
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
import fontawesome from '@fortawesome/fontawesome';
import { faCoffee } from '@fortawesome/fontawesome-free-solid';
fontawesome.library.add(faCoffee);

All icons from solid render despite not importing them.

**Comment by robmadole** [comment]
this syntax is easier and more bullet-proof:

`import faCoffee from '@fortawesome/fontawesome-free-solid/faCoffee'`

You'll need to configure tree-shaking in your build tool in order to prevent bundling unnecessary icons https://fontawesome.com/how-to-use/font-awesome-api#advanced-stuff

**Comment by s3rg3** [comment]
ok, thank you

i'll use this syntax: import faCoffee from '@fortawesome/fontawesome-free-solid/faCoffee'

it works as intended.
