### ISSUE TITLE
Some Free brand fab won't load on safari iOS

### ISSUE THREAD

**Issue by feiwhang** [FortAwesome/vue-fontawesome#280]
Some of the free brands icon won't load on safari ios but load normally on other devices

On Chrome macOS
![Ywz9y](https://user-images.githubusercontent.com/49202744/104176659-3214ea80-543a-11eb-9234-f571dd7ce188.png)

On Safari iOS
![Xu3OS](https://user-images.githubusercontent.com/49202744/104176674-36410800-543a-11eb-81e5-73f88fe3c8ba.jpg)

My code

In main.js
`import { faFacebookF, faLine, faYoutube } from "@fortawesome/free-brands-svg-icons";`
`library.add([ faFacebookF, faLine, faYoutube ]);`

In component.vue
` <font-awesome-icon :icon="{ prefix: 'fab', iconName: facebook-f }"/>`
` <font-awesome-icon :icon="{ prefix: 'fab', iconName: youtube }"/>`
` <font-awesome-icon :icon="{ prefix: 'fab', iconName: line }"/>`

**Comment by gregmarzio** [comment]
Experiencing a similar issue where Solid icons are loading but Brands icons are not.

**Comment by jasonlundien** [comment]
hey @gregmarzio ---

Are you still seeing issues in safari ?

I just tested and the icons will show if you use the following syntax:

String format
  `<font-awesome-icon icon="fa-brands fa-youtube" />`
  `<font-awesome-icon icon="fa-brands fa-facebook-f" />`
  `<font-awesome-icon icon="fa-brands fa-line" />`

Array Format
  `<font-awesome-icon :icon="['fab', 'youtube']" />`
  `<font-awesome-icon :icon="['fab', 'facebook-f']" />`
  `<font-awesome-icon :icon="['fab', 'line']" />`

I am going to go ahead and close this issue... if you still are having issues let us know and we can reopen if necessary.
