### ISSUE TITLE
fonts not available in exported component

### ISSUE THREAD

**Issue by jamesdixon** [FortAwesome/vue-fontawesome#282]
Hi, this is 99% probably not a bug with this lib but asking here to see if anyone has a quick tip to get this working:

I am publishing an npm package with a Vue component to be shared across a couple of other applications. When running this component, all icons show up as expected. However, when publishing the package and importing it elsewhere, the icons do not display.

Is there a trick to getting this to work properly?

This is a basic Vue 2 CLI app and I've used the following code for importing and setting up the icons:

```
import Vue from 'vue'
import App from './App.vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import './style/application.scss'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faArrowLeft, faBackward, faSunset, faSunrise, faMinus, faPlus, faUndo, faRedo, faCircle, faFont, faLongArrowAltRight, faSquare, faTrash, faComment, faCheck, faCheckCircle } from '@fortawesome/pro-light-svg-icons'
import { dom } from '@fortawesome/fontawesome-svg-core'

// add needed icons explicitly to take advantage of tree-shaking
library.add(faArrowLeft, faBackward, faSunset, faSunrise, faMinus, faPlus, faUndo, faRedo, faCircle, faFont, faLongArrowAltRight, faSquare, faTrash, faComment, faCheck, faCheckCircle)

// converts <i> tags into svg
// https://github.com/FortAwesome/vue-fontawesome#processing-i-tags-into-svg-using-font-awesome
dom.watch()

Vue.use(Vuetify, {
  theme: {
    primary: '#5c9ccf',
    secondary: '#45769c',
    error: '#d53636',
    info: '#65c635',
    success: '#65c635',
    warning: '#d53636'
  }
})

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')
```

Thanks in advance!

**Comment by magedhennawy** [comment]
When you do an npm install in the project importing your component, does it properly install the pro package?

**Comment by jamesdixon** [comment]
@magedhennawy yes it does!

![image](https://user-images.githubusercontent.com/110114/105225434-2ef9b880-5b24-11eb-9212-cc8ecafa2d68.png)

**Comment by magedhennawy** [comment]
How do you serve it from your main project?

**Comment by jamesdixon** [comment]
It's imported in `main.js` as in the code above.

**Comment by jamesdixon** [comment]
@magedhennawy found the issue. thanks for your responses

**Comment by GreyXor** [comment]
> @magedhennawy found the issue. thanks for your responses

You could share the solution.
