### ISSUE TITLE
Icons appearing very large

### ISSUE THREAD

**Issue by sdaitzman** [FortAwesome/vue-fontawesome#283]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/1499476/105506736-5a051900-5c98-11eb-9239-614785bf052e.png">

**Describe the bug**
Since upgrading npm packages, all the icons are appearing extremely large.

**Reproducible test case**
Currently rolled-back in my Netlify deploy, but it's this tag: https://600add46972af6000869a14e--sdaitzman.netlify.app

Which is even with main here at this commit (I'm temporarily swapping the plugin out of my site in later commits): https://github.com/sdaitzman/sam.daitzman.com/tree/86d39cb2cc9ddf49faa56a4d1ef5f6bbc16ba382

**Expected behavior**
Icons appear at the approximate size of the surrounding font, or at some default scale that matches a typical font size.

**Desktop (please complete the following information):**
 - Reproduced in all browsers I tried, but currently using latest macOS & Safari

**Additional context**
Seems quite connected to #103 and its connected nuxt issues.

**Comment by sdaitzman** [comment]
For reference, the relevant code: https://github.com/sdaitzman/sam.daitzman.com/blob/86d39cb2cc9ddf49faa56a4d1ef5f6bbc16ba382/.vuepress/components/Profiles.vue

**Comment by jasonlundien** [comment]
@sdaitzman ---

Just wanted to check in here ... are you still having the large icon issue ?

We have released a few versions since your initial post, and I have not seen anything lately about this issue.

**Comment by jasonlundien** [comment]
I am going to go ahead and close this issue.  If this occurs again just let us know.
