### ISSUE TITLE
Unable to use vue conditional logic in icon attribute

### ISSUE THREAD

**Issue by holmesadrianh** [FortAwesome/vue-fontawesome#284]
The following fails as icon is passed 'undefined':

`<font-awesome-icon :icon="{'info-circle': alertType == 'info', 'check-circle': alertType == 'success', 'exclamation-triangle': alertType == 'danger'}" />`

The logic works for a class name:

`<span :class="{'bg-success': activeFilter == 'true', 'bg-danger': activeFilter == 'false', 'bg-info': activeFilter == ''}">`

Am I missing something?

**Comment by robmadole** [comment]
@holmesadrianh the `:class` has [special handling](https://vuejs.org/v2/guide/class-and-style.html) that our `:icon` property does not. It needs to be a string or an icon object. Please check the docs again.

**Comment by holmesadrianh** [comment]
For anyone else, it was not a vuejs issue or fontawesome. It was just syntax. Here is a working solution:

`<font-awesome-icon :icon="(alertType == 'success') ? 'check-circle' : (alertType == 'danger') ? 'exclamation-triangle' : 'info-circle'" />
`
