### ISSUE TITLE
all.css is not bundled

### ISSUE THREAD

**Issue by Kameecoding** [FortAwesome/vue-fontawesome#285]
**Describe the bug**
If I go offline font-awesome icons no longer work because there is an attempt to download css from the web.
GET `https://use.fontawesome.com/releases/v5.6.3/css/all.css`

**Reproducible test case**
main.js

```
import { library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
library.add(fas);
library.add(far);
library.add(fab);
Vue.component("fa", FontAwesomeIcon);

```

**Expected behavior**
I would expect this css file to be part of the bundle when vue-cli is done with the build so there is no need to call external resources.

**Desktop (please complete the following information):**
 - Browser 
 - Version - 
```
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "5.13.0",
    "@fortawesome/free-regular-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/vue-fontawesome": "^2.0.0",
```

**Additional context**

**Comment by Kameecoding** [comment]
nvm I had to add the css file to the public folder and load it in index.html from there.

however it would be nice if we were able to bundle this css file automatically.

**Comment by jasonlundien** [comment]
@Kameecoding ---

I do not see this being an issue any longer, so I am going to go ahead and close.  If you feel this still needs to remain open just let us know.
