### ISSUE TITLE
"Uncaught TypeError: Object(...) is not a function" on Import

### ISSUE THREAD

**Issue by joaoggnogueira** [FortAwesome/vue-fontawesome#286]
i'm following this example on Vue 3

```
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'; //error here

library.add(faUserSecret);

Vue.config.productionTip = false
Vue.component('font-awesome-icon', FontAwesomeIcon)
```

The Vue is crashing, and cannot render anything

![image](https://user-images.githubusercontent.com/10080622/106684815-f3400380-65a5-11eb-99ca-ed6900f81cad.png)

Also, i'm using the lastest version of vue-fontawesome dependencies

![image](https://user-images.githubusercontent.com/10080622/106684921-24203880-65a6-11eb-9601-489ffdb85d43.png)

**Comment by thijstriemstra** [comment]
same issue here using:

```
"@fortawesome/fontawesome-svg-core": "^1.2.34",
"@fortawesome/free-brands-svg-icons": "^5.15.2",
"@fortawesome/vue-fontawesome": "^3.0.0-3",
```

**Comment by runxc1** [comment]
It seems that there is a major issue with Vue-fontawesome and that it should not be used in a Vue3 project.

https://github.com/vuejs/vue-next/issues/4707

**Comment by robmadole** [comment]
https://github.com/vuejs/vue-next/issues/4707 is not using the `vue-fontawesome` component. I've left a comment.

**Comment by robmadole** [comment]
@joaoggnogueira @thijstriemstra if you can provide a reproducible example we'll be happy to take a look but we need more than a couple of code snippets and a screenshot. I'll re-open this ticket if either of you have time to provide that.
