### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by abudayah** [FortAwesome/vue-fontawesome#29]
I faced an issue when using vue-fontawesome on main.js, check the details:

My code:
<img width="672" alt="screen shot 2017-12-21 at 8 08 53 pm" src="https://user-images.githubusercontent.com/1739369/34268831-d97293de-e68a-11e7-9625-cdc039694137.png">

The issue:
<img width="507" alt="screen shot 2017-12-21 at 8 07 38 pm" src="https://user-images.githubusercontent.com/1739369/34268799-ba8f88aa-e68a-11e7-823d-d5726d91cfc2.png">

**Comment by robmadole** [comment]
```
import fontawesome from '@fortawesome/fontawesome'
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
```

Try that, @abudayah

**Comment by OriginalEXE** [comment]
Hi,

You are importing the wrong package.Try this:
```
import fontawesome from '@fortawesome/fontawesome';
```
and your component is this:
```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
```

**Comment by abudayah** [comment]
WOW that was fast lol, thanks everyone :)
