### ISSUE TITLE
Only user-secret icon works

### ISSUE THREAD

**Issue by prasad-kumkar** [FortAwesome/vue-fontawesome#290]
**Describe the bug**
i am following the instructions to implement vue-fontawesome. I have got the user-secret icon to show up, but when i change it to any other icon, it does not appear.

**Reproducible test case**
Use the About.vue page:
https://codesandbox.io/s/busy-gareth-gg57d?file=/src/views/About.vue
1. Try using user-secret icon on line6
![image](https://user-images.githubusercontent.com/43164022/109333303-4ba4b100-7885-11eb-80c1-ac1e80e319c7.png)

2. Try using any other icon
![image](https://user-images.githubusercontent.com/43164022/109333405-6ecf6080-7885-11eb-8f66-cc08ce3cf30b.png)

![image](https://user-images.githubusercontent.com/43164022/109333377-64ad6200-7885-11eb-804a-6e223e38c99b.png)

**Desktop (please complete the following information):**
 - Browser Brave
 - Version 1.9.92

**Comment by yaron-shamul** [comment]
on it too!

**Comment by yaron-shamul** [comment]
anything new about this issue? I'm stuck on it too

**Comment by christhofer** [comment]
@prasad-kumkar you don't have faCoffee imported.
You need to import every icons you need

Change these
```
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
library.add(faUserSecret)
```

into these
```
import { faUserSecret, faCoffee } from '@fortawesome/free-solid-svg-icons'
library.add(faUserSecret, faCoffee)
```

**Comment by prasad-kumkar** [comment]
Thank you @christhofer , i hadn't noticed that.

**Comment by teguhsatria892** [comment]
import { fas } from '@fortawesome/free-solid-svg-icons'


and 


library.add(fas)


do did to add all icon from free-solid-svg-icons without one by one
