### ISSUE TITLE
Vue 3 Compatibility Status?

### ISSUE THREAD

**Issue by richardtallent** [FortAwesome/vue-fontawesome#294]
The issue related to Vue 3 reactivity has been active now for 7 months (#250), and there hasn't been any visible progress on the Vue 3.x branch in over three months.

- Is there still an intent to create a Vue 3 compatible version of this component, with reactive issues fixed?
- If so, is there anything that we Vue 3 developers can assist with to get this back on track?

**Comment by otijhuis** [comment]
Created a PR (#297) to add reactivity support. Tested it with dynamic icons, sizes, spinning true/false, layer counters and HMR (vitejs). Didn't run into any issues so hopefully it makes it into the next release.

**Comment by jasonlundien** [comment]
Closing issue... we have an official working Vue 3 component.
If you have any other issues or problems just let us know.
