### ISSUE TITLE
Icon doesnt changes after changing variable

### ISSUE THREAD

**Issue by Yonier** [FortAwesome/vue-fontawesome#296]
**Describe the bug**
Im making a simple ui where the users select an icon from a menu and then shows what icon the user have selected, im loading the font awesome from a component like this:

<font-awesome-icon v-if="this.icon.length > 0" :icon="[this.icon[0], this.icon[1]]" size="4x" />

After the user select an icon and then tries to select another icon the component doesnt update:

https://i.ibb.co/ZW4Sbfk/image.png

versions:

"@fortawesome/angular-fontawesome": "^0.8.1",
"@fortawesome/fontawesome-svg-core": "^1.2.34",
"@fortawesome/free-brands-svg-icons": "^5.15.2",
"@fortawesome/free-regular-svg-icons": "^5.15.2",
"@fortawesome/free-solid-svg-icons": "^5.15.2",
"@fortawesome/vue-fontawesome": "^3.0.0-1",
"@ionic/vue": "^5.4.0",

Thanks!.

**Comment by otijhuis** [comment]
It's a known issue, see #250. You can try and use the `key` attribute for now as a workaround.

**Comment by Yonier** [comment]
It worked, thanks @otijhuis !
