### ISSUE TITLE
DRY library.add

### ISSUE THREAD

**Issue by Ahmed7fathi** [FortAwesome/vue-fontawesome#304]
anyway to not repeat my self on library.add 
if i imported multiple icons i need also to add them it's redundant 

> import {
  faHome,
  faSearch,
  faTrash,
  faEdit,
  faUsers,
  faEnvelope,
  faAddressCard,
  faStopwatch,
  faClipboardCheck,
  faArrowCircleLeft,
  faArrowCircleRight,
  faPen,
  faTimes,
  faInfo,
  faStickyNote,
  faTable,
  faPlus,
  faCheck
} from "@fortawesome/free-solid-svg-icons";

> library.add(
>   faHome,
>   faSearch,
>   faTrash,
>   faEdit,
>   faUsers,
>   faEnvelope,
>   faAddressCard,
>   faFacebook,
>   faTwitter,
>   faInstagram,
>   faStopwatch,
>   faClipboardCheck,
>   faArrowCircleLeft,
>   faArrowCircleRight,
>   faPen,
>   faTimes,
>   faInfo,
>   faStickyNote,
>   faTable,
>   faPlus,
>   faCheck
> );

any way to avoid that ?

**Comment by christhofer** [comment]
If you don't want to import each icons, you can import all of them at once
```js
import * as icons from '@fortawesome/free-solid-svg-icons'
library.add(icons.faCoffee)
```
but you'll end up with bulky js bundle.

Or you can use the cdn way, and use `<i class="fas fa-coffee">`. You'll have the same bulky bundle size because you get all of the icons either way.

Tip: Just use the recommended way, import every icons you are using. You are likely doesn't need all the icons.

**Comment by Ahmed7fathi** [comment]
I didn't import all of icons and i don't want to because  the size of the bundle indeed and i also not going to use the cdn way 
it's not a good thing when i add an icon add it twice

**Comment by kad-tijhuo** [comment]
Not sure why it would be redundant and not a good thing. It's no different than any other imported named export. You import it and then use it. This makes it explicit. Doing some magic under the hood just to save some typing is often far worse and less flexible.

**Comment by robmadole** [comment]
@Ahmed7fathi if you have some recommendations we'd be up for hearing them. I'll go ahead and close this though as there isn't much we can do that I know of.
