### ISSUE TITLE
Vue 3 + FA 6 beta support?

### ISSUE THREAD

**Issue by richardtallent** [FortAwesome/vue-fontawesome#318]
I'm using Vue 3, and would like to start our testing with the v6 beta icons.

From what I can tell, only the old Vue 2 branch supports this so far.

**Comment by robmadole** [comment]
@richardtallent you are correct. The changes to support version 6 are small but that work hasn't been done yet for our Vue 3 version of `vue-fontawesome`.

**Comment by eMeRiKa13** [comment]
@robmadole Did you do any progress since June? How we can help you? Thanks

**Comment by niallthompson** [comment]
What's the timeframe on this? Thank you!

**Comment by adrianrudnik** [comment]
Is the [release schedule](https://blog.fontawesome.com/version-6-release-schedule/) still correct? If so, any estimate when `@next` will be available? Would help in regards to include or exclude version 6 in planning for current client projects.

**Comment by martinpokorny** [comment]
Based on [this release blogpost](blog.fontawesome.com/font-awesome-6/) and particularly the sentence:

>Font Awesome 6 makes it even easier to use icons where you want to. More plugins and packages to match your stack. Less time wrestling browser rendering.

I'm guessing the update will come with the final release of FA 6 in Februray, is that correct? :)

**Comment by jasonlundien** [comment]
We have updated our Vue 3 and Vue 2 packages along with our [docs](https://fontawesome.com/docs/web/use-with/vue/), both supporting FA6. 

I will go ahead and close this issue. If you feel that it needs to remain open just let me know.

**Comment by richardtallent** [comment]
Is 3.x going to be come the default version for npm?

Vue 3 was released 16 months ago.

**Comment by jasonlundien** [comment]
If you just run `npm i @fortawesome/vue-fontawesome` you will be getting our "latest" Vue 2 version.
So to get our Vue 3 component you would have to run `npm i --save @fortawesome/vue-fontawesome@latest-3`.

In terms of changing `latest` to Vue 3, we will be watching the downloads to gauge.
