### ISSUE TITLE
the appearing icon are too large before the css finishes loading

### ISSUE THREAD

**Issue by dreamer2q** [FortAwesome/vue-fontawesome#323]
As the title points out, before all the css finishes loading, the svg icon has a very large `viewport`.

Because of this, I have to add inline-style like `max-width: 14px` to enforce a smooth loading experience.

![image](https://user-images.githubusercontent.com/56211747/129158984-b4f00cca-9109-4480-b030-8153bc5f931e.png)

This is surely a fault considering most icons should not be a such large size (or `viewport`)

**Comment by jasonlundien** [comment]
Hi @dreamer2q 

I see that this issue is fairly old, are you still experiencing issues?
If so, can you provide a reproducible test case  (I am not seeing this with our Vue 2 or Vue 3 components)?

**Comment by jasonlundien** [comment]
@dreamer2q ---

Going to go ahead and close this issue.  If you provide a reproducible repo we can re-open.
