### ISSUE TITLE
Missing relative sizing values in v3 / FA6 branch

### ISSUE THREAD

**Issue by ux-engineer** [FortAwesome/vue-fontawesome#326]
In FA6 documentation about sizing, in [relative sizing section](https://fontawesome.com/v6.0/docs/web/style/size#relative-sizing), there are these sizing values available: **2xs, xs, sm, lg, xl, 2xl**

Your Vue component's [size property validator](https://github.com/FortAwesome/vue-fontawesome/blob/3.x/src/components/FontAwesomeIcon.js) **is missing these values: 2xs, xl, 2xl**

You also might want to consider allowing `undefined` value to be used along with `null`, as an empty value.

**Comment by ahudovich** [comment]
**2.x branch (the right number of sizes):**
https://github.com/FortAwesome/vue-fontawesome/blob/ba927d03b224463f98f266a4c24914448fd84a71/src/components/FontAwesomeIcon.js#L98

**3.x branch:**
https://github.com/FortAwesome/vue-fontawesome/blob/efe9812b74b77fcb287e5f86fe9ee6f9e3efbb5f/src/components/FontAwesomeIcon.js#L75

This leads to Vue warns when using missing sizes:

`[Vue warn]: Invalid prop: custom validator check failed for prop "size".`

**Comment by jasonlundien** [comment]
@ux-engineer & @andrei-hudovich ---

We have updated our Vue 3 (official now) package to include the relative sizing.  You should be good to go now. I will go ahead and close this issue. If you feel that it needs to remain open just let me know.
