### ISSUE TITLE
vue-fontawesome not work with beta2

### ISSUE THREAD

**Issue by mustafaahmed7** [FortAwesome/vue-fontawesome#329]
`error code ERESOLVE
error ERESOLVE unable to resolve dependency tree
error
error Found: @fortawesome/fontawesome-svg-core@1.3.0-beta2
error node_modules/@fortawesome/fontawesome-svg-core
error   @fortawesome/fontawesome-svg-core@"^1.3.0-beta2" from the root project
error
error Could not resolve dependency:
error peer @fortawesome/fontawesome-svg-core@">= 1.2.0 < 1.3" from @fortawesome/vue-fontawesome@2.0.2
error node_modules/@fortawesome/vue-fontawesome
error   @fortawesome/vue-fontawesome@"2.0.2" from the root project
error
error Fix the upstream dependency conflict, or retry
error this command with --force, or --legacy-peer-deps
error to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by jasonlundien** [comment]
Hi @mustafaahmed7 ---

We have updated our Vue 3 and Vue 2 packages along with our [docs](https://fontawesome.com/docs/web/use-with/vue/). You should be good to go now. I will go ahead and close this issue. If you feel that it needs to remain open just let me know.
