### ISSUE TITLE
FontAwesomeIcon: Use an animation prop instead of separate boolean props.

### ISSUE THREAD

**Issue by jpickwell** [FortAwesome/vue-fontawesome#33]
I feel that `pulse` and `spin` are mutually exclusive animation properties. It would be easier (in the sense of library coding) to use an `animation` property.

Having the `animation` property would also facilitate future additions of animation types instead of adding more boolean properties.

Now is a good time to make this change because a 1.0 release hasn't been made.

**Comment by robmadole** [comment]
Hi @jpickwell . These are good thoughts but we are going to stick with the current API. There will most likely not be future animations added to Font Awesome as projects like animate.css do a fantastic job at filling this need (which we fully support integration with.)

Thanks for the thoughts.
