### ISSUE TITLE
FontAwesomeIcon: Use symbol.

### ISSUE THREAD

**Issue by jpickwell** [FortAwesome/vue-fontawesome#34]
You can currently create a symbol, but there's no way to use that symbol through the component.

Options:
1. new component
2. add new `use` prop to FontAwesomeIcon
3. change how `symbol` works in the component

For option 3, I'm thinking that the component would prepend the symbol version of the icon to the body (if it doesn't already exist on the page), and then render the use-markup. This would make symbol usage straightforward and automatic (in the sense of markup).

**Comment by robmadole** [comment]
@jpickwell the point of the symbol is so you can leverage the SVG sprites technique directly. We do not want to burden Vue or the JavaScript engine by processing anything else. Thanks for the comments.

**Comment by jpickwell** [comment]
The documentation for how to use the symbols needs to be expanded. The example shows a css size class on the symbol usage, but there's no documentation about these size classes.

I feel that there should be a component that makes using symbols straightforward.
