### ISSUE TITLE
Fontawesome is being purge after building in nuxt

### ISSUE THREAD

**Issue by phojie** [FortAwesome/vue-fontawesome#349]
**Describe the bug**
Fontawesome icons is not recognized in production mode

**Desktop (please complete the following information):**
 - Nuxt: 2.15.8
 - Tailwind v3
 - vue-font-awesome 2.0.6

**Comment by sheldonbaker** [comment]
Happening for me too.

* Nuxt: 2.15.8
* vue-font-awesome 2.0.6

**Comment by GuasaPlay** [comment]
Happens to me too :C

Purge all classes even though it is already specified in the whitelistPatterns

nuxt.config.js file
```
...
  purgeCSS: {
    whitelistPatterns: [/svg.*/, /fa.*/],
  },
...
```

**Comment by robmadole** [comment]
Hey, can you all double-check that you are using the `@fortawesome/vue-fontawesome` package? If it's `vue-font-awesome` (with a space after font) that's a different project than this one.

**Comment by bhuvidya** [comment]
Same thing is happening for me. Loading fine on local dev, but not loading on a SSR build on live server. Html has the fa-icon element "untouched":

```
<fa-icon icon="far,copy" class="copy-icon"></fa-icon>
```

Any help greatly appreciated.

Nuxt 2.15.8
@nuxtjs/fontawesome: ^1.1.2
@fortawesome/free-regular-svg-icons: ^6.1.1
@fortawesome/vue-fontawesome: 0.1.10 (via @nuxtjs/fontawesome)

**Comment by bhuvidya** [comment]
Ok I found it - the "suffix" config option for @nuxtjs/fontawesome had to be explicitly set, and it was a different default on dev site (true) to server build (false).

**Comment by jasonlundien** [comment]
@Phojie ---

Are you still having issues ?  Did you check to make sure you had `@fortawesome/vue-fontawesome` ?

**Comment by MrTob** [comment]
> Ok I found it - the "suffix" config option for @nuxtjs/fontawesome had to be explicitly set, and it was a different default on dev site (true) to server build (false).

same issue here on dev working fine, production build no icons, can you provide me detailed infos how you solved it?
![image](https://user-images.githubusercontent.com/30464573/181808065-253704ad-b1ed-4c62-8b9a-fc5d81223090.png)
these are my dependencies

**Comment by phojie** [comment]
Here's I solve the issue

Instead of importing the css file from node_modules @fortawesome folder, I just copy the css file located in **node_modules /@fortawesome/fontawesome-svg-core/style.css** to my assets/css folder  and import it manually in nuxt.config.js

```.js
css: [
    '@/assets/css/fontawesome.css',
  ],
```
