### ISSUE TITLE
Using 'vue-fontawsome' disables the default FontAwesome JS

### ISSUE THREAD

**Issue by jpscharf** [FortAwesome/vue-fontawesome#35]
If you use `vue-fontawesome` then the regular FontAwesome does not work:

```html
<font-awesome-icon :icon="['fal', 'compress-alt']" />
<i class="fas fa-arrow-down" />
```

![image](https://user-images.githubusercontent.com/1039984/34498820-5120b3f8-efd1-11e7-89b4-075e55b67ffd.png)

**Comment by robmadole** [comment]
`vue-fontawesome` [disables automatic icon replacement](https://github.com/FortAwesome/vue-fontawesome/blob/master/src/index.js#L4) when you decide to use a library or framework that has a virtual DOM (Vue, React, etc).

The reason why we cannot support both is that any modifications to a DOM element controlled by Vue should not be mutated outside of the control of Vue. This destroys the ability for virtual DOMs to correctly apply and detect diffs against a given state.

**Comment by robmadole** [comment]
We've actually been doing some work on this and think we might be able to resolve this after all. I've re-opened this and probably next week we'll look at getting some pre-releases out that will accommodate this.

**Comment by Dylan-DutchAndBold** [comment]
Run into the same issue here, is there any update on this?

**Comment by robmadole** [comment]
This work is still in flight. We'll have a 5.1.0 pre-release available as soon as we can.

**Comment by jacobg** [comment]
Looking forward to this fix to support both vue and non-vue working together.

**Comment by robmadole** [comment]
New docs up https://github.com/FortAwesome/vue-fontawesome#processing-i-tags-into-svg-using-font-awesome
