### ISSUE TITLE
Unexpected token 'export' on Nuxt 2 + bridge real server but not dev server

### ISSUE THREAD

**Issue by FayKn** [FortAwesome/vue-fontawesome#351]
**Describe the bug**
The icons and plugin works fine but on the Nuxt dev server (npm run dev) but when I use the real server (npm run start after an npm run build) I get Unexpected token 'export'

**Reproducible test case**
fontawesome.js
`import Vue from 'vue'
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { fas } from '@fortawesome/free-solid-svg-icons'

// This is important, we are going to let Nuxt.js worry about the CSS
config.autoAddCss = false

// You can add your icons directly in this plugin. See other examples for how you
// can add other styles or just individual icons.
library.add(fas)

// Register the component globally
Vue.component('font-awesome-icon', FontAwesomeIcon)
`
Nuxt config
`  css: [
    '@fortawesome/fontawesome-svg-core/styles.css'
  ],
`

`  plugins: [
    '~/plugins/helpers.js',
    '~/plugins/fontawesome.js',
    '~/plugins/stripemenu.js'
  ],
`

**Expected behavior**
I expected the page to load and show my icons like on the dev server

**Desktop (please complete the following information):**
Google Chrome 98.0.4758.102

**Comment by robmadole** [comment]
Hey thanks @Ovab we'll take a look at this as soon as we can.

**Comment by jasonlundien** [comment]
@Ovab ---

Are you still having this issue ?

I am using `"@fortawesome/fontawesome-svg-core": "^6.1.1"` and `"@fortawesome/free-solid-svg-icons": "^6.1.1",`.
Running  `npm run start` after an `npm run build` is showing the icons without any errors or warning.

**Comment by jasonlundien** [comment]
I am going to go ahead and close this issue.
If you are still having a problem let us know and we can re-open if need be.
