### ISSUE TITLE
Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack'

### ISSUE THREAD

**Issue by rrd108** [FortAwesome/vue-fontawesome#353]
I run into the same as https://github.com/FortAwesome/angular-fontawesome/issues/125 but with vuejs 3

Downgrade to 1.2.36 does solve the problem for me.

**Comment by frankykubo** [comment]
I've run into that as well, but updating other dependencies resolved the problem.

@fortawesome/fontawesome-svg-core to **^6.1.0** and
@fortawesome/free-solid-svg-icons to **^6.1.0** as well.

My @fortawesome/vue-fontawesome version is **3.0.0-5**.

**Comment by christhofer** [comment]
FA6 does not support Vue 3 yet
https://fontawesome.com/docs/web/use-with/vue/troubleshoot#using-vue-3

**Comment by frankykubo** [comment]
> FA6 does not support Vue 3 yet https://fontawesome.com/docs/web/use-with/vue/troubleshoot#using-vue-3

Official version is not out yet, but there is prerelease out for pretty long time actually, which is working really fine.
https://stackoverflow.com/questions/66389974/using-font-awesome-in-vue-3

**Comment by christhofer** [comment]
Yes, I know @prerelease for vue 3, but that is for FA5. I have been using it in all my projects.
Can you use it with FA6? I haven't tried because no mention about FA6 in the documentation.

**Comment by frankykubo** [comment]
> Yes, I know @prerelease for vue 3, but that is for FA5. I have been using it in all my projects. Can you use it with FA6? I haven't tried because no mention about FA6 in the documentation.

Not sure if it's officially supported, but it is working in my Vue3 project without any issues.

**Comment by jasonlundien** [comment]
Hi @rrd108 --- 

We have updated our Vue 3 (official) package, with FA6 support, along with our [docs](https://fontawesome.com/docs/web/use-with/vue/). You should be good to go now. I will go ahead and close this issue.  You should NOT be seeing the error any longer.  I am going to go ahead and close this issue.  If you feel that it needs to remain open just let us know.
