### ISSUE TITLE
Icon shaking

### ISSUE THREAD

**Issue by Pinnokkio** [FortAwesome/vue-fontawesome#356]
**Describe the solution you'd like**
FontAwesome accepts icon shaking: https://fontawesome.com/docs/web/style/animate#shake VueFontAwesome does not.
Example of how it could be: `<fa :icon="['far', 'bell']" shake/>`

**Comment by jasonlundien** [comment]
HI @Pinnokkio ---

We have updated our Vue 3 package to include the `shake` animation along with a few other things that were missing.  You should be good to go now. I will go ahead and close this issue. If you have any other problems just let us know.
