### ISSUE TITLE
when update vue 3 version?

### ISSUE THREAD

**Issue by skimhugo** [FortAwesome/vue-fontawesome#359]
I see you guys update @fortawesome/fontawesome-svg-core

but @fortawesome/vue-fontawesome@^3.0.0-5 is not update

**Comment by anburocky3** [comment]
Did you tried with `@fortawesome/vue-fontawesome@prerelease`?

**Comment by skimhugo** [comment]
this version is same with ^3.0.0-5 ？

It is ok for now, I do not know why, I just update @fortawesome/fontawesome-svg-core to latest version.

Vue component's work should work a little quickly. There are a lot pro user like me using vue.

**Comment by anburocky3** [comment]
i was using free version for my open-source, finally, get rid of it and was using svg for my projects.

**Comment by jasonlundien** [comment]
Hey @skimhugo ---

We have updated our Vue 3 and Vue 2 packages along with our [docs](https://fontawesome.com/docs/web/use-with/vue/).  You should be good to go now.  I will go ahead and close this issue.  If you feel that it needs to remain open just let me know.
