### ISSUE TITLE
Problem while using vue-fontawesome with nuxt.

### ISSUE THREAD

**Issue by SzymonLisowiec** [FortAwesome/vue-fontawesome#36]
Hello,
I found a problem while using `vue-fontawesome` with nuxt.js (SSR). The problem is that `@fortawesome/fontawesome` using DOM, but nuxt don't have DOM while server side rendering.

**Comment by OriginalEXE** [comment]
Hi,

this is a problem with `@fortawesome/fontawesome`, until this is fixed, I would recommend using older versions:

```
"@fortawesome/fontawesome": "1.0.1",
"@fortawesome/vue-fontawesome": "0.0.21",
```

**Comment by SzymonLisowiec** [comment]
@OriginalEXE ooo thanks! 😄
