### ISSUE TITLE
Documentation example do not work with Vue 3 cli

### ISSUE THREAD

**Issue by codigoisaac** [FortAwesome/vue-fontawesome#368]
The [readme](https://github.com/FortAwesome/vue-fontawesome) describes the setting up of vue-fontawesome in a way that doesn't seem to work anymore with Vue3 cli.

The Readme says: 
```
import Vue from 'vue'
import App from './App'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faUserSecret)

Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  components: { App },
  template: '<App/>'
})
```

But this generates the error:
> ReferenceError
> Vue is not defined

![Sem título](https://user-images.githubusercontent.com/37576563/166131638-8276d4e7-8954-4ddc-ae1c-2e1a1f69a706.png)

**Reproducible test case**
https://codesandbox.io/s/font-awesome-vue-docs-example-dont-work-ixgbuf?file=/src/main.js

**Additional context**
In my project, what I do for vue-fontawesome to work is
```
createApp(App).component('font-awesome-icon', FontAwesomeIcon).use(router).mount('#app')
```

**Comment by jasonlundien** [comment]
Hi @codigoisaac -- we have updated our docs for Vue 3.  You can check them out [here](https://fontawesome.com/docs/web/use-with/vue/).  I will go ahead and close this issue.  If you feel that it needs to remain open just let me know.
