### ISSUE TITLE
how to do a half-filled star?

### ISSUE THREAD

**Issue by codeofsumit** [FortAwesome/vue-fontawesome#38]
As `star-half-o` is now gone from FontAwesome 5, how can I create a half filled star? If I put two half-star from solid and regular next to each other, flip one - there is too much spacing in between them obviously.
![image](https://user-images.githubusercontent.com/2399810/34622670-4d0cdec0-f24e-11e7-9082-3624794865eb.png)

**Comment by robmadole** [comment]
Hi @codeofsumit here is an example that we've worked up for this specific thing https://codepen.io/fontawesome/pen/GyjamK

**Comment by dannosaur** [comment]
That's ridiculous. What was previously a single line of HTML has now turned into a 4-fold increase AND requires additional detection logic in code that generates the star output to know that the previous star was a half filled star, thus requiring even more HTML to complete the previous star. How was it decided that it was better this way?

**Comment by robmadole** [comment]
@dannosaur we worked with the community to come to this decision. Sorry you don't agree but this new solution is more robust and makes some things possible that were not with the old design. We opted to listen to the requests that we had for this set of icons.
