### ISSUE TITLE
What is the family abbreviation for the new sharp solid pro icons?

### ISSUE THREAD

**Issue by oberocks** [FortAwesome/vue-fontawesome#399]
I'm looking to integrate the new v6.2.0 package into my lib + installation system.

To do so, I'll need to update my lib and installer scripts (which have options for installing FA free and FA pro packages) along with this package. 

The thing is, in my implementation of the vue-fontawesome component, the lib is using the `:icon="['fas', 'user']"` syntax under the hood. I also have FontAwesome utilities for strict Vue component type/string validation, for example.

What I can't seem to find in any docs or issues/pr's though... is **what would the abbreviated string be for the new Sharp Solid icons?**

For clarity, here's the current array of FA family abbreviations from [my lib](https://github.com/obewds/vueventus/blob/main/src/validators/ValidFontAwesomeFamilies.ts) as of now:

```javascript
// ./src/validators/ValidFontAwesomeFamilies.ts

const ValidFontAwesomeFamilies = [
    'fab',
    'fad',
    'fal',
    'far',
    'fas',
    'fat',
] as const

// ...
```

So **what would the new Sharp Solid icons abbreviation be (especially considering the `fas` already in use) ?**

As a guess, is it: `fass`?

Many thanks for the work and awesome new 6.2 stuff!

Cheers 🍻 

PS - Please let me know if I need to do something on my end to this issue (especially if this should be a feature req vs a bug).

**Comment by mlwilkerson** [comment]
Hi @oberocks, `fass` should work. That's the `IconPrefix` that identifies Sharp Solid, which is a combination of family (Sharp) and style (Solid). [This shows](https://github.com/FortAwesome/Font-Awesome/blob/d3a7818c253fcbafff9ebd1d4abb2866c192e1d7/js-packages/%40fortawesome/fontawesome-common-types/index.d.ts#L2) all values that are valid as an `IconPrefix` for Font Awesome 6.2.0.

That first array element is just being [passed down as the prefix](https://github.com/FortAwesome/vue-fontawesome/blob/47e48d3cb4b84c98ce2c3bc35c30b5054bea36ed/src/components/FontAwesomeIcon.js#L26) for looking up the icon, so I expect any of these prefixes to be valid.

**Comment by oberocks** [comment]
@mlwilkerson Thank you very much, and I'm super excited to get everything wired up tomorrow morning!

Have a great evening!
