### ISSUE TITLE
How to integrate with Vue-cli & vue-router

### ISSUE THREAD

**Issue by 10yung** [FortAwesome/vue-fontawesome#41]
I try all step in your tutorial in my vue-cli project (with vue router).
I put these lines in my main.js file
```
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import faSpinner from '@fortawesome/fontawesome-free-solid/faSpinner'
fontawesome.library.add(brands, faSpinner)
```
but I cannot use <font-awesome-icon icon="spinner" /> in any of my child component.
error: component undefined.
```
// one of my child component
 components: {
    FontAwesomeIcon // this line will cause error
  }
```

I also try to register global components (in my main.js file), but I'm not sure how to create my own template
```
Vue.component('font-awesome-icon', {
	props: {
		icon
	},
	// template: `<svg><use :xlink:href="'static/icons/solid.svg#' + icon"></use></svg>`
})
```
I really need your help ~
Thank you!

**Comment by OriginalEXE** [comment]
In the file where you have
```
// one of my child component
 components: {
    FontAwesomeIcon // this line will cause error
  }
```

are you importing `FontAwesomeIcon` like this?
```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
```

If not, try that and see if you still get the problem.

**Comment by robmadole** [comment]
Thanks @OriginalEXE. @10yung if you still have problems we can re-open.

**Comment by 10yung** [comment]
Thanks! It’s actually work.
That’s my terrible mistake cuz I copy all code from app.js demo code and it
import from ‘@fontawesome/fontawesome’
Thank you!

-- 
TengYung Lin

**Comment by dflock** [comment]
Similar to #43 & #54
