### ISSUE TITLE
dont work out of the box with vue-cli webpack

### ISSUE THREAD

**Issue by stephanedemotte** [FortAwesome/vue-fontawesome#42]
conflict with `@`

```
@fortawesome/fontawesome
```
vue webpack cli search in 'src' because of alias in `build/webpack.base.conf.js`

```
...
alias: {
   ...
      '@': resolve('src'),
}
```

**Comment by OriginalEXE** [comment]
This issue should be raised in vue webpack cli repository if this is the case, as @ in front of the package name is perfectly valid and is how scoped packages work: https://docs.npmjs.com/getting-started/scoped-packages

**Comment by robmadole** [comment]
Yep, that's an issue with vue-cli if it's doing that. Closing this.
