### ISSUE TITLE
2.0.9 multiple versions leading to checksum errors

### ISSUE THREAD

**Issue by mslosarek** [FortAwesome/vue-fontawesome#425]
**Describe the bug**
Failing on npm install due to checksum failure:
```
sha512-13m3f0IJD8Ll052AmNjWBEn5TQ9okL2KaZ0rhSEdaOwe611QU+ZJ7u2suvohcNMTLCBbsexi+k9PfBmAQXPS6w== integrity checksum failed when using sha512: wanted sha512-13m3f0IJD8Ll052AmNjWBEn5TQ9okL2KaZ0rhSEdaOwe611QU+ZJ7u2suvohcNMTLCBbsexi+k9PfBmAQXPS6w== but got sha512-tUmO92PFHbLOplitjHNBVGMJm6S57vp16tBXJVPKSI/6CfjrgLycqKxEpC6f7qsOqUdoXs5nIv4HLUfrOMHzuw==
```

**Reproducible test case**
Caused by multiple versions of 2.0.9 even when using the same version of Node and NPM. One computer is a Mac, the other is an EC2 box.

**Expected behavior**
`npm install` should work with `package-lock.json`

**Comment by jasonlundien** [comment]
Hey @mslosarek ---

I am not following here.  Are saying you cannot install our Vue 2 ([2.0.9](https://www.npmjs.com/package/@fortawesome/vue-fontawesome/v/2.0.9)) component in a Vue 2 project?

**Comment by mslosarek** [comment]
Hi @jasonlundien. I am installing a project that uses vue-fontawesome as a dependency. The requirement in the dependency is `"@fortawesome/vue-fontawesome": "^2.0.2"`. On my development machine (a mac) it resolves to 1 version and the `package-lock.json` is generated. Then installing these dependencies on a AWS EC2 instance, using the same version of Node and NPM, it selects the other version and the install fails because the checksum does not match. There are 2 versions of 2.0.9 listed on npm (https://www.npmjs.com/package/@fortawesome/vue-fontawesome?activeTab=versions). This defeats the purpose of versioning, there shouldn't be 2 versions with the same number published.

**Comment by jasonlundien** [comment]
Hey @mslosarek ---

I just want to clarify:  there are not two versions of `2.0.9`, rather it is just 1 version with multiple `tags` pointing to `2.0.9`.

![Image](https://user-images.githubusercontent.com/50338269/210433562-b5727bff-6826-46d7-a216-c282844b6918.png)

- Can you check to make sure your Node version is the same on your local and EC2 ?
- If they are the same, can you check that you are not using a proxy in your package.json file ?

Just let me know what you find.

**Comment by jasonlundien** [comment]
I am going to go ahead and close this issue.
If you are still having problems let us know and we can re-open if need be.
