### ISSUE TITLE
Update latest npm tag to v3

### ISSUE THREAD

**Issue by hugoattal** [FortAwesome/vue-fontawesome#426]
**Is your feature request related to a problem? Please describe.**
Hello, I usually update packages of my repo by doing a `pnpm update --latest`. The thing is that the version with the `latest` tag of `vue-fontawesome` is the v2, and not the v3. So I have to manually revert the change every time I do this since I'm using vue3.

cf https://www.npmjs.com/package/@fortawesome/vue-fontawesome?activeTab=versions
![image](https://user-images.githubusercontent.com/4563971/210371910-29d654b8-d698-412e-baf6-067d72b69fa6.png)

**Describe the solution you'd like**
I'd like the `latest` tag to point toward the v3 version. Of course, `latest-2` and `latest-3` should point to v2 and v3.

**Describe alternatives you've considered**
Manually revert the change every time I do `pnpm update --latest`.

**Additional context**
I believe more people are using Vue3 as it has been the latest stable Vue version for a while. So I think the default `vue-fontawesome` install version should be for Vue3.

Also, the `latest` tag for the Vue package point to Vue3, Vue2 has the tag `legacy`.
cf https://www.npmjs.com/package/vue?activeTab=versions

**Comment by jasonlundien** [comment]
@hugoattal --- 

Originally `latest` was set to v2 because we had more downloads from v2.  We did this with the understanding that we would eventually change the `latest` from v2 to v3 once we saw that v3 was being used (downloaded) more than v2.

So perhaps now is the time;  I am going to check and review this with the "suits" and get back with you.

**Comment by robmadole** [comment]
Oh great. Am I a "suit" @jasonlundien ?! 😃 

Yeah let's update `latest` to point to 3. I'm in favor.

**Comment by jasonlundien** [comment]
@robmadole ---

you are definitely the "suit" I was going to ask 😀 !!!

And thank you.  The next release I will get this change implemented !!!

**Comment by jasonlundien** [comment]
New release today.   `latest` now points to our Vue 3 component.
I will go ahead and close this issue.
Let us know if anything else pops up !!!
