### ISSUE TITLE
3.x Types Issue: FontAwesomeIconProps missing values

### ISSUE THREAD

**Issue by brandon-mork** [FortAwesome/vue-fontawesome#428]
**Describe the bug**
Types in [index.d.ts FontAwesomeIconProps](https://github.com/FortAwesome/vue-fontawesome/blob/3.x/index.d.ts#L15-L20) do not match actual expected props in [FontAwesomeIcon.js](https://github.com/FortAwesome/vue-fontawesome/blob/3.x/src/components/FontAwesomeIcon.js#L80-L136).

**Expected behavior**
Exact match of supported props and associated types definition.

**Reproduction**
Unintuitive breakage due to missing types, string `"false"` evaluates to true:
<font-awesome-icon :icon="['far', 'cog']" bounce="false"></font-awesome-icon>

Functioning code to pass boolean `false` value instead of string, which consuming developer **would** know to use **if** types were present:
<font-awesome-icon :icon="['far', 'cog']" :bounce="false"></font-awesome-icon>

**Additional context**
Issue introduced by: https://github.com/FortAwesome/vue-fontawesome/pull/366
PR merged under https://github.com/FortAwesome/vue-fontawesome/issues/415 fixed one piece of the issue, but left much of the issue remaining.

**Exact diff of expected types**
```diff
+ bounce?: boolean
+ shake?: boolean
+ beat?: boolean
+ fade?: boolean
+ beatFade?: boolean
+ flash?: boolean
+ spinPulse?: boolean
+ spinReverse?: boolean
```

**Comment by jasonlundien** [comment]
@brandon-mork --- 

Oh my goodness, you are right, I missed them... somehow (I have no idea how).

I will get this PR submitted and merged as well.  Thank you !!!

**Comment by brandon-mork** [comment]
You rock- thanks @jasonlundien!! :)

**Comment by jasonlundien** [comment]
@brandon-mork ---

PR merged.  So I am going to go ahead and close this one now. Thanks again for your help.

Also, I am going to add you as a contributor unless you tell me other wise.  Have a great one !!!
