### ISSUE TITLE
Global decleration not working

### ISSUE THREAD

**Issue by TWG-Matt** [FortAwesome/vue-fontawesome#43]
Hi.  I'm not sure if I'm missing something or now.  I'm trying to declare this globally so I can use it in all of my vue template files.

In my main.js file I have the following.
```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import { faHdd } from '@forawesome/fontawesome-pro-light'

new Vue({
    computed: {
        hhd () {
            return faHdd
        }
    },
    components: { App, FontAwesomeIcon },
    router,
    store,
    template: '<App/>'
}).$mount('#app')
```

**Comment by OriginalEXE** [comment]
Hi, please check how I did it here:
https://codesandbox.io/s/n97705o5ml

**Comment by TWG-Matt** [comment]
Thanks @OriginalEXE .

**Comment by jackn3o** [comment]
@OriginalEXE need to add 1 icon by 1 icon? cannot all in?

**Comment by OriginalEXE** [comment]
@jackn3o You can load them all:
https://codesandbox.io/s/py2mym5o4j

**Comment by Xikura** [comment]
That did the trick @OriginalEXE

**Comment by robmadole** [comment]
Thanks again @OriginalEXE

**Comment by dflock** [comment]
Would be a good idea to make this explicit in the README.
