### ISSUE TITLE
ESLint cannot recognize FontAwesomeIcon import

### ISSUE THREAD

**Issue by AloisSeckar** [FortAwesome/vue-fontawesome#448]
**Describe the bug**
Using ESLint with [Nuxt config](https://github.com/nuxt/eslint-config) in Nuxt 3 project I am getting violation of [import/named](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/named.md) rule from 
`import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'`

I am using the latest `@fortawesome/vue-fontawesome`. The import I copied [from the docs](https://fontawesome.com/docs/web/use-with/vue/add-icons) and also it works correctly when applied. But the linting error is tedious.

**Reproducible test case**
[GitHub repo](https://github.com/AloisSeckar/demos-nuxt/tree/main/nuxt-fa) where I encountered it. It is part of a larger project, but with separate `package.json`

At the moment, I covered the issue up by a setting inside `.eslintrc.json`
```
"settings": {
  "import/ignore": [
    "*vue-fontawesome*"
  ]
}
```
So the import is not checked and the error is not raising.

**Expected behavior**
Since the import is technically valid, there shouldn't be a clash with ESLint rules.

**Desktop (please complete the following information):**
 - Happening inside VS Code 1.75.1 with ESLint plugin 2.4.0
 - Node 18.14, Nuxt 3.2.0, vue-fontawesome 3.0.3

**Additional context**
Opened [on request](https://github.com/FortAwesome/Font-Awesome/discussions/19557).

**Comment by smujaddid** [comment]
Any follow up on this issue? It is weird bug

**Comment by ykkwfreelance** [comment]
It seems to be just a mistake in the type definition. By ignoring it as shown below, you should be able to use it

```typescript
// eslint-disable-next-line import/named
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome"
```

**Comment by wagslane** [comment]
I'm getting the same bug

**Comment by AloisSeckar** [comment]
It looks like it got solved over the time. Eslint is now happy with it as it is.

My current dependencies:

```
"devDependencies": {
    "@fortawesome/fontawesome-svg-core": "6.5.1",
    "@fortawesome/free-solid-svg-icons": "6.5.1",
    "@fortawesome/vue-fontawesome": "3.0.6",
    "@nuxtjs/eslint-config-typescript": "12.1.0",
    "eslint": "8.57.0",
    "nuxt": "3.10.3"
}
```

**Comment by jasonlundien** [comment]
Ok cool, whew ;) .... closing for now!

If this pops up again just let us know !!!

Thank you,
-jason
