### ISSUE TITLE
Computed property "title" is already defined in Props.

### ISSUE THREAD

**Issue by roelVerdonschot** [FortAwesome/vue-fontawesome#449]
**Describe the bug**
I'm getting the Vue warning: Computed property "title" is already defined in Props.

**Desktop (please complete the following information):**
"@fortawesome/vue-fontawesome": "^3.0.3",
 "vue": "^3.2.0",
"vite": "^4.0.0",
<img width="558" alt="Scherm­afbeelding 2023-02-22 om 11 42 20" src="https://user-images.githubusercontent.com/8642074/220597054-474a56b0-3d29-487e-9192-b615e85ddcff.png">

**Comment by jasonlundien** [comment]
@roelVerdonschot ---

Do you have a reproducible test case we can look?

**Comment by TomDeSmet** [comment]
I have this issue as well. But I have no idea what is causing it.
I'm using:

"vue": "^3.4.21",
"vite": "^5.1.6",
"@vitejs/plugin-legacy": "^5.3.0",
"@vitejs/plugin-vue": "^5.0.4",
"@fortawesome/fontawesome-free-regular": "^5.0.13",
"@fortawesome/fontawesome-svg-core": "^6.5.2",
"@fortawesome/free-solid-svg-icons": "^6.5.2",
"@fortawesome/vue-fontawesome": "^3.0.6",

Making a reproducable test case is not easy to di I fear.

**Comment by jasonlundien** [comment]
@TomDeSmet ---

Is there a repo or test repo you could share that has this warning ?

**Comment by TomDeSmet** [comment]
Unfortunately no, it's in a large codebase with strict security. I'll try to do some tests and figure out as much as possible.

**Comment by TomDeSmet** [comment]
I cannot reproduce it in sandbox mode and I have no idea when it actually triggers. The Vue warning is not very clear on that.

But it looks to me like it only happens in Vite dev mode. I can't reproduce it after a build and running  Vite preview.
It seems to trigger whenever I make a change in some codebase that uses `<font-awesome-icon>` that makes Vite reload its HMR and then the shit hits the fan for some reason.
