### ISSUE TITLE
[Proposal] Improved icon and prefix API

### ISSUE THREAD

**Issue by Morgul** [FortAwesome/vue-fontawesome#47]
I'l like to propose two extensions of the API:

```html
<!-- Improved String API -->
<font-awesome-icon icon="far spinner" />

<!-- Prefix API -->
<font-awesome-icon prefix="far" icon="spinner" />
```

I personally find the space separated classes much closer to the `<i class="far fa-spinner"></i>` syntax, and is just a bit cleaner than the array syntax. (Doing `icon.split(" ")` to generate the array shouldn't be prohibitive, I think.)

The `prefix` prop is just a little more in line with other vue component libraries; I figured while we're adjusting the API, why not add it?

Of course, these changes should be backwards compatible. If you guys like them, I'll totally do the merge request; should be pretty simple.

**Comment by robmadole** [comment]
@Morgul sorry but we've thought this through and have rejected both of those ideas.

**Comment by gilles-crealp** [comment]
Can you provide an explanation on why you reject the more clear and logical way of doing with the `prefix` prop (`<font-awesome-icon prefix="far" icon="spinner" />`)?

Moreover if @Morgul propose to merge it…

**Comment by robmadole** [comment]
See #18

**Comment by gilles-crealp** [comment]
Thank you!
