### ISSUE TITLE
How to use plugin alongside with kits

### ISSUE THREAD

**Issue by arsenitem** [FortAwesome/vue-fontawesome#474]
I am using fontawesome plugin for icons in my vue3 app, but recently i discovered fontawesome kits and tryed to use them
with js embed code <script src="https://kit.fontawesome.com/xxxx.js" crossorigin="anonymous"></script>

Unfortunately emded code breaks the behaviour of plugin, seems like a styles conflict

Are there any ways to get around this problem, or use kits inside plugin?

**Comment by inkbeard** [comment]
Did you find anything out about this? I'm having some similar issues.
