### ISSUE TITLE
Strange rendering issue

### ISSUE THREAD

**Issue by tomirons** [FortAwesome/vue-fontawesome#48]
I'm not getting any errors when this happens, but after the **first** icon renders, nothing else will render on the page.

Here's an example of how I have everything setup. I'm using webpack in this instance.

App.js:
```
window.Vue = require('vue');

import fontawesome  from '@fortawesome/fontawesome';
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
import falight from '@fortawesome/fontawesome-pro-light';
import fabrands from '@fortawesome/fontawesome-free-brands';

fontawesome.library.add(falight, fabrands);

Vue.component('font-awesome-icon', FontAwesomeIcon);

const app = new Vue({
    el: '#app',
});
```

HTML:
```
<div id="app">
        Foo
        <font-awesome-icon :icon="['fal', 'clipboard']" />
        Bar
</div>
```
The output of this will show "Foo" and then the icon, but "Bar" is never to be seen. However, it does flash before the icon gets rendered.

Has anyone else had this issue or have any suggestions?

**Comment by robmadole** [comment]
Can you post an example that reproduces this?

I tried here: https://codesandbox.io/s/w7wrvy6mm7

**Comment by robmadole** [comment]
This might be relate https://github.com/vuejs/vue/issues/1036

**Comment by tomirons** [comment]
It might be the way we're doing it, you do it via component and I was doing it via a blade (laravel) file. If I close the component in blade it works just fine.

Is the reason cause I was using HTML5 and there is no self closing tags?

**Comment by OriginalEXE** [comment]
Check this out: https://github.com/FortAwesome/vue-fontawesome/issues/37#issuecomment-360919419
