### ISSUE TITLE
Unique ID generated when using a "title" breaks SSR

### ISSUE THREAD

**Issue by sei-jdshimkoski** [FortAwesome/vue-fontawesome#491]
**Describe the bug**
When a title attribute is added to an icon, `FontAwesomeIcon` generates a unique ID... unfortunately, this unique ID does not work in an SSR environment. The ID is different on the server and the client.

**Reproducible test case**
```
<FontAwesomeIcon icon="user" title="User" />
```

**Expected behavior**
The unique ID should be the same on the server and the client.

**Desktop (please complete the following information):**
 - Microsoft Edge
 - 120.0.2210.121 (Official build) (arm64)

**Additional context**
You can see this repo for an example on how to create SSR-friendly unique IDs: https://github.com/shimyshack/uid

**Comment by robmadole** [comment]
@sei-jdshimkoski this is not documented well but you can set props `titleId` and `maskId` to prevent these from being auto-generated. Give that a try and let us know if that doesn't work.
