### ISSUE TITLE
Set a prefix default

### ISSUE THREAD

**Issue by erikrorstrom** [FortAwesome/vue-fontawesome#50]
Would be great if you could globally set the prefix default for the project. The same way you add libraries:

```
import fontawesome from '@fortawesome/fontawesome'
fontawesome.library.add(brands, faSpinner)
```
Something like:
```
import fontawesome from '@fortawesome/fontawesome'
fontawesome.setPrefix('fal');
```

**Comment by ralphwilliams** [comment]
Would love to see this as an option!

**Comment by carestad** [comment]
Would love this.

When adding separate icons to the library (with `library.add()`), the prefix is already present, so why can't the component figure out itself when I write

```vue
<font-awesome-icon icon="clock" />
```

That this is in fact

```vue
<font-awesome-icon :icon="['fal', 'clock']" />
```

I can see that this could be an issue if I imported the `clock` from both `fal` and `fas`, but how often will that be the case?

**Comment by christhofer** [comment]
Any plan to implement this simple request??

Have been 2 years since this issue was created, but no official response from Vue FontAwesome team.

> I can see that this could be an issue if I imported the `clock` from both `fal` and `fas`, but how often will that be the case?

Then just make it back to default `fas` or whatever user set as default prefix.

Should be something like this, no? I don't know how to add the test though, maybe someone will make pull request with this.

components/FontAwesomeIcon.js
```js
let prefix = 'fas'

function setPrefix(_prefix) {
  prefix = _prefix
}

function normalizeIconArgs (icon) {
  if (icon === null) {
    return null
  }

  if (typeof icon === 'object' && icon.prefix && icon.iconName) {
    return icon
  }

  if (Array.isArray(icon) && icon.length === 2) {
    return { prefix: icon[0], iconName: icon[1] }
  }

  if (typeof icon === 'string') {
    return { prefix, iconName: icon } // use default prefix instead of hard code
  }
}

export default {
  // ...

  setPrefix,
}
```

so we can use it

```js
import Vue from 'vue'
import { FontAwesomeIcon, FontAwesomeLayers, FontAwesomeLayersText } from '@fortawesome/vue-fontawesome'

import { faEgg } from '@fortawesome/pro-regular-svg-icons'
library.add(faEgg)

FontAwesomeIcon.setPrefix('far')

Vue.component('fa-icon', FontAwesomeIcon)
Vue.component('fa-layers', FontAwesomeLayers)
Vue.component('fa-layers-text', FontAwesomeLayersText)
```

**Comment by jasonlundien** [comment]
Hey there,

After [importing your icons](https://fontawesome.com/docs/web/use-with/vue/add-icons), you can set the default style by inserting the following code in your `main.js` or `main.ts` file:

```
// import config so we can set a default style
import { config } from '@fortawesome/fontawesome-svg-core'
config.styleDefault = 'fad'
```

Then you can call icons like:
`<font-awesome-icon icon="coffee" size="3x" />`


*** this would pop in a duotone coffee icon being that I set the default to duotone.

More on the topic of defaults:
- [Style default](https://fontawesome.com/v6/docs/apis/javascript/configuration#styledefault)
- [Family default (currently would on be Sharp)](https://fontawesome.com/v6/docs/apis/javascript/configuration#familydefault)
