### ISSUE TITLE
Add a dist folder with prebuilt source

### ISSUE THREAD

**Issue by adam-buckley** [FortAwesome/vue-fontawesome#53]
Hello,

If possible, could you please add a dist folder with everything already built? I'm using Vue and Font Awesome in our framework and just discovered the two don't play too nice together. I'd love to use this library but would prefer not to introduce (yet) another build tool.

Ideally, I would like to be able to include a "vue-fontawesome.min.js" onto pages (just like with the base Font Awesome library) that need it and then use the _font-awesome-icon_ components from there.

If this isn't possible that's OK, thank you for your time.

**Comment by robmadole** [comment]
We don't use a `dist` folder but we can include the `index.js` and `index.es.js` in the root (where the `package.json` is expecting them). We'll get this on the list.

**Comment by jasonlundien** [comment]
Closing this issue as both the `index.js` and the `index.es.js` are in the root with the `package.json`.
