### ISSUE TITLE
Problem with use global?

### ISSUE THREAD

**Issue by thearabbit** [FortAwesome/vue-fontawesome#54]
```
// app.js
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
import fontawesome from '@fortawesome/fontawesome';
import solid from '@fortawesome/fontawesome-free-solid';
import regular from '@fortawesome/fontawesome-free-regular';
import brands from '@fortawesome/fontawesome-free-brands';

fontawesome.library.add(solid, regular, brands);
Vue.use(FontAwesomeIcon);
--------------
// home.vue
<font-awesome-icon :icon="['fab', 'font-awesome']"/>
```

![image](https://user-images.githubusercontent.com/4495160/36009981-91be2a6c-0d81-11e8-87a7-73cf5e9452df.png)

**Comment by dflock** [comment]
There's a way to make this work over here: https://github.com/FortAwesome/vue-fontawesome/issues/43

Basically, do this in your top level "app" component - `home.vue`, in your case:

```js
import Vue from 'vue'
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
Vue.component('font-awesome-icon', FontAwesomeIcon)
```

I would have preferred to do this in app.js too, but I couldn't make it work that way.

**Comment by robmadole** [comment]
You can do this in your `app.js`. Post an example of the error you are getting if this is still an issue.

**Comment by thearabbit** [comment]
Thanks I will try.
