### ISSUE TITLE
Improve documentation for getting started

### ISSUE THREAD

**Issue by sscholle** [FortAwesome/vue-fontawesome#57]
```
<font-awesome-icon :icon="['fab', 'font-awesome']" />
```

```
  import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
  export default {
    components: {
      FontAwesomeIcon
    }
}
```

ERROR: 
```
VM31702 index.js:476 Check not find one or more icon(s) 
{prefix: "fab", iconName: "font-awesome"}
iconName
:
"font-awesome"
prefix
:
"fab"
```

**Comment by robmadole** [comment]
Have you added the icon to the `fontawesome.library`?

**Comment by akinhwan** [comment]
@robmadole like this? Below is my main.js file in my vue-cli init webpack template project

`import Vue from 'vue'
import App from './App'
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import { faSpinner } from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(brands, faSpinner );

Vue.config.productionTip = false

new Vue({
  el: '#app',
  components: { App },
  template: '<App/>'
})`

**Comment by akinhwan** [comment]
I think the documentation on the npm package page could be clearer. I particularly had issues understanding the latter portion where it explains library configuration. I followed the code exactly and it has not worked as the "basics" portion has for me.

"It can be tedious to always import the icons individually so a library can be configured and shorthand can be used when rendering the icon.

Define a library that can be used without explicit imports:"

**Comment by robmadole** [comment]
Agreed, this needs to be improved.

**Comment by tophat1986** [comment]
The guide doesn't highlight for some reason that you also have to also install via NPM the - 

` npm install --save @fortawesome/fontawesome-free-solid `
` npm install --save @fortawesome/fontawesome-free-brands`

Because the import examples need to import it.  I know it's simple to overcome but I find it odd and inconsistent.

**Comment by dysol** [comment]
So how can i _vue.use('fontawesome')_ in my main.js like other plugins? I followed the documentation, however i still have to **import** FontAwesomeIcon in **all** the components that i want to use icons. 

Is there a cleaner way?

**Comment by robmadole** [comment]
@dysol this package is not a plugin (it would need to have an `install` hook for that). It's just a component.

In you `App.js` or similar place you can register a component `Vue.component('font-awesome-icon', FontAwesomeIcon)` and then use it everywhere in your app.

**Comment by paulers** [comment]
I spent 30 minutes trying to get this to work, no dice. I have these packages installed:
```javascript
@fortawesome/vue-fontawesome
@fortawesome/fontawesome
@fortawesome/fontawesome-free-solid
```
In my app.js I have the following:
```javascript
import Vue from 'vue';
import App from './components/App.vue';
import FontAwesomeIcon from '@fortawesome/vue-fontawesome';
import fontawesome from '@fortawesome/fontawesome';
import * as solid from '@fortawesome/fontawesome-free-solid';
fontawesome.library.add(solid);

const app = new Vue({
    el: '#app',
    render: h => h(App)
});
Vue.component('font-awesome-icon', FontAwesomeIcon)
```
Then in my components I'm using it like this:
```html
<font-awesome-icon :icon="['fas', 'faCog']" />
```
It's not throwing an exception about the component not being found or imported correctly, but I can't get the icon to render. I've tried several different ways to import the solid and also different bindings inside the element itself... at a loss now.

**Comment by robmadole** [comment]
@paulers try `<font-awesome-icon :icon="['fas', 'cog']" />`. The lookup syntax is different than imports.

**Comment by paulers** [comment]
That worked, thanks! I also had to change ``import * as solid from '@fortawesome/fontawesome-free-solid';`` to ``import solid from '@fortawesome/fontawesome-free-solid';``

**Comment by VicoErv** [comment]
any idea with vue-cli guys?
```
import Vue from 'vue'
import Router from 'vue-router'
import Home from '@/components/Home'

import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import fontawesome from '@fortawesome/fontawesome'
import { faTwitter, faInstagram } from '@fortawesome/fontawesome-free-brands'

fontawesome.library.add(faInstagram, faTwitter)
Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }
  ]
})
```
sorry i'm beginner

**Comment by robmadole** [comment]
Looks pretty solid @VicoErv. Are you getting an error?

**Comment by VicoErv** [comment]
same as above `index.js:476 Check not find one or more icon(s)`, even i import it on .vue file. will try latter what happen if i assign `faTwitter` or `faInstagram` to `this.$data`

**Comment by robmadole** [comment]
Let's see the rest of your code @VicoErv . If you can create a codesandbox.io or similar that would be the best way we could help you.

**Comment by robmadole** [comment]
@xeroxstar make sure you add the icon to your library before you attempt to use it.

```javascript
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import fontawesome from '@fortawesome/fontawesome'
import faSpinner from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(faSpinner)

export default {
  name: 'App',
  components:{FontAwesomeIcon},
}

<template>
  <div id="app"><font-awesome-icon icon="spinner" /></div>
</template>
```

**Comment by shershen08** [comment]
I am really lost... it was a simple thing - an icon, piece of picture ... why doing all all this hell of complicated a mess out of it - https://fontawesome.com/how-to-use/use-with-node-js ?
surprisingly it doesnt' work  
<img width="573" alt="screen shot 2018-05-09 at 21 44 43" src="https://user-images.githubusercontent.com/1363772/39836086-8af2e9f6-53d2-11e8-80ca-796da8892e46.png">

**Comment by Aterr** [comment]
Same problem here.
Trying to add facebook icon with:
`:icon="['fab', 'facebook']"`

And what I get is: 
`Could not find one or more icon(s)` error.

Please hulp

**Comment by robmadole** [comment]
@Aterr you need to add the Facebook icon to your library:

```javascript
import { library } from '@fortawesome/fontawesome-svg-core'
import { faFacebook } from '@fortawesome/free-brands-svg-icons'

library.add(faFacebook)
```

**Comment by rSammy** [comment]
Just do this 

```
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
library.add(fas)
```

**Comment by rSammy** [comment]
Now you can do `<font-awesome-icon icon="whatEverIcon" />`

**Comment by thanhtruong1992** [comment]
> Just do this
> 
> ```
> import { library } from '@fortawesome/fontawesome-svg-core'
> import { fas } from '@fortawesome/free-solid-svg-icons'
> import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
> library.add(fas)
> ```

Thanks. I try it and working

**Comment by avilesasturias** [comment]
@robmadole Quick question, if you would like to use all free icons, for let's say an icon picker, do you manually need to import each of the icons to library? or is there a better way to achieve this?
Thanks.

**Comment by vienpt** [comment]
Nuxt application

1. npm install

```
@fortawesome/fontawesome-svg-core
@fortawesome/free-brands-svg-icons
@fortawesome/free-regular-svg-icons
@fortawesome/free-solid-svg-icons
@fortawesome/vue-fontawesome
```

2. Create /plugin/font-awsome.js

- should change import { <prefix> }
**prefix** should be the same fontawsome icon: solid -> `fas`; brand -> `fab`

```
import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(fas, fab)

Vue.component('font-awesome-icon', FontAwesomeIcon)

Vue.config.productionTip = false
```

3. Set plugin in `nuxt.config.js`

```
plugins: [{ src: '~/plugins/font-awesome' }]
```

4. Use in `.vue`

```
<font-awesome-icon icon="search" />
```
