### ISSUE TITLE
@fortawesome/fontawesome VS @fortawesome/vue-fontawesome VS vue-awesome ???

### ISSUE THREAD

**Issue by akinhwan** [FortAwesome/vue-fontawesome#58]
What are the differences between these three packages?
I am developing in Vue JS, but feel as though the normal fontawesome package would work as well apart from some minor conveniences? 
Thanks for your explanation FortAwesome!

**Comment by robmadole** [comment]
You'll want to use `@fortawesome/vue-fontawesome`. All of the official packages are going to have the `@fortawesome` scope. Anything else you find out there (like vue-fontawesome) is going to be from the community.
