### ISSUE TITLE
How do we implement vue-fontawesome with nuxt js app?

### ISSUE THREAD

**Issue by rlam3** [FortAwesome/vue-fontawesome#59]
Hi, i was wondering how do we implement vue-font-awesome with nuxt js app?

I've tried working with the following module https://github.com/vaso2/nuxt-fontawesome which has dependencies on this source code but I seem to keep getting the following error...for a nuxt js app. 

<img width="908" alt="screen shot 2018-02-18 at 8 03 17 am" src="https://user-images.githubusercontent.com/1154044/36352676-3796a25a-1482-11e8-8094-e22424b4b9a7.png">

Was wondering if there was something else that needs to be imported correctly to get this to work? Thanks!

**Comment by OriginalEXE** [comment]
Hi, check out this comment: https://github.com/FortAwesome/vue-fontawesome/issues/14#issuecomment-351474573

**Comment by angelsagredo** [comment]
@OriginalEXE not worked for me

**Comment by robmadole** [comment]
New section in the docs added: https://github.com/FortAwesome/vue-fontawesome#integrating-with-other-tools-and-frameworks
