### ISSUE TITLE
Using vue-fontawesome in Laravel without explicit imports

### ISSUE THREAD

**Issue by rafailml** [FortAwesome/vue-fontawesome#62]
HI,
I'm following the manual and I'm trying go use vue-fontawesome in Laravel without explicit imports.
In my app.js I have:

```
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import fontawesome from '@fortawesome/fontawesome'
import faSpinner from '@fortawesome/fontawesome-free-solid/faSpinner'

fontawesome.library.add( faSpinner)
```

Then in my component I have:
```
components: {
            FontAwesomeIcon,
        },
```
But I'm getting error in console:

> Uncaught ReferenceError: FontAwesomeIcon is not defined

If I put 

> import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

 in my component it works.

What I'm doing wrong?

**Comment by OriginalEXE** [comment]
You're not doing anything wrong, that's exactly how it should work. If you don't import it (which results in FontAwesomeIcon not being defined in the component scope), you will get the undefined error.

You can define it as a child component in your top-level component (the one that holds all other components/views), so by only importing it there and passing it to the `components` prop, you get to use it in all your other components.

**Comment by rafailml** [comment]
But then why should I put anything in app.js?
It works with only:
`import FontAwesomeIcon from '@fortawesome/vue-fontawesome'`
in my component.

**Comment by OriginalEXE** [comment]
Yes, that is enough, `import FontAwesomeIcon from '@fortawesome/vue-fontawesome'`1 in app.js does nothing in your example as you are not using it.

**Comment by rafailml** [comment]
Thanks!

**Comment by kojoYeboah53i** [comment]
HI, I'm having trouble using `FontAwesomeIcon` in my laravel application. I keep getting the some error no matter what I do " Can't resolve '@fortawesome/free-solid-svg-icons'" I followed the manual exactly yet to no avail

`import Vue from 'vue'
import App from './vue/app'

import { library } from '@fortawesome/fontawesome-svg-core'
import { faPlusSquare, faTrash } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faPlusSquare, faTrash)

Vue.component('font-awesome-icon', FontAwesomeIcon)

const app = new Vue({
    el: '#app',
    components : { App }
});


`

and in my component I have
`<template>
    <div class="addItem">
       <input type="text"/>
       <font-awesome-icon 
       icon="plus-square" />
    </div>
</template>

<script>
export default{
components: {
    FontAwesomeIcon,
}

}
</script>`

What AM I doing wrong
