### ISSUE TITLE
Title property not working. 

### ISSUE THREAD

**Issue by jmadda** [FortAwesome/vue-fontawesome#63]
When a title is added to a font-awesome-icon component its being rendered as title="my_title" on the svg element, which does not work, at least not in chrome.

Seems that is needs to be added as child element of the svg, as <title>my_title</title>

**Comment by robmadole** [comment]
Hi @jmadda this is a known issue and we have it on the list to be worked on. Thanks for reporting and we'll let you know when it's fixed.

**Comment by jacobg** [comment]
Is this for the tooltip when hovering?
https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility

Is there an ETA on this?

**Comment by ricardokojo** [comment]
I was working on accessibility on a website and we use FontAwesome icons to show our social media links.
Having `title` property to work properly would make things much easier.

**Comment by Magenta94** [comment]
This bug seems that it doesn't allow to set the tooltip on the font awesome html tag..

**Comment by lggwettmann** [comment]
Hmm, its two years later and still not solved? Any chance on a fix soon? :)

**Comment by larserikfinholt** [comment]
I get the following error when trying to set the title: `Error in nextTick: "TypeError: Cannot create property 'isRootInsert' on string 'Not InService'"` when setting title like this:

```
<font-awesome-icon icon="exclamation"  v-if="booking.groupId==4" title="Not InService" />
```
Same issue?

**Comment by Escarnope** [comment]
Over three years later, still not fixed lmao

How long is that list of things to fix?

**Comment by jacobg** [comment]
Seems to work now in font awesome version 6.
