### ISSUE TITLE
Feedback: Unable to build vue-fontawesome due to babel error

### ISSUE THREAD

**Issue by Itee** [FortAwesome/vue-fontawesome#64]
Hello, and thanks for the work but...

When building my app using: `import FontAwesomeIcon from '@fortawesome/vue-fontawesome'`, i got a babel error: 

> [!] (babel plugin) Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\...!...\\node_modules\\@fortawesome\\vue-fontawesome\\src"

Inside `/node_modules/@fortawesome/vue-fontawesome` i was unable to find the `index.es.js` nor any node_modules local to this package.

To fix it i needed to run `npm install` inside the package to get correct dependencies, then use `rollup -c` to build it !

Did you forget the build ?

Next, i got: 

> Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

So apparently, the probleme come from that you're using deprecated stuff from babel a.k.a `babel-preset-es2015` 

The npm warning about it during `npm install --save-dev babel-preset-es2015:` 

> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

I use babel-preset-env.

So i change my babel conf to use es2015 and stage-3 but still got error:

>  It looks like your Babel configuration specifies a module transformer

Finally, i found the fix using: `exclude: 'node_modules/**'` in my babel config.

Best regards

**Comment by robmadole** [comment]
We do need to upgrade this to use `babel-preset-env` but that is not going to prevent you from using this project.

@Itee @jety91 why are you building this project to begin with? We have ES5 CommonJS and an ES6 module bundled as part of this package. Are you having issues using those?

**Comment by jety91** [comment]
I don't use those in my project. I use the babel-preset-env package only. Here is my .babelrc file:
```
cacheDirectory: true,
presets: [
    [
        "env",
        {
            modules: false,
            useBuiltIns: true,
            targets: {
                browsers: [........],
                uglify: true
            }
        }
    ]
],
plugins: [
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    [
        "transform-runtime",
        {
            polyfill: false,
            helpers: false
        }
    ]
]
```

When I try to compile my project with this package:
```
(babel plugin) Error: Couldn't find preset "es2015" relative to directory
".....\node_modules\@FortAwesome\vue-fontawesome\src"
```

I followed @Itee instructions, and the error message gone, when I install the package dependencies on the ".....\node_modules\@FortAwesome\vue-fontawesome" folder.

So I think, you should use the babel-preset-env package in this project. See: [https://github.com/cleverbeagle/pup/issues/60](here)

**Comment by robmadole** [comment]
@jety91 why aren't you using the pre-compiled ES6 module or CommonJS package?

**Comment by robmadole** [comment]
Ok, closing as this project is not currently setup to support compiling the source code into other projects.
