### ISSUE TITLE
Combine power-transforms

### ISSUE THREAD

**Issue by attx** [FortAwesome/vue-fontawesome#66]
current possibilities:
```html
<font-awesome-icon icon="spinner" transform="shrink-6 left-4" />
<font-awesome-icon icon="spinner" :transform="{ rotate: 42 }" />
<font-awesome-icon icon="spinner" :transform="{ rotate: 42, size: 25 }" />
```

desired possibility:
```html
<font-awesome-icon icon="spinner" :transform="{ shrink: 6, left: 4, rotate: 42, size: 25 }" />
or ..
<font-awesome-icon icon="spinner" :transform="shrink-6 left-4 rotate-42 size-25" />
```

**Comment by robmadole** [comment]
Does this help to explain this @attx ?

https://fontawesome.com/how-to-use/font-awesome-api#parse-transform

**Comment by attx** [comment]
Sorry 🙄

**Comment by s0By** [comment]
It's really disturbing that I can't do 
`:transform="{shrink: 6}"`
My icon data comes from server so I have to render icons by its properties, can't hardcore. 
Is there a fix coming for this?
