### ISSUE TITLE
CSP/SRI-compliance under vue.js

### ISSUE THREAD

**Issue by Scrayos** [FortAwesome/vue-fontawesome#67]
Hey,

I use the vue-fontawesome-module like this:
```javascript
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import { faUser, faUserPlus } from '@fortawesome/fontawesome-pro-solid'

export default {
  name: 'App',

  computed: {
    userIcon () {
      return faUser
    },
    userPlusIcon () {
      return faUserPlus
    }
  },

  components: {
    FontAwesomeIcon
  }
}
```
(as suggested by the documentation).

I am however, deploying a strong CSP, that enforces style-src to only be from 'self' and not of type 'inline'. My approach seems to inject the CSS into the head (inline) which is blocked by my CSP. I confirmed this ot the official fontawesome website: https://fontawesome.com/how-to-use/performance-and-security#content-security-policy

The error is: "Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' ". Either the 'unsafe-inline' keyword, a hash ('sha256-BRawPKd7hltOCz24YgrQwTT/e3nTnPX14QPC8ElDJlU='), or a nonce ('nonce-...') is required to enable inline execution."

I wonder how I'd achieve the same thing with the vue-fontawesome-module. I am using webpack, if that is relevant.

Thanks in Advance!

**Comment by robmadole** [comment]
@Scrayos have you disabled the automatic addition of CSS into the `<head>`?

You can do that with:

```javascript
FontAwesomeConfig = { autoAddCss: false }
```

**Comment by Scrayos** [comment]
Yeah. Seems to have no effect, unfortunately. :(

**Comment by Scrayos** [comment]
I'm sorry, I am pretty new to vue.js and completely overlooked, that it had to be added to the head/that vue.js-scripts aren't injected into the head. The CSP-warning is gone now.

I'm either overlooking a more elegant/sophisticated way, or I specifically have to add a static script to the index.html however. I dislike having static assets in the index.html, while everything else is injected dynamically during build-process. So if there's a better way to achieve this, please let me know.

The other part - that still stops me from being able to use it - is where to obtain `/static/vendors/fontawesome/css/fa-svg-with-js.css` from, as it was mentioned in the docs. And how would I best import this script/do I have to specify it statically aswell?

Sorry for bothering with those questions, but I guess a new documentation section about vue.js + CSP would be really neat and would certainly help people like me.

Thank you very much in advance!

**Comment by robmadole** [comment]
@Scrayos the CSS file will be in `node_modules/@fortawesome/fontawesome`.
