### ISSUE TITLE
Using fontawesome more then doubles CPU usage with webpack-dev-server

### ISSUE THREAD

**Issue by ymhr** [FortAwesome/vue-fontawesome#69]
We are trying to use FA 5 pro in a project, and we're noticing that our CPU usage is more than doubling when our project imports fontawesome. It's going to (according to the MacOS activity monitor) 140%, which I think means nearly 1.5 cores total used, which is _huge_.

We're not using tree shaking currently, but are importing all icons. However, I have done a test with importing 1 single icon, and my CPU jumps from 50% with no icons, to 80% with just 1 icon. Has anyone else experienced this issue?

**Comment by robmadole** [comment]
Do you have a reproducible test case @ymhr ?

**Comment by ymhr** [comment]
I cannot seem to recreate the issue in a new repo, so it's possible there's something wrong with our main repo's webpack config I suppose.

**Comment by robmadole** [comment]
Would be happy to re-open if you can help us reproduce (we just don't have anywhere we can look until we can see this happening ourselves).

**Comment by ymhr** [comment]
Thanks @robmadole, I understand. I'll come back when I have more information.

**Comment by aiventimptner** [comment]
I can confirm increased CPU usage with my nuxt project. For testing purpose I created a fresh install with `npx create-nuxt-app` and only installed vue-fontawesome, fontawesome-svg-core & free-solid-svg-icons.

Normally i ran with 15% CPU usage, with FontAwesome enabled it's increased to 25%. Changing free-solid to pro-solid icon set CPU goes up to 35%. TreeShaking doesn't helps at all. Importing only 1 icon with pro-pack CPU is at 30%, adding more icons increasing cpu incrementally.

For my personal project with multipe icon sets (pro-solid, pro-regular, pro-light & brands) and using treeshaking for round about 30 icons the CPU is up at 70-80%. For development purpose I will now only use free-solid-svg-icons.

**Comment by MikeyAlder** [comment]
I am also having this issue in a Quasar application. Importing icons jumps the CPU up to 250% for node.

**Comment by hawkeye64** [comment]
I am also having same issue

**Comment by robmadole** [comment]
@aiventimptner @MikeyAlder @hawkeye64 can you create a reproducible test case so we can see it locally? Has anyone reported this to the webpack folks?
