### ISSUE TITLE
Dont work with webpack UglifyJs

### ISSUE THREAD

**Issue by academici** [FortAwesome/vue-fontawesome#7]
ERROR in static/js/vendor.f26255b01e687de9902c.js from UglifyJs
Unexpected token: name (isLastCharLower) [./~/@fortawesome/vue-fontawesome/index.js:12,0][static/js/vendor.f26255b01e687de9902c.js:15618,5]

**Comment by designbyadrian** [comment]
I'm getting the same problem with uglifyjs using Browserify.

**Comment by robmadole** [comment]
This should be fixed with 0.0.16. But be warned we changed the API a bit. Check the README :smile:
