### ISSUE TITLE
Documentation pro node tutorial does not work properly

### ISSUE THREAD

**Issue by tadeucaldas** [FortAwesome/vue-fontawesome#70]
Hey guys.. i don´t really know if this is happening for everyone else, but on the documentation site, the part that describes the steps to use pro version with npm may need a little change..

The documentation says that to registry token globally is like this

$ npm config set @fortawesome:registry https://npm.fontawesome.com/token

I tried that, and is did not work.. i had to put an equals sign (=) there to work..

$ npm config set @fortawesome:registry=https://npm.fontawesome.com/token

Dont really know if that an issue, but there it is!

Keep up the great work!

**Comment by robmadole** [comment]
@tadeucaldas are you on Windows?

**Comment by robmadole** [comment]
And are you using Power Shell?

**Comment by tadeucaldas** [comment]
Windows yes..

About powershell i dont really remenber becouse i was using the terminal inside visual code.. so it could be powershell

**Comment by robmadole** [comment]
There is an [issue with npm](https://github.com/npm/npm/issues/19693) that prevents correct configuration with PowerShell. We'll work on getting the documentation updated with the workaround.

**Comment by robmadole** [comment]
Ok, I think we have some documentation that we can add that will help with this. Thanks for reporting @tadeucaldas
