### ISSUE TITLE
icon binding to string doesn't work

### ISSUE THREAD

**Issue by netleader** [FortAwesome/vue-fontawesome#73]
`<font-awesome-icon class="icon" :icon="{ 'lock' : team.isPrivate, 'lock-open': !team.isPrivate }" />`

This should be self explanatory.

**Comment by robmadole** [comment]
@netleader this does not work like `class` does. We do not pull the keys off the object and look to see which is truthy. Check the docs again and if you are still having trouble let us know and we'll re-open this.

**Comment by alyatek** [comment]
Thanks for the solution!
