### ISSUE TITLE
Error: <svg> attribute transform: Expected transform function, "grow-20".

### ISSUE THREAD

**Issue by sleewoo** [FortAwesome/vue-fontawesome#76]
Transforms works as expected but getting errors like these in console:

<img width="531" alt="screen shot 2018-04-12 at 10 40 20 am" src="https://user-images.githubusercontent.com/9264860/38662767-fe854e22-3e3d-11e8-920c-a803488dd818.png">

Here is my code:

```html
<icon-layer>
  <icon icon="folder" transform="grow-20"></icon>
  <icon icon="plus" transform="down-2" style="color: white;"></icon>
</icon-layer>
```

The result is as expected:

<img width="59" alt="screen shot 2018-04-12 at 10 40 39 am" src="https://user-images.githubusercontent.com/9264860/38662997-3edad17c-3e3e-11e8-9147-7bbadf60ec06.png">

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a **[codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by sleewoo** [comment]
here is the reproduction - https://jz17ypwp69.codesandbox.io/
see the error in console

and here is the sandbox - https://codesandbox.io/s/jz17ypwp69

**Comment by robmadole** [comment]
@sleewoo your `Icon.vue` file has a `v-bind="$attrs"` so you are copying the props on there.

The `@fortawesome/vue-fontawesome` component does not do this.

**Comment by sleewoo** [comment]
how then to wrap `@fortawesome/vue-fontawesome` properly and pass props into it?

**Comment by robmadole** [comment]
There is no need to wrap it. You can use the component as-is. Is there a reason that you are trying to do this? (the wrapping)
