### ISSUE TITLE
For those who get an error with 'far' icons

### ISSUE THREAD

**Issue by julicamb** [FortAwesome/vue-fontawesome#77]
You have to install
`npm i --save @fortawesome/fontawesome-free-regular`
and then add it with 
`import { faCircle, faCheckCircle } from '@fortawesome/fontawesome-free-regular'`

It seems logical when you see it, but since I didn't see 'fontawesome-free-regular' mentionned anywhere on this github I had to look a while to understand that the regular icons aren't were not in the normal fontawesome. Maybe I'm just stupid, anyway, hope this helps

**Comment by jeitnier** [comment]
Great tip @julicamb. I needed this tonight. If you want the same icon from different imports you can just use aliases like this:

```
import {
  faEdit
} from '@fortawesome/fontawesome-free-solid'

import {
  faEdit as faEditRegular
} from '@fortawesome/fontawesome-free-regular'

fontawesome.library.add(
  faEdit,
  faEditRegular
)
```

**Comment by robmadole** [comment]
We've made some improvements to the pre-release documentation:

https://github.com/FortAwesome/vue-fontawesome/tree/development

How does that look?
