### ISSUE TITLE
Cannot read property 'prefix' of undefined

### ISSUE THREAD

**Issue by designbyadrian** [FortAwesome/vue-fontawesome#8]
```
vue.runtime.common.js:561 TypeError: Cannot read property 'prefix' of undefined
    at Object.icon (index.js:1309)
    at render (index.js:243)
    at createFunctionalComponent (vue.runtime.common.js:3519)
    at createComponent (vue.runtime.common.js:3678)
    at _createElement (vue.runtime.common.js:3857)
    at createElement (vue.runtime.common.js:3796)
    at vm._c (vue.runtime.common.js:4136)
```

mycomponent.vue

```
<template>
  <header>
    <h1>Pond</h1> <font-awesome-icon pack="fas" name="check-square" />
  </header>
</template>

<script>
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'

export default {
  name: 'header',
  components: {
    FontAwesomeIcon
  },
}
</script>
```

I at first used npm local import to be able to use the pro collection (as it's not on NPM), then tried regular installation of `@fortawesome/fontawesome` and free-solid.

**Comment by pepzwee** [comment]
Same issue

**Comment by dahrens** [comment]
The error is not verbose at all, I agree.

It occurs if the icon is not included in the pack that you specified or the pack you specified is not present at all.

In my apps main.js i have tje following:

```javascript
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import solid from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(brands, solid)
```

This way the packs `solid` and `brands` are available.

**Comment by designbyadrian** [comment]
@dahrens  Yes, that worked!

Not sure what you mean with 

> I recently discovered that fas and fab are aliases for solid and brands - so you can use it as shown in your sample code.

My code didn't work until I assigned the libraries as per your instructions. I'm still using "fas", though. Do you mean I could also have writted `pack="solid"`?

**Comment by dahrens** [comment]
I was using `pack="solid"`, which also works.

**Comment by robmadole** [comment]
BTW: the API for this has changed a bit with 0.0.16. The README now has some basic usage information.
