### ISSUE TITLE
Linkedin not loading?

### ISSUE THREAD

**Issue by nnagewad** [FortAwesome/vue-fontawesome#81]
I got spinner going but not LinkedIn. What gives?

**Comment by robmadole** [comment]
@nnagewad make sure you are loading the Brands style (and not trying to grab LinkedIn from the Solid style).

If you still are having trouble post a reproducible test case for us to look at (codesandbox.io is a good choice). We'll re-open if you are still having issues.

**Comment by nnagewad** [comment]
Sorry about as suggested here it is: https://codesandbox.io/s/nw44jz37q4

**Comment by nnagewad** [comment]
Thanks for getting back...
I was successful with Solids though. I have a working example up on codesandbox as suggested. https://codesandbox.io/s/nw44jz37q4

**Comment by robmadole** [comment]
For icons that have a different prefix you need to do this:

`:icon="['fab', 'linkedin']"`

**Comment by nnagewad** [comment]
@robmadole I did that and it didn't work.

**Comment by robmadole** [comment]
https://codesandbox.io/s/lyjqyolrol

**Comment by robmadole** [comment]
@nnagewad I forked your codesandbox. Check the `App.vue` and see if that makes things more clear.

**Comment by kyuumeitai** [comment]
Maybe this has to be putted in the readme

**Comment by developing-coder** [comment]
I would recommend adding it here as well. And to similar pages for other frameworks.

https://fontawesome.com/how-to-use/on-the-web/using-with/react

**Comment by KevinPan** [comment]
should be :icon="['fab', 'linkedin']"
works for me, thanks

**Comment by only-js** [comment]
> 
> 
> should be :icon="['fab', 'linkedin']"
> works for me, thanks

Yes, it works for me too :)
Thank you @robmadole
