### ISSUE TITLE
Set prefix with a parameter

### ISSUE THREAD

**Issue by antoine-pous** [FortAwesome/vue-fontawesome#83]
Hi !

Currently when we want set a prefix we need to use an array, this is clearly not developper friendly. My first reflex was to use `prefix="fab" icon="pagelines"`.

Can you implement this usage ? It would be really usefull.

Thank you !

**Comment by robmadole** [comment]
Added some docs on why we chose not to do this @antoine-pous 

https://github.com/FortAwesome/vue-fontawesome/tree/development#why-so-explicit-the-iconfar-coffee-syntax
