### ISSUE TITLE
How to use Pseudo-elements

### ISSUE THREAD

**Issue by paulm17** [FortAwesome/vue-fontawesome#84]
Migrating from a jQuery project to a Vue webpack one.

Everything is working fine, documentation was a bit confusing but got there in the end.

Is there support for pseudo-elements?

Taking an example from: 

    https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

	.login::before {
	  font-family: "Font Awesome 5 Free";
	  font-weight: 900;
	  content: "\f007";
	}

I just get a square.

If someone can provide me with an example, would be most helpful!

**Comment by paulm17** [comment]
Looking at the React issues, I see this referenced here:

    https://github.com/FortAwesome/react-fontawesome/issues/72

I even tried this:

    https://stackoverflow.com/a/48328403

In the end, gave up on the advanced features that webpack offers and instead doing:

	// Font Awesome 
	@import '~@fortawesome/fontawesome-pro-webfonts/scss/fontawesome';
	@import '~@fortawesome/fontawesome-pro-webfonts/scss/fa-brands';
	@import '~@fortawesome/fontawesome-pro-webfonts/scss/fa-solid';
	@import '~@fortawesome/fontawesome-pro-webfonts/scss/fa-regular';

In my laravel app, which adds 258 kB to my app which wasn't there before.

Really hope you guys eventually fix this!

**Comment by robmadole** [comment]
Hi @paulm17. Can you tell us why you need to use pseudo-elements with Vue?

**Comment by paulm17** [comment]
I'm porting a completed application from jCodeigniter and jQuery to Laravel and Webpack/Vuejs/ES6 Javascript.  So a completely new toolchain for me.

I have many areas on my application where I use pseduo-elements.

Here's one such example as an image:

![Registration Form Image](https://i.imgur.com/JhEewr3.png)

I threw this together as a learning exercise.

**Comment by robmadole** [comment]
@paulm17 I would rather not complicate the `vue-fontawesome` component and introduce pseudo-elements. They work best for a situation where you cannot control the markup/HTML. This is not going to be the case for working with Vue. I would recommend using absolute positioning to place actual icons in the page instead.

**Comment by lee-alderdice** [comment]
@robmadole I am using a BS4 template, for the cost vs time it makes sense.  However, they use Pseudo-classes quite extensively for check boxes, radios etc in similar fashion to the above and as per the below.  

```
.form-check .form-check-sign::after {
    font-family: 'Font Awesome 5 Free';
    content: "\f00c";
    top: -1px;
    text-align: center;
    font-size: 15px;
    opacity: 0;
    color: #FFF;
    border: 0;
    background-color: inherit; }


<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input" type="checkbox" value="" checked="">
    <span class="form-check-sign"></span>
    Subscribe to newsletter
  </label>
</div>
```

So is your suggestion that I place the <fontawesome-icon> within the span, position absolute and toggle onClick?

Thanks,
Lee

**Comment by robmadole** [comment]
Lee, that's really up to you. We don't have any specific recommendations.

You might consider switching to web fonts with CSS instead. If you are using another template to save time then it might save you more time to "go with the flow"? ;)

**Comment by jawa-the-hutt** [comment]
Hey...FWIW to future viewers of this issue, there is a StackOverflow Q&A that answers this specific situation and how to move away from pseudo-elements used with FA5.  Takes about 5-10 minutes to migrate your code.  Just did it in a similar BS4 Admin Template project I'm adapting for use.

https://stackoverflow.com/a/48772789/1754955

**Comment by collmomo** [comment]
ommg, I had the same problem, took me a while to realize the package just DOESN'T support it. I understand the choice not to but maybe like a simple warning on the documentation saying, the recommended way is to REFACTOR or download the whole package again would be appreciated and everyone one would save time and be happy... on this note, thanks for the library, I really appreciate it.
