### ISSUE TITLE
Support all features of the SVG Framework

### ISSUE THREAD

**Issue by dahrens** [FortAwesome/vue-fontawesome#9]
Would be awesome if compositions, layers, text overlays and counter badge overlays were supported by the component.

**Comment by dahrens** [comment]
Layers are already supported.

```html
<span class="fa-layers fa-fw">
  <font-awesome-icon pack="fas" name="eye" />
  <font-awesome-icon pack="fas" name="plus" size="sm" transform="right-10"/>
</span>
```

**Comment by robmadole** [comment]
@dahrens 0.0.16 has just been released that includes support for compositions and symbols. Layers, text overlays, and counter badges should be usable already.

**Comment by robmadole** [comment]
@dahrens fair warning that the API has changed slightly in 0.0.16. Please check the README for the details.

**Comment by dahrens** [comment]
Cool - looks promising. Thanks a bunch for the update and the README :) makes it much easier to adopt. - I'll upgrade my project at the weekend.

**Comment by dahrens** [comment]
Using regular expression based search replace it was quite easy to upgrade - if anyone needs to do the same:

replace `pack="(fa[s|b])" :name="([\w-.]*)"` with `:icon="['$1', $2]"`
and
replace  `pack="(fa[s|b])" name="([\w-.]*)"` with `:icon="['$1', '$2']"`

this works as long as you never wrote attributes between pack and name ...
