### ISSUE TITLE
Documentation is seriously lacking (how do I *use* the libraries?)

### ISSUE THREAD

**Issue by akarelas** [FortAwesome/vue-fontawesome#90]
`Vue.use(WHAT?)`

**Comment by akarelas** [comment]
Ok, it's mentioned further down the page. Feel free to delete this ticket, though it makes sense to mention Vue.use or components: {...} above the mention of the <component-name> type of usage

**Comment by robmadole** [comment]
Hey, @akarelas any PRs would be welcome if you think that would clear things up.
