### ISSUE TITLE
Documentation on npm and on github is quite different

### ISSUE THREAD

**Issue by akarelas** [FortAwesome/vue-fontawesome#91]
github says I should:
```
$ npm i --save @fortawesome/fontawesome
$ npm i --save @fortawesome/fontawesome-free-solid
$ npm i --save @fortawesome/vue-fontawesome
```

whereas npmjs says I should:
```
$ npm i --save @fortawesome/fontawesome
$ npm i --save @fortawesome/vue-fontawesome
```

Which of the two is it? And what do each of these three lines mean? And what other available lines are there I could use in their place?

**Comment by robmadole** [comment]
@akarelas we have a pre-release version of this library that includes better documentation.

https://github.com/FortAwesome/vue-fontawesome/tree/development

I would suggest using that version as it should explain things better and we'll be releasing that very soon.
