### ISSUE TITLE
How do I use vue-fontawesome with my PRO account?

### ISSUE THREAD

**Issue by akarelas** [FortAwesome/vue-fontawesome#92]
I've paid for PRO.

What should I do to be able to use the PRO icons in vue-fontawesome? It's not mentioned in the documentation.

**Comment by toadkicker** [comment]
Did you configure a .npmrc or .yarnrc? They have a nice page where you can copy/paste it with your auth token preconfigured.

**Comment by robmadole** [comment]
Our development branch does a bit better job explaining things:

https://github.com/FortAwesome/vue-fontawesome/tree/development

**Comment by Lueton** [comment]
This helped me a lot:
https://code.luasoftware.com/tutorials/npm/fontawesome-5-pro-npm-and-webpack-guide/
To get the token go to the account details in fontawesome and copy the "Pro npm Package Token"
