### ISSUE TITLE
How to toggle font awesome icon on click?

### ISSUE THREAD

**Issue by snowdream** [FortAwesome/vue-fontawesome#94]
How to toggle font awesome icon on click?
I write as follows，but it does not work。
<font-awesome-icon :icon="faAngelLeft" size="2x" class="xyt-icon" style="order:0"
                       @click="$router.back(-1)"/>

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).
