### ISSUE TITLE
Recommendation for use with radio/checkbox?

### ISSUE THREAD

**Issue by timwis** [FortAwesome/vue-fontawesome#96]
Hi folks, thanks for this library! We've used font awesome for a while at beta.phila.gov, via the css-loaded font. We have nice-looking checkbox and radio `<input>`s by hiding the `input` and putting a font-awesome character in the `label:before` via the `content` property. Do you have any advice for how to do this the svg way? I'd love to save them bytes by only loading the icons we need, and I figure this problem's likely already been solved.

I figure I'll have to make my own little checkbox/radio component and bubble up the events (and pass down the props), and I could still use css to show either `<FontAwesomeIcon icon="circle"/>` or `<FontAwesomeIcon icon="check-circle"/>`. Or I could keep the "checked" state of the `<input>` in local state (`data`) and set the `icon` prop using a computed property. Neither solution sounds ideal. What do you recommend?

Thanks and I hope this is an appropriate venue to ask this kind of question.

**Comment by robmadole** [comment]
Hi @timwis. I don't know of a solution for this. Your approach sounds pretty good though :)
