### ISSUE TITLE
Missing icons? Or misplaced expectation?

### ISSUE THREAD

**Issue by seesykescode** [FortAwesome/vue-fontawesome#97]
So I'm working through the documentation and finally got things working. However, I'm noticing icons that I expect to see aren't in the package.

```<font-awesome-icon :icon="['far', 'home']"/>```
yields no results but the font-awesome page does have an far version of home [here](https://fontawesome.com/icons/home?style=regular)

The fas version of home seems to be present and working.

Some icons seem to have far and fas versions available as well, which makes this more confusing
```<font-awesome-icon :icon="['far', 'user]"/>```
```<font-awesome-icon :icon="['fas', 'user]"/>```

Are certain icons not included for all libraries if they're not widely used? Or is there something I may have done incorrectly on importing?

Here is the component i'm working from
```
<template>
    <nav>
        <router-link to="/home">
           <font-awesome-icon :icon="['fas', 'home']"/>
        </router-link> 
        <router-link to="/about">
             <font-awesome-icon :icon="['far', 'user']" />
        </router-link>
        <router-link to="/projects">Projects</router-link>
        <router-link to="/info">Contact</router-link>
    </nav>
</template>
<script>

export default {
  name: "Navbar"
};
</script>

```

and this is my main.js 

```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import fontawesome from '@fortawesome/fontawesome'
import regular from '@fortawesome/fontawesome-free-regular'
import solid from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(regular, solid)
Vue.component("font-awesome-icon", FontAwesomeIcon);


Vue.config.productionTip = false


/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})

```

**Comment by robmadole** [comment]
Hey @seesykescode. The `['far', 'home']` icon is only available in Pro. We make this a little more clear in the pre-release.

https://github.com/FortAwesome/vue-fontawesome/tree/development
