### ISSUE TITLE
Use two styles simultaneously

### ISSUE THREAD

**Issue by cisoun** [FortAwesome/vue-fontawesome#99]
Hello !

I'd like to use two styles (solid and regular) of the same icon.
Unfortunately, I can't import the same icon from both styles because Webpack tells me that `fa{whatever}` has already been declared.

Is there any way to do this ?

The only solution I see is to rename `fa{icon}` to `fa{icon}{style}` (like faCommentRegular/faCommentSolid) in the JS code but I don't want to touch it.

Thanks !

**Comment by robmadole** [comment]
Try this:

```
import { faStroopwafel as fasFaStroopwafel } from '@fortawesome/fontawesome-free-solid'
import { faStroopwafel as farFaStroopwafel } from '@fortawesome/fontawesome-pro-regular'
```
